if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_caching_allocator[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_caching_allocator[1]_tests.cmake")
else()
  add_test(test_caching_allocator_NOT_BUILT test_caching_allocator_NOT_BUILT)
endif()
