if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_mask_rcnn_losses[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_mask_rcnn_losses[1]_tests.cmake")
else()
  add_test(test_mask_rcnn_losses_NOT_BUILT test_mask_rcnn_losses_NOT_BUILT)
endif()
