if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_quantization_conversion[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_quantization_conversion[1]_tests.cmake")
else()
  add_test(test_quantization_conversion_NOT_BUILT test_quantization_conversion_NOT_BUILT)
endif()
