if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_offload_engine[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_offload_engine[1]_tests.cmake")
else()
  add_test(test_offload_engine_NOT_BUILT test_offload_engine_NOT_BUILT)
endif()
