if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_zero_profiling[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_zero_profiling[1]_tests.cmake")
else()
  add_test(test_zero_profiling_NOT_BUILT test_zero_profiling_NOT_BUILT)
endif()
