if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_fused_ops[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_fused_ops[1]_tests.cmake")
else()
  add_test(test_fused_ops_NOT_BUILT test_fused_ops_NOT_BUILT)
endif()
