if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_backend_parity_example[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_backend_parity_example[1]_tests.cmake")
else()
  add_test(test_backend_parity_example_NOT_BUILT test_backend_parity_example_NOT_BUILT)
endif()
