if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_indexing_operator[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_indexing_operator[1]_tests.cmake")
else()
  add_test(test_indexing_operator_NOT_BUILT test_indexing_operator_NOT_BUILT)
endif()
