if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_unet[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_unet[1]_tests.cmake")
else()
  add_test(test_unet_NOT_BUILT test_unet_NOT_BUILT)
endif()
