if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_parameter_offload[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_parameter_offload[1]_tests.cmake")
else()
  add_test(test_parameter_offload_NOT_BUILT test_parameter_offload_NOT_BUILT)
endif()
