if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_bert[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_bert[1]_tests.cmake")
else()
  add_test(test_bert_NOT_BUILT test_bert_NOT_BUILT)
endif()
