if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_cuda_scalar_debug[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_cuda_scalar_debug[1]_tests.cmake")
else()
  add_test(test_cuda_scalar_debug_NOT_BUILT test_cuda_scalar_debug_NOT_BUILT)
endif()
