if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_pruning[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_pruning[1]_tests.cmake")
else()
  add_test(test_pruning_NOT_BUILT test_pruning_NOT_BUILT)
endif()
