if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_yolo[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_yolo[1]_tests.cmake")
else()
  add_test(test_yolo_NOT_BUILT test_yolo_NOT_BUILT)
endif()
