if(EXISTS "/home/lee/Projects/Tenzor/build_transfer/tests/test_async_ops[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_transfer/tests/test_async_ops[1]_tests.cmake")
else()
  add_test(test_async_ops_NOT_BUILT test_async_ops_NOT_BUILT)
endif()
