if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/integration/test_data_pipeline[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/integration/test_data_pipeline[1]_tests.cmake")
else()
  add_test(test_data_pipeline_NOT_BUILT test_data_pipeline_NOT_BUILT)
endif()
