add_test([=[ModelZoo.ResNet18Creation]=]  /home/lee/Projects/Tenzor/bin/test_model_zoo [==[--gtest_filter=ModelZoo.ResNet18Creation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelZoo.ResNet18Creation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests/integration SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ModelZoo.ResNet50Creation]=]  /home/lee/Projects/Tenzor/bin/test_model_zoo [==[--gtest_filter=ModelZoo.ResNet50Creation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelZoo.ResNet50Creation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests/integration SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ModelZoo.ResNetVariants]=]  /home/lee/Projects/Tenzor/bin/test_model_zoo [==[--gtest_filter=ModelZoo.ResNetVariants]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelZoo.ResNetVariants]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests/integration SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ModelZoo.BERTModelCreation]=]  /home/lee/Projects/Tenzor/bin/test_model_zoo [==[--gtest_filter=ModelZoo.BERTModelCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelZoo.BERTModelCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests/integration SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ModelZoo.ResNetFineTuning]=]  /home/lee/Projects/Tenzor/bin/test_model_zoo [==[--gtest_filter=ModelZoo.ResNetFineTuning]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelZoo.ResNetFineTuning]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests/integration SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ModelZoo.InferenceBatchSizeFlexibility]=]  /home/lee/Projects/Tenzor/bin/test_model_zoo [==[--gtest_filter=ModelZoo.InferenceBatchSizeFlexibility]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelZoo.InferenceBatchSizeFlexibility]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests/integration SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ModelZoo.TransferLearningFeatureExtraction]=]  /home/lee/Projects/Tenzor/bin/test_model_zoo [==[--gtest_filter=ModelZoo.TransferLearningFeatureExtraction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelZoo.TransferLearningFeatureExtraction]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests/integration SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ModelZoo.BERTSequenceClassification]=]  /home/lee/Projects/Tenzor/bin/test_model_zoo [==[--gtest_filter=ModelZoo.BERTSequenceClassification]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelZoo.BERTSequenceClassification]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests/integration SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
set(  test_model_zoo_TESTS ModelZoo.ResNet18Creation ModelZoo.ResNet50Creation ModelZoo.ResNetVariants ModelZoo.BERTModelCreation ModelZoo.ResNetFineTuning ModelZoo.InferenceBatchSizeFlexibility ModelZoo.TransferLearningFeatureExtraction ModelZoo.BERTSequenceClassification)
