if(EXISTS "/home/lee/Projects/Tenzor/build_oneapi/tests/test_vulkan_complete_ops[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_oneapi/tests/test_vulkan_complete_ops[1]_tests.cmake")
else()
  add_test(test_vulkan_complete_ops_NOT_BUILT test_vulkan_complete_ops_NOT_BUILT)
endif()
