if(EXISTS "/home/lee/Projects/Tenzor/build_oneapi/tests/test_faster_rcnn[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_oneapi/tests/test_faster_rcnn[1]_tests.cmake")
else()
  add_test(test_faster_rcnn_NOT_BUILT test_faster_rcnn_NOT_BUILT)
endif()
