if(EXISTS "/home/lee/Projects/Tenzor/build_oneapi/tests/test_slice_debug[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_oneapi/tests/test_slice_debug[1]_tests.cmake")
else()
  add_test(test_slice_debug_NOT_BUILT test_slice_debug_NOT_BUILT)
endif()
