if(EXISTS "/home/lee/Projects/Tenzor/build_oneapi/tests/test_bmm_autograd[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_oneapi/tests/test_bmm_autograd[1]_tests.cmake")
else()
  add_test(test_bmm_autograd_NOT_BUILT test_bmm_autograd_NOT_BUILT)
endif()
