if(EXISTS "/home/lee/Projects/Tenzor/build_oneapi/tests/test_contiguous_fix[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_oneapi/tests/test_contiguous_fix[1]_tests.cmake")
else()
  add_test(test_contiguous_fix_NOT_BUILT test_contiguous_fix_NOT_BUILT)
endif()
