if(EXISTS "/home/lee/Projects/Tenzor/build_oneapi/tests/test_normalization[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_oneapi/tests/test_normalization[1]_tests.cmake")
else()
  add_test(test_normalization_NOT_BUILT test_normalization_NOT_BUILT)
endif()
