// Auto-generated file - DO NOT EDIT
// Generated by scripts/embed_shaders.py

#pragma once

#include <cstdint>
#include <cstddef>
#include <string>
#include <unordered_map>

namespace tenzor {
namespace vulkan {
namespace embedded_shaders {

extern const uint32_t activations_data[];
extern const size_t activations_size;

extern const uint32_t activations_backward_data[];
extern const size_t activations_backward_size;

extern const uint32_t activations_backward_f16_data[];
extern const size_t activations_backward_f16_size;

extern const uint32_t activations_backward_f64_data[];
extern const size_t activations_backward_f64_size;

extern const uint32_t activations_f16_data[];
extern const size_t activations_f16_size;

extern const uint32_t activations_f64_data[];
extern const size_t activations_f64_size;

extern const uint32_t adaptive_avg_pool2d_backward_data[];
extern const size_t adaptive_avg_pool2d_backward_size;

extern const uint32_t adaptive_avg_pool2d_backward_f16_data[];
extern const size_t adaptive_avg_pool2d_backward_f16_size;

extern const uint32_t adaptive_avg_pool2d_backward_f64_data[];
extern const size_t adaptive_avg_pool2d_backward_f64_size;

extern const uint32_t adaptive_pooling_data[];
extern const size_t adaptive_pooling_size;

extern const uint32_t adaptive_pooling_f16_data[];
extern const size_t adaptive_pooling_f16_size;

extern const uint32_t adaptive_pooling_f64_data[];
extern const size_t adaptive_pooling_f64_size;

extern const uint32_t argmax_argmin_data[];
extern const size_t argmax_argmin_size;

extern const uint32_t argmax_argmin_i32_data[];
extern const size_t argmax_argmin_i32_size;

extern const uint32_t avg_pool2d_data[];
extern const size_t avg_pool2d_size;

extern const uint32_t avg_pool2d_backward_data[];
extern const size_t avg_pool2d_backward_size;

extern const uint32_t batchnorm_data[];
extern const size_t batchnorm_size;

extern const uint32_t batchnorm2d_backward_data[];
extern const size_t batchnorm2d_backward_size;

extern const uint32_t batchnorm2d_forward_data[];
extern const size_t batchnorm2d_forward_size;

extern const uint32_t batchnorm2d_mean_var_data[];
extern const size_t batchnorm2d_mean_var_size;

extern const uint32_t batchnorm_backward_data[];
extern const size_t batchnorm_backward_size;

extern const uint32_t batchnorm_update_stats_data[];
extern const size_t batchnorm_update_stats_size;

extern const uint32_t batchnorm_update_stats_f16_data[];
extern const size_t batchnorm_update_stats_f16_size;

extern const uint32_t batchnorm_update_stats_f64_data[];
extern const size_t batchnorm_update_stats_f64_size;

extern const uint32_t boolean_reduction_data[];
extern const size_t boolean_reduction_size;

extern const uint32_t cat_data[];
extern const size_t cat_size;

extern const uint32_t clamp_data[];
extern const size_t clamp_size;

extern const uint32_t clamp_f64_data[];
extern const size_t clamp_f64_size;

extern const uint32_t col2im_data[];
extern const size_t col2im_size;

extern const uint32_t comparison_data[];
extern const size_t comparison_size;

extern const uint32_t comparison_bool_data[];
extern const size_t comparison_bool_size;

extern const uint32_t comparison_f64_data[];
extern const size_t comparison_f64_size;

extern const uint32_t comparison_i32_data[];
extern const size_t comparison_i32_size;

extern const uint32_t comparison_i64_data[];
extern const size_t comparison_i64_size;

extern const uint32_t conv2d_data[];
extern const size_t conv2d_size;

extern const uint32_t conv2d_backward_bias_data[];
extern const size_t conv2d_backward_bias_size;

extern const uint32_t conv2d_backward_input_data[];
extern const size_t conv2d_backward_input_size;

extern const uint32_t conv2d_backward_weight_data[];
extern const size_t conv2d_backward_weight_size;

extern const uint32_t conv2d_forward_data[];
extern const size_t conv2d_forward_size;

extern const uint32_t conv2d_forward_f16_data[];
extern const size_t conv2d_forward_f16_size;

extern const uint32_t conv2d_forward_f64_data[];
extern const size_t conv2d_forward_f64_size;

extern const uint32_t conv_transpose2d_forward_data[];
extern const size_t conv_transpose2d_forward_size;

extern const uint32_t cross_entropy_data[];
extern const size_t cross_entropy_size;

extern const uint32_t embedding_data[];
extern const size_t embedding_size;

extern const uint32_t expand_data[];
extern const size_t expand_size;

extern const uint32_t expand_f16_data[];
extern const size_t expand_f16_size;

extern const uint32_t expand_f64_data[];
extern const size_t expand_f64_size;

extern const uint32_t fill_data[];
extern const size_t fill_size;

extern const uint32_t full_data[];
extern const size_t full_size;

extern const uint32_t full_f16_data[];
extern const size_t full_f16_size;

extern const uint32_t full_f64_data[];
extern const size_t full_f64_size;

extern const uint32_t full_i64_data[];
extern const size_t full_i64_size;

extern const uint32_t full_i8_data[];
extern const size_t full_i8_size;

extern const uint32_t full_uint8_data[];
extern const size_t full_uint8_size;

extern const uint32_t gather_data[];
extern const size_t gather_size;

extern const uint32_t gather_relative_position_bias_data[];
extern const size_t gather_relative_position_bias_size;

extern const uint32_t gather_relative_position_bias_f16_data[];
extern const size_t gather_relative_position_bias_f16_size;

extern const uint32_t gather_relative_position_bias_f64_data[];
extern const size_t gather_relative_position_bias_f64_size;

extern const uint32_t group_norm_data[];
extern const size_t group_norm_size;

extern const uint32_t hyperbolic_data[];
extern const size_t hyperbolic_size;

extern const uint32_t im2col_data[];
extern const size_t im2col_size;

extern const uint32_t index_select_data[];
extern const size_t index_select_size;

extern const uint32_t indexing_data[];
extern const size_t indexing_size;

extern const uint32_t layer_norm_data[];
extern const size_t layer_norm_size;

extern const uint32_t layer_norm_f16_data[];
extern const size_t layer_norm_f16_size;

extern const uint32_t layer_norm_f64_data[];
extern const size_t layer_norm_f64_size;

extern const uint32_t log_softmax_data[];
extern const size_t log_softmax_size;

extern const uint32_t log_softmax_backward_data[];
extern const size_t log_softmax_backward_size;

extern const uint32_t log_softmax_backward_f64_data[];
extern const size_t log_softmax_backward_f64_size;

extern const uint32_t log_softmax_f64_data[];
extern const size_t log_softmax_f64_size;

extern const uint32_t masked_select_count_data[];
extern const size_t masked_select_count_size;

extern const uint32_t masked_select_gather_data[];
extern const size_t masked_select_gather_size;

extern const uint32_t math_data[];
extern const size_t math_size;

extern const uint32_t math_broadcast_data[];
extern const size_t math_broadcast_size;

extern const uint32_t math_broadcast_bool_data[];
extern const size_t math_broadcast_bool_size;

extern const uint32_t math_broadcast_f16_data[];
extern const size_t math_broadcast_f16_size;

extern const uint32_t math_broadcast_f64_data[];
extern const size_t math_broadcast_f64_size;

extern const uint32_t math_broadcast_i64_data[];
extern const size_t math_broadcast_i64_size;

extern const uint32_t math_broadcast_i8_data[];
extern const size_t math_broadcast_i8_size;

extern const uint32_t math_broadcast_uint8_data[];
extern const size_t math_broadcast_uint8_size;

extern const uint32_t math_f16_data[];
extern const size_t math_f16_size;

extern const uint32_t math_f64_data[];
extern const size_t math_f64_size;

extern const uint32_t math_i32_data[];
extern const size_t math_i32_size;

extern const uint32_t math_i64_data[];
extern const size_t math_i64_size;

extern const uint32_t math_i8_data[];
extern const size_t math_i8_size;

extern const uint32_t math_uint8_data[];
extern const size_t math_uint8_size;

extern const uint32_t matmul_data[];
extern const size_t matmul_size;

extern const uint32_t matmul_f16_data[];
extern const size_t matmul_f16_size;

extern const uint32_t matmul_f64_data[];
extern const size_t matmul_f64_size;

extern const uint32_t matmul_i32_data[];
extern const size_t matmul_i32_size;

extern const uint32_t max_pool2d_data[];
extern const size_t max_pool2d_size;

extern const uint32_t max_pool2d_backward_data[];
extern const size_t max_pool2d_backward_size;

extern const uint32_t max_pool2d_backward_indices_data[];
extern const size_t max_pool2d_backward_indices_size;

extern const uint32_t max_pool2d_backward_indices_f16_data[];
extern const size_t max_pool2d_backward_indices_f16_size;

extern const uint32_t max_pool2d_backward_indices_f64_data[];
extern const size_t max_pool2d_backward_indices_f64_size;

extern const uint32_t ones_data[];
extern const size_t ones_size;

extern const uint32_t ones_f16_data[];
extern const size_t ones_f16_size;

extern const uint32_t ones_i64_data[];
extern const size_t ones_i64_size;

extern const uint32_t ones_i8_data[];
extern const size_t ones_i8_size;

extern const uint32_t ones_uint8_data[];
extern const size_t ones_uint8_size;

extern const uint32_t permute_data[];
extern const size_t permute_size;

extern const uint32_t pooling_data[];
extern const size_t pooling_size;

extern const uint32_t pooling_backward_data[];
extern const size_t pooling_backward_size;

extern const uint32_t pooling_forward_with_indices_data[];
extern const size_t pooling_forward_with_indices_size;

extern const uint32_t prefix_sum_data[];
extern const size_t prefix_sum_size;

extern const uint32_t prod_reduction_data[];
extern const size_t prod_reduction_size;

extern const uint32_t prod_reduction_i32_data[];
extern const size_t prod_reduction_i32_size;

extern const uint32_t random_data[];
extern const size_t random_size;

extern const uint32_t random_f16_data[];
extern const size_t random_f16_size;

extern const uint32_t random_f64_data[];
extern const size_t random_f64_size;

extern const uint32_t reduction_data[];
extern const size_t reduction_size;

extern const uint32_t reduction_f16_data[];
extern const size_t reduction_f16_size;

extern const uint32_t reduction_f64_data[];
extern const size_t reduction_f64_size;

extern const uint32_t reduction_i32_data[];
extern const size_t reduction_i32_size;

extern const uint32_t scatter_data[];
extern const size_t scatter_size;

extern const uint32_t scatter_f64_data[];
extern const size_t scatter_f64_size;

extern const uint32_t softmax_data[];
extern const size_t softmax_size;

extern const uint32_t softmax_backward_data[];
extern const size_t softmax_backward_size;

extern const uint32_t softmax_backward_f16_data[];
extern const size_t softmax_backward_f16_size;

extern const uint32_t softmax_backward_f64_data[];
extern const size_t softmax_backward_f64_size;

extern const uint32_t softmax_f16_data[];
extern const size_t softmax_f16_size;

extern const uint32_t softmax_f64_data[];
extern const size_t softmax_f64_size;

extern const uint32_t strided_copy_data[];
extern const size_t strided_copy_size;

extern const uint32_t strided_copy_f16_data[];
extern const size_t strided_copy_f16_size;

extern const uint32_t strided_copy_f64_data[];
extern const size_t strided_copy_f64_size;

extern const uint32_t swish_backward_data[];
extern const size_t swish_backward_size;

extern const uint32_t swish_backward_f64_data[];
extern const size_t swish_backward_f64_size;

extern const uint32_t transform_data[];
extern const size_t transform_size;

extern const uint32_t transpose_data[];
extern const size_t transpose_size;

extern const uint32_t trigonometric_data[];
extern const size_t trigonometric_size;

extern const uint32_t variance_std_data[];
extern const size_t variance_std_size;

// Shader registry: maps shader name to (data, size)
struct ShaderData {
    const uint32_t* data;
    size_t size;
};

inline const std::unordered_map<std::string, ShaderData>& getShaderRegistry() {
    static const std::unordered_map<std::string, ShaderData> registry = {
        {"activations", {activations_data, activations_size}},
        {"activations_backward", {activations_backward_data, activations_backward_size}},
        {"activations_backward_f16", {activations_backward_f16_data, activations_backward_f16_size}},
        {"activations_backward_f64", {activations_backward_f64_data, activations_backward_f64_size}},
        {"activations_f16", {activations_f16_data, activations_f16_size}},
        {"activations_f64", {activations_f64_data, activations_f64_size}},
        {"adaptive_avg_pool2d_backward", {adaptive_avg_pool2d_backward_data, adaptive_avg_pool2d_backward_size}},
        {"adaptive_avg_pool2d_backward_f16", {adaptive_avg_pool2d_backward_f16_data, adaptive_avg_pool2d_backward_f16_size}},
        {"adaptive_avg_pool2d_backward_f64", {adaptive_avg_pool2d_backward_f64_data, adaptive_avg_pool2d_backward_f64_size}},
        {"adaptive_pooling", {adaptive_pooling_data, adaptive_pooling_size}},
        {"adaptive_pooling_f16", {adaptive_pooling_f16_data, adaptive_pooling_f16_size}},
        {"adaptive_pooling_f64", {adaptive_pooling_f64_data, adaptive_pooling_f64_size}},
        {"argmax_argmin", {argmax_argmin_data, argmax_argmin_size}},
        {"argmax_argmin_i32", {argmax_argmin_i32_data, argmax_argmin_i32_size}},
        {"avg_pool2d", {avg_pool2d_data, avg_pool2d_size}},
        {"avg_pool2d_backward", {avg_pool2d_backward_data, avg_pool2d_backward_size}},
        {"batchnorm", {batchnorm_data, batchnorm_size}},
        {"batchnorm2d_backward", {batchnorm2d_backward_data, batchnorm2d_backward_size}},
        {"batchnorm2d_forward", {batchnorm2d_forward_data, batchnorm2d_forward_size}},
        {"batchnorm2d_mean_var", {batchnorm2d_mean_var_data, batchnorm2d_mean_var_size}},
        {"batchnorm_backward", {batchnorm_backward_data, batchnorm_backward_size}},
        {"batchnorm_update_stats", {batchnorm_update_stats_data, batchnorm_update_stats_size}},
        {"batchnorm_update_stats_f16", {batchnorm_update_stats_f16_data, batchnorm_update_stats_f16_size}},
        {"batchnorm_update_stats_f64", {batchnorm_update_stats_f64_data, batchnorm_update_stats_f64_size}},
        {"boolean_reduction", {boolean_reduction_data, boolean_reduction_size}},
        {"cat", {cat_data, cat_size}},
        {"clamp", {clamp_data, clamp_size}},
        {"clamp_f64", {clamp_f64_data, clamp_f64_size}},
        {"col2im", {col2im_data, col2im_size}},
        {"comparison", {comparison_data, comparison_size}},
        {"comparison_bool", {comparison_bool_data, comparison_bool_size}},
        {"comparison_f64", {comparison_f64_data, comparison_f64_size}},
        {"comparison_i32", {comparison_i32_data, comparison_i32_size}},
        {"comparison_i64", {comparison_i64_data, comparison_i64_size}},
        {"conv2d", {conv2d_data, conv2d_size}},
        {"conv2d_backward_bias", {conv2d_backward_bias_data, conv2d_backward_bias_size}},
        {"conv2d_backward_input", {conv2d_backward_input_data, conv2d_backward_input_size}},
        {"conv2d_backward_weight", {conv2d_backward_weight_data, conv2d_backward_weight_size}},
        {"conv2d_forward", {conv2d_forward_data, conv2d_forward_size}},
        {"conv2d_forward_f16", {conv2d_forward_f16_data, conv2d_forward_f16_size}},
        {"conv2d_forward_f64", {conv2d_forward_f64_data, conv2d_forward_f64_size}},
        {"conv_transpose2d_forward", {conv_transpose2d_forward_data, conv_transpose2d_forward_size}},
        {"cross_entropy", {cross_entropy_data, cross_entropy_size}},
        {"embedding", {embedding_data, embedding_size}},
        {"expand", {expand_data, expand_size}},
        {"expand_f16", {expand_f16_data, expand_f16_size}},
        {"expand_f64", {expand_f64_data, expand_f64_size}},
        {"fill", {fill_data, fill_size}},
        {"full", {full_data, full_size}},
        {"full_f16", {full_f16_data, full_f16_size}},
        {"full_f64", {full_f64_data, full_f64_size}},
        {"full_i64", {full_i64_data, full_i64_size}},
        {"full_i8", {full_i8_data, full_i8_size}},
        {"full_uint8", {full_uint8_data, full_uint8_size}},
        {"gather", {gather_data, gather_size}},
        {"gather_relative_position_bias", {gather_relative_position_bias_data, gather_relative_position_bias_size}},
        {"gather_relative_position_bias_f16", {gather_relative_position_bias_f16_data, gather_relative_position_bias_f16_size}},
        {"gather_relative_position_bias_f64", {gather_relative_position_bias_f64_data, gather_relative_position_bias_f64_size}},
        {"group_norm", {group_norm_data, group_norm_size}},
        {"hyperbolic", {hyperbolic_data, hyperbolic_size}},
        {"im2col", {im2col_data, im2col_size}},
        {"index_select", {index_select_data, index_select_size}},
        {"indexing", {indexing_data, indexing_size}},
        {"layer_norm", {layer_norm_data, layer_norm_size}},
        {"layer_norm_f16", {layer_norm_f16_data, layer_norm_f16_size}},
        {"layer_norm_f64", {layer_norm_f64_data, layer_norm_f64_size}},
        {"log_softmax", {log_softmax_data, log_softmax_size}},
        {"log_softmax_backward", {log_softmax_backward_data, log_softmax_backward_size}},
        {"log_softmax_backward_f64", {log_softmax_backward_f64_data, log_softmax_backward_f64_size}},
        {"log_softmax_f64", {log_softmax_f64_data, log_softmax_f64_size}},
        {"masked_select_count", {masked_select_count_data, masked_select_count_size}},
        {"masked_select_gather", {masked_select_gather_data, masked_select_gather_size}},
        {"math", {math_data, math_size}},
        {"math_broadcast", {math_broadcast_data, math_broadcast_size}},
        {"math_broadcast_bool", {math_broadcast_bool_data, math_broadcast_bool_size}},
        {"math_broadcast_f16", {math_broadcast_f16_data, math_broadcast_f16_size}},
        {"math_broadcast_f64", {math_broadcast_f64_data, math_broadcast_f64_size}},
        {"math_broadcast_i64", {math_broadcast_i64_data, math_broadcast_i64_size}},
        {"math_broadcast_i8", {math_broadcast_i8_data, math_broadcast_i8_size}},
        {"math_broadcast_uint8", {math_broadcast_uint8_data, math_broadcast_uint8_size}},
        {"math_f16", {math_f16_data, math_f16_size}},
        {"math_f64", {math_f64_data, math_f64_size}},
        {"math_i32", {math_i32_data, math_i32_size}},
        {"math_i64", {math_i64_data, math_i64_size}},
        {"math_i8", {math_i8_data, math_i8_size}},
        {"math_uint8", {math_uint8_data, math_uint8_size}},
        {"matmul", {matmul_data, matmul_size}},
        {"matmul_f16", {matmul_f16_data, matmul_f16_size}},
        {"matmul_f64", {matmul_f64_data, matmul_f64_size}},
        {"matmul_i32", {matmul_i32_data, matmul_i32_size}},
        {"max_pool2d", {max_pool2d_data, max_pool2d_size}},
        {"max_pool2d_backward", {max_pool2d_backward_data, max_pool2d_backward_size}},
        {"max_pool2d_backward_indices", {max_pool2d_backward_indices_data, max_pool2d_backward_indices_size}},
        {"max_pool2d_backward_indices_f16", {max_pool2d_backward_indices_f16_data, max_pool2d_backward_indices_f16_size}},
        {"max_pool2d_backward_indices_f64", {max_pool2d_backward_indices_f64_data, max_pool2d_backward_indices_f64_size}},
        {"ones", {ones_data, ones_size}},
        {"ones_f16", {ones_f16_data, ones_f16_size}},
        {"ones_i64", {ones_i64_data, ones_i64_size}},
        {"ones_i8", {ones_i8_data, ones_i8_size}},
        {"ones_uint8", {ones_uint8_data, ones_uint8_size}},
        {"permute", {permute_data, permute_size}},
        {"pooling", {pooling_data, pooling_size}},
        {"pooling_backward", {pooling_backward_data, pooling_backward_size}},
        {"pooling_forward_with_indices", {pooling_forward_with_indices_data, pooling_forward_with_indices_size}},
        {"prefix_sum", {prefix_sum_data, prefix_sum_size}},
        {"prod_reduction", {prod_reduction_data, prod_reduction_size}},
        {"prod_reduction_i32", {prod_reduction_i32_data, prod_reduction_i32_size}},
        {"random", {random_data, random_size}},
        {"random_f16", {random_f16_data, random_f16_size}},
        {"random_f64", {random_f64_data, random_f64_size}},
        {"reduction", {reduction_data, reduction_size}},
        {"reduction_f16", {reduction_f16_data, reduction_f16_size}},
        {"reduction_f64", {reduction_f64_data, reduction_f64_size}},
        {"reduction_i32", {reduction_i32_data, reduction_i32_size}},
        {"scatter", {scatter_data, scatter_size}},
        {"scatter_f64", {scatter_f64_data, scatter_f64_size}},
        {"softmax", {softmax_data, softmax_size}},
        {"softmax_backward", {softmax_backward_data, softmax_backward_size}},
        {"softmax_backward_f16", {softmax_backward_f16_data, softmax_backward_f16_size}},
        {"softmax_backward_f64", {softmax_backward_f64_data, softmax_backward_f64_size}},
        {"softmax_f16", {softmax_f16_data, softmax_f16_size}},
        {"softmax_f64", {softmax_f64_data, softmax_f64_size}},
        {"strided_copy", {strided_copy_data, strided_copy_size}},
        {"strided_copy_f16", {strided_copy_f16_data, strided_copy_f16_size}},
        {"strided_copy_f64", {strided_copy_f64_data, strided_copy_f64_size}},
        {"swish_backward", {swish_backward_data, swish_backward_size}},
        {"swish_backward_f64", {swish_backward_f64_data, swish_backward_f64_size}},
        {"transform", {transform_data, transform_size}},
        {"transpose", {transpose_data, transpose_size}},
        {"trigonometric", {trigonometric_data, trigonometric_size}},
        {"variance_std", {variance_std_data, variance_std_size}}
    };
    return registry;
}

} // namespace embedded_shaders
} // namespace vulkan
} // namespace tenzor
