/**
 * @file philox_dropout.cpp
 * @brief OneAPI/SYCL device-side Philox4x32-10 dropout mask generator.
 *
 * Audit F13-followup: eliminates the prior CPU fallback in the OneAPI
 * FlashAttention composed-ops dropout path. Previously the mask was built
 * host-side via `tenzor::philox_dropout_mask` and copied to the OneAPI
 * device with `.to(device)`; this kernel writes the mask directly into a
 * device-allocated tensor in a single SYCL parallel_for launch.
 *
 * Counter convention matches the host helper exactly:
 *
 *     ctr = (batch_head, query_idx, kv_pos, offset)   // 3-D or 4-D attention shape
 *     ctr = (linear_index, 0, 0, offset)              // generic shape
 *     key = (seed_low_32, seed_low_32 ^ 0x1BD11BDA)
 *
 * So masks generated by this kernel are bit-exactly identical to those
 * produced by the autograd-level host helper in
 * `src/autograd/function_attention.cpp` and by the CPU host helper in
 * `src/ops/philox_dropout.cpp` — backward replay works regardless of
 * which side produced the forward mask.
 */

#include "tenzor/core/tensor.hpp"
#include "tenzor/core/dtype.hpp"

#include <sycl/sycl.hpp>

#include <cstdint>
#include <stdexcept>
#include <string>
#include <vector>

namespace tenzor::oneapi {

namespace {

class PhiloxDropoutKernelFloat32;
class PhiloxDropoutKernelFloat64;
class PhiloxDropoutKernelFloat16;
class PhiloxDropoutKernelBFloat16;

// Inline Philox4x32-10 round — same constants as `src/ops/philox_dropout.cpp`
// and `src/autograd/function_attention.cpp`. SYCL devices support 64-bit
// multiplication on every backend tenzor currently targets (Intel iGPU,
// dGPU, CPU device).
inline void philox_round_device(uint32_t ctr[4], const uint32_t key[2]) {
    constexpr uint32_t M0 = 0xD2511F53u;
    constexpr uint32_t M1 = 0xCD9E8D57u;
    uint64_t prod0 = static_cast<uint64_t>(M0) * static_cast<uint64_t>(ctr[0]);
    uint64_t prod1 = static_cast<uint64_t>(M1) * static_cast<uint64_t>(ctr[2]);
    uint32_t hi0 = static_cast<uint32_t>(prod0 >> 32);
    uint32_t lo0 = static_cast<uint32_t>(prod0);
    uint32_t hi1 = static_cast<uint32_t>(prod1 >> 32);
    uint32_t lo1 = static_cast<uint32_t>(prod1);
    uint32_t new0 = hi1 ^ ctr[1] ^ key[0];
    uint32_t new1 = lo1;
    uint32_t new2 = hi0 ^ ctr[3] ^ key[1];
    uint32_t new3 = lo0;
    ctr[0] = new0; ctr[1] = new1; ctr[2] = new2; ctr[3] = new3;
}

inline float philox_uniform_device(uint32_t c0, uint32_t c1, uint32_t c2,
                                     uint32_t c3, uint32_t seed_low) {
    constexpr uint32_t W0 = 0x9E3779B9u;
    constexpr uint32_t W1 = 0xBB67AE85u;
    constexpr uint32_t KEY_XOR = 0x1BD11BDAu;
    uint32_t ctr[4] = {c0, c1, c2, c3};
    uint32_t k[2] = {seed_low, seed_low ^ KEY_XOR};
    for (int r = 0; r < 10; ++r) {
        philox_round_device(ctr, k);
        if (r < 9) { k[0] += W0; k[1] += W1; }
    }
    return static_cast<float>(ctr[0] >> 8) * (1.0f / 16777216.0f);
}

template <typename T, typename KernelName>
void launch_philox_mask(T* out_ptr,
                         int64_t total,
                         int64_t bh_dim,
                         int64_t sq_dim,
                         int64_t sk_dim,
                         float p,
                         uint32_t seed_low,
                         uint32_t offset_low,
                         sycl::queue& queue) {
    const float keep_scale = (p < 1.0f) ? (1.0f / (1.0f - p)) : 0.0f;
    const bool attn_addressing =
        (bh_dim > 0 && sq_dim > 0 && sk_dim > 0 &&
         bh_dim * sq_dim * sk_dim == total);

    queue.submit([&](sycl::handler& cgh) {
        cgh.parallel_for<KernelName>(
            sycl::range<1>(static_cast<size_t>(total)),
            [=](sycl::id<1> id) {
                int64_t idx = static_cast<int64_t>(id[0]);
                uint32_t c0, c1, c2;
                if (attn_addressing) {
                    // Decode idx → (bh, qi, ki) matching the host helper's
                    // row-major linearisation of [bh_dim, sq_dim, sk_dim].
                    int64_t ki = idx % sk_dim;
                    int64_t rest = idx / sk_dim;
                    int64_t qi = rest % sq_dim;
                    int64_t bh = rest / sq_dim;
                    c0 = static_cast<uint32_t>(bh);
                    c1 = static_cast<uint32_t>(qi);
                    c2 = static_cast<uint32_t>(ki);
                } else {
                    c0 = static_cast<uint32_t>(idx);
                    c1 = 0;
                    c2 = 0;
                }
                float u = philox_uniform_device(c0, c1, c2, offset_low, seed_low);
                float v = (u >= p) ? keep_scale : 0.0f;
                out_ptr[idx] = static_cast<T>(v);
            });
    }).wait();
}

}  // namespace

/// Build a Philox4x32-keyed pre-scaled Bernoulli mask directly on a OneAPI
/// device. Returns a Tensor allocated on `queue`'s device (no host copy).
auto philox_dropout_mask_kernel(const std::vector<int64_t>& shape,
                                 float p,
                                 uint64_t seed,
                                 uint64_t offset,
                                 DType dtype,
                                 sycl::queue& queue) -> Tensor {
    if (p < 0.0f || p >= 1.0f) {
        throw std::invalid_argument(
            "oneapi::philox_dropout_mask_kernel: dropout probability must be in [0, 1), got " +
            std::to_string(p));
    }

    int64_t total = 1;
    for (auto d : shape) total *= d;

    // Decode attention shape (3-D `[BH, Sq, Sk]` or 4-D `[B, H, Sq, Sk]`)
    // exactly as the host helper does.
    int64_t bh = 0, sq = 0, sk = 0;
    if (shape.size() == 4) {
        bh = shape[0] * shape[1];
        sq = shape[2];
        sk = shape[3];
    } else if (shape.size() == 3) {
        bh = shape[0];
        sq = shape[1];
        sk = shape[2];
    }

    // Allocate output on the OneAPI device — Tensor ctor picks the device
    // from the queue's device index implicitly via the registered backend
    // allocator; we use the queue's associated `Device::oneapi(...)` here.
    auto device_index = 0;  // single-device OneAPI build (matches the rest of the registry)
    Tensor out(std::vector<int64_t>(shape.begin(), shape.end()),
                dtype, Device{Device::Type::OneAPI, device_index});

    const uint32_t seed_low = static_cast<uint32_t>(seed & 0xFFFFFFFFu);
    const uint32_t off_low  = static_cast<uint32_t>(offset & 0xFFFFFFFFu);

    if (dtype == DType::Float32) {
        launch_philox_mask<float, PhiloxDropoutKernelFloat32>(
            static_cast<float*>(const_cast<void*>(out.data_ptr())),
            total, bh, sq, sk, p, seed_low, off_low, queue);
    } else if (dtype == DType::Float64) {
        launch_philox_mask<double, PhiloxDropoutKernelFloat64>(
            static_cast<double*>(const_cast<void*>(out.data_ptr())),
            total, bh, sq, sk, p, seed_low, off_low, queue);
    } else if (dtype == DType::Float16) {
        launch_philox_mask<sycl::half, PhiloxDropoutKernelFloat16>(
            static_cast<sycl::half*>(const_cast<void*>(out.data_ptr())),
            total, bh, sq, sk, p, seed_low, off_low, queue);
    } else if (dtype == DType::BFloat16) {
        // bf16 isn't a first-class SYCL type universally; the OneAPI runtime
        // exposes `sycl::ext::oneapi::bfloat16` on Intel devices but not in
        // a portable way. For BF16 we widen-write via F32 mask + on-device
        // cast: produce the F32 mask, then `out.to(BFloat16)`. The cast
        // itself runs on the OneAPI device, so this is still a fully
        // on-device path (no CPU fallback).
        Tensor mask_f32 = philox_dropout_mask_kernel(shape, p, seed, offset,
                                                       DType::Float32, queue);
        return mask_f32.to(DType::BFloat16);
    } else {
        throw std::runtime_error(
            "oneapi::philox_dropout_mask_kernel: unsupported dtype " +
            std::string(dtype_name(dtype)));
    }

    return out;
}

}  // namespace tenzor::oneapi
