if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/utils/test_utils_config[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/utils/test_utils_config[1]_tests.cmake")
else()
  add_test(test_utils_config_NOT_BUILT test_utils_config_NOT_BUILT)
endif()
