"""
Tenzor: High-performance neural network and tensor library

A PyTorch-compatible deep learning framework with C++ backend for performance.

Basic usage:
    import tenzor as tz

    # Create tensors
    x = tz.randn([3, 4])
    y = tz.zeros([4, 2])

    # Create a neural network
    class MyNet(tz.nn.Module):
        def __init__(self):
            super().__init__()
            self.fc1 = tz.nn.Linear(10, 20)
            self.fc2 = tz.nn.Linear(20, 5)

        def forward(self, x):
            x = tz.nn.relu(self.fc1(x))
            return self.fc2(x)

    model = MyNet()
    model.to("cuda")  # Move to GPU; also "rocm", "vulkan", "oneapi", "mps"

Thread safety:
    The GIL is released during most C++ operations (matmul, conv2d, etc.),
    so Python threads can overlap computation with I/O. However:
    - Variables (autograd tensors) are NOT thread-safe by default.
    - Call var.make_thread_safe() before concurrent gradient accumulation.
    - NoGradGuard is thread-local and does NOT propagate to spawned threads.
    - For data-parallel training, use separate Variable instances per thread
      or call make_thread_safe() on shared parameters.
"""

# Import sys and importlib for module registration
import sys as _sys
import importlib.util as _importlib_util
import os as _os

# Configure optimal thread count before loading C++ library
# This prevents OpenMP from initializing with too many threads
if 'OMP_NUM_THREADS' not in _os.environ:
    try:
        import multiprocessing as _mp
        # S23: underscore-prefix internal locals so they don't leak as
        # ``tenzor.physical_cores`` / ``tenzor.siblings`` public attributes
        # (which then drifted out of __init__.pyi).
        _physical_cores = _mp.cpu_count() or 1
        # On Linux, try to detect hyperthreading to get physical core count
        try:
            with open('/sys/devices/system/cpu/cpu0/topology/thread_siblings_list') as f:
                _siblings = len(f.read().strip().split(','))
                if _siblings > 1:
                    _physical_cores = max(1, _physical_cores // _siblings)
        except (OSError, IOError):
            pass  # Non-Linux: use cpu_count() directly
        _os.environ['OMP_NUM_THREADS'] = str(max(1, _physical_cores))
    except Exception as _omp_detect_exc:
        # Audit item H.1: replace bare `except Exception: pass`.  CPU-count
        # detection isn't critical — the user's OMP_NUM_THREADS / system
        # default still applies — but a bare swallow hid real bugs in the
        # past.  Print a one-line breadcrumb to stderr at WARN level
        # equivalent (Python doesn't have stdlib logging configured yet at
        # this point in module init).
        import sys as _sys_for_warn
        _sys_for_warn.stderr.write(
            f"[tenzor] OMP_NUM_THREADS detection failed: "
            f"{type(_omp_detect_exc).__name__}: {_omp_detect_exc}\n"
        )

# --------------------------------------------------------------------------
# Windows: register vendor SDK directories on the DLL search path before
# importing the native extension.
#
# Windows extension modules (.pyd) have not consulted PATH for their DLL
# dependencies since Python 3.8 -- os.add_dll_directory() must be called
# explicitly for every directory containing a needed DLL, or the import
# fails with a generic "DLL load failed ... The specified module could not
# be found." that gives no hint which of the ~900+ transitive dependencies
# is missing.
#
# On top of that, a Windows loader quirk was found by hand: some of these
# vendor DLLs (confirmed for Intel oneAPI's SYCL/oneDNN runtime) fail to
# resolve their OWN nested dependencies through AddDllDirectory-registered
# search paths when loaded cold, but succeed immediately once those
# dependencies are already resident in the process. So beyond registering
# directories, a curated set of runtime DLLs is pre-loaded by name pattern
# before the native extension is imported.
#
# The directory list comes from _win_dll_dirs.py, generated by CMake at
# configure time from the exact SDK roots this build was configured against
# (see CMakeLists.txt) -- not hardcoded here, so it stays correct across
# oneAPI/CUDA/ROCm version bumps and different install layouts.
if _sys.platform == "win32":
    def _tenzor_win_bootstrap():
        try:
            from . import _win_dll_dirs as _manifest
            dll_dirs = list(_manifest.DLL_DIRS)
        except ImportError:
            # Manifest wasn't generated (e.g. a hand-rolled build setup that
            # doesn't go through CMakeLists.txt's Python bindings block).
            # Nothing to register; import may still fail below with the
            # normal DLL-not-found error.
            dll_dirs = []

        for _d in dll_dirs:
            if _os.path.isdir(_d):
                try:
                    _os.add_dll_directory(_d)
                except (OSError, AttributeError):
                    pass  # add_dll_directory requires Python >= 3.8

        import ctypes as _ctypes
        import glob as _glob
        # Name patterns for the runtime DLLs known to need pre-loading (see
        # module docstring above). A pattern matching nothing on this
        # machine (e.g. no ROCm installed) is simply skipped.
        _preload_patterns = (
            "libmmd.dll", "svml_dispmd.dll", "tbb12.dll", "tbb.dll",
            "ur_win_proxy_loader.dll", "sycl*.dll", "libiomp5md.dll",
            "mkl_core.*.dll", "mkl_intel_thread.*.dll", "mkl_tbb_thread.*.dll",
            "mkl_sequential.*.dll", "dnnl.dll",
            "nvrtc64_*.dll", "hiprtc*.dll", "amdhip64_*.dll",
        )
        for _d in dll_dirs:
            if not _os.path.isdir(_d):
                continue
            for _pattern in _preload_patterns:
                for _dll_path in _glob.glob(_os.path.join(_d, _pattern)):
                    try:
                        _ctypes.WinDLL(_dll_path)
                    except OSError:
                        pass

    _tenzor_win_bootstrap()
    del _tenzor_win_bootstrap

# Import C++ core module first
# NOTE: This will also register tenzor.nn in sys.modules pointing to C++ nn
from .tenzor_core import *

# _foreach_* names start with '_' so are not pulled in by import *; import explicitly.
from .tenzor_core import (
    _foreach_add, _foreach_add_,
    _foreach_sub, _foreach_sub_,
    _foreach_mul, _foreach_mul_,
    _foreach_div, _foreach_div_,
    _foreach_neg, _foreach_neg_,
    _foreach_abs, _foreach_abs_,
    _foreach_sqrt, _foreach_sqrt_,
    _foreach_zero_, _foreach_copy,
    _foreach_addcdiv_, _foreach_addcmul_,
    _foreach_lerp_, _foreach_norm,
)

# Windows: call finalize() deterministically via Python's own atexit, instead
# of relying solely on the C++ library's std::atexit(finalize) safety net.
# tenzor_core.finalize() is idempotent (a no-op past the first call), so this
# does not skip or duplicate that native registration -- it just makes the
# FIRST real call happen earlier and safely, while the interpreter is still
# fully alive, rather than racing against other DLLs' (confirmed: the SYCL
# runtime's) own exit-time cleanup in the C-runtime's process-wide atexit
# cascade -- which reproducibly corrupts the heap at process exit
# (STATUS_STACK_BUFFER_OVERRUN) once the OneAPI backend has real SYCL
# devices/queues to tear down. Verified with a minimal non-Python C++ repro:
# calling finalize() while still "running" never crashes; leaving only the
# native atexit-triggered call to fire during the real shutdown cascade
# always does.
if _sys.platform == "win32":
    import atexit as _atexit
    _atexit.register(finalize)
    del _atexit

# Audit E.10: module-level `from_numpy` convenience. Until now the .pyi
# advertised `tz.from_numpy(array, requires_grad=False)` but the runtime
# only exposed `tz.Tensor.from_numpy(...)`. Expose a thin top-level alias
# so the documented surface matches reality.
def from_numpy(array, requires_grad: bool = False):
    """Create a Tensor (or Variable, if ``requires_grad=True``) from a NumPy array.

    Mirrors ``torch.from_numpy``: zero-copy when the dtype and stride layout
    allow it, otherwise materialises a host copy. The returned tensor lives
    on CPU; move it explicitly with ``.to(device)``.

    .. warning::
        When the zero-copy path is taken, the returned tensor **shares
        memory with** the input NumPy array. With ``requires_grad=True``
        this aliasing extends into the autograd graph: the resulting leaf
        Variable's value is backed by the same buffer as ``array``. Mutating
        ``array`` in place afterwards (e.g. ``array[:] = ...``) silently
        changes the leaf's value out from under autograd, corrupting any
        forward results already computed and the gradients derived from
        them. This matches ``torch.from_numpy`` behaviour. If you intend to
        keep mutating the NumPy array, pass a copy (``array.copy()``) or
        detach the leaf before mutating.
    """
    from .tenzor_core import Tensor as _Tensor, Variable as _Variable
    t = _Tensor.from_numpy(array)
    if requires_grad:
        return _Variable(t, True)
    return t


# Audit B1 (follow-up): module-level ``to_torch`` / ``from_torch`` convenience.
# The C++ interop lives on the ``tenzor.torch_interop`` submodule as
# ``tensor_to_torch`` / ``tensor_from_torch``. These top-level aliases mirror
# ``from_numpy`` (Audit E.10): the documented surface is the short name, and
# delegating to the submodule keeps a single implementation. When the module
# was built without torch support, ``torch_interop`` is the unavailable proxy
# whose attribute access raises a clear ImportError, so the error path is
# preserved.
def to_torch(tensor, requires_grad: bool = False):
    """Convert a Tenzor ``Tensor`` to a PyTorch tensor.

    Delegates to ``tenzor.torch_interop.tensor_to_torch``: zero-copy when the
    dtype, contiguity and device allow it, otherwise materialises a copy.
    ``requires_grad`` requests a PyTorch tensor that tracks gradients.
    """
    return torch_interop.tensor_to_torch(tensor, requires_grad)


def from_torch(torch_tensor, device=None):
    """Convert a PyTorch tensor to a Tenzor ``Tensor``.

    Delegates to ``tenzor.torch_interop.tensor_from_torch``: zero-copy when
    possible, otherwise copies. ``device`` places the result on a specific
    Tenzor device; when ``None`` the PyTorch tensor's own device is honoured.
    """
    return torch_interop.tensor_from_torch(torch_tensor, device)


# ---------------------------------------------------------------------------
# Reproducible seeding across the C++ RNG *and* the Python-side RNGs.
#
# ``from .tenzor_core import *`` above bound ``manual_seed`` to the C++
# ``tenzor::manual_seed``, which only seeds Tenzor's own (C++) generators.
# Several Python-side code paths draw randomness outside that generator:
#
#   * the ``tenzor.distributions`` samplers call ``np.random.*`` on NumPy's
#     *global* RNG;
#   * ``tenzor.data`` samplers / DataLoader worker seeding use Python's
#     ``random`` module global RNG.
#
# Before this wrapper, ``tz.manual_seed(0)`` left those global RNGs untouched,
# so distribution sampling and data shuffling were non-reproducible. Wrap the
# C++ entry point so a single ``manual_seed`` call seeds *all three* RNGs and
# record the value so other Python modules can derive reproducible sub-seeds.
from .tenzor_core import manual_seed as _cpp_manual_seed

_last_manual_seed = None  # set by manual_seed(); read via initial_seed()


def manual_seed(seed: int) -> None:
    """Seed Tenzor's C++ RNG and the Python-side global RNGs.

    Seeds, in order:

    * the C++ Tenzor generators (via ``tenzor_core.manual_seed``), governing
      ops such as ``tz.rand`` / ``tz.randn`` and dropout masks;
    * NumPy's global RNG (``numpy.random.seed``), used by the
      ``tenzor.distributions`` samplers;
    * Python's ``random`` module global RNG, used by the ``tenzor.data``
      samplers and ``DataLoader`` worker seeding.

    After ``tz.manual_seed(s)`` the full sampling pipeline is reproducible.
    """
    global _last_manual_seed
    seed = int(seed)
    _cpp_manual_seed(seed)
    # NumPy's legacy global RNG requires a 32-bit unsigned seed.
    import numpy as _np
    _np.random.seed(seed & 0xFFFFFFFF)
    import random as _random
    _random.seed(seed)
    _last_manual_seed = seed


def initial_seed():
    """Return the seed passed to the most recent ``tz.manual_seed`` call.

    Returns ``None`` if ``manual_seed`` has not been called. Intended for
    Python-side modules that need to derive a reproducible sub-seed.
    """
    return _last_manual_seed


# Import the nn submodule from C++ (keep reference for internal use)
from .tenzor_core import nn as _cpp_nn

# CRITICAL: Manually load tenzor/nn.py to bypass sys.modules cache
# pybind11 registers 'tenzor.nn' pointing to C++ module, so normal import won't work
_nn_path = _os.path.join(_os.path.dirname(__file__), 'nn.py')
_spec = _importlib_util.spec_from_file_location('tenzor.nn', _nn_path)
_nn_module = _importlib_util.module_from_spec(_spec)

# Execute the module to define its contents
_spec.loader.exec_module(_nn_module)

# Override sys.modules with our Python wrapper
_sys.modules['tenzor.nn'] = _nn_module

# Make nn point to the wrapper module which has the enhanced Module class
nn = _nn_module

# Load nn.functional submodule
_func_path = _os.path.join(_os.path.dirname(__file__), 'functional.py')
_func_spec = _importlib_util.spec_from_file_location('tenzor.nn.functional', _func_path)
_func_module = _importlib_util.module_from_spec(_func_spec)
_func_spec.loader.exec_module(_func_module)
_sys.modules['tenzor.nn.functional'] = _func_module
_nn_module.functional = _func_module

# Load data submodule (Dataset, DataLoader, DistributedSampler, etc.)
_data_path = _os.path.join(_os.path.dirname(__file__), 'data.py')
if _os.path.exists(_data_path):
    _data_spec = _importlib_util.spec_from_file_location('tenzor.data', _data_path)
    _data_module = _importlib_util.module_from_spec(_data_spec)
    _data_spec.loader.exec_module(_data_module)
    # Re-attach the C++ data submodules (transforms, datasets) which are
    # registered under tenzor_core.data and would otherwise be shadowed
    # by the pure-Python tenzor.data wrapper that replaces sys.modules
    # ['tenzor.data'] below. Same pattern as tenzor.nn / tenzor.nn.functional.
    from .tenzor_core import data as _cpp_data
    if hasattr(_cpp_data, 'transforms'):
        _data_module.transforms = _cpp_data.transforms
        _sys.modules['tenzor.data.transforms'] = _cpp_data.transforms
    if hasattr(_cpp_data, 'datasets'):
        _data_module.datasets = _cpp_data.datasets
        _sys.modules['tenzor.data.datasets'] = _cpp_data.datasets
    _sys.modules['tenzor.data'] = _data_module
    data = _data_module

# Load autograd submodule with Python Function base class
_autograd_path = _os.path.join(_os.path.dirname(__file__), 'autograd.py')
if _os.path.exists(_autograd_path):
    _autograd_spec = _importlib_util.spec_from_file_location(
        'tenzor.autograd', _autograd_path)
    _autograd_module = _importlib_util.module_from_spec(_autograd_spec)
    _autograd_spec.loader.exec_module(_autograd_module)
    _sys.modules['tenzor.autograd'] = _autograd_module
    autograd = _autograd_module

# audit-10 OO.12: load the composable function-transforms wrapper.  Mirrors
# the autograd pattern: ``from .tenzor_core import *`` above bound
# ``tenzor.func`` to the raw C++ submodule; we override that binding with a
# Python module so ``func.pyi`` has a sibling ``.py`` for check_pyi_drift,
# and so any future Python-side helpers can land here without changing C++.
_func_transforms_path = _os.path.join(_os.path.dirname(__file__), 'func.py')
if _os.path.exists(_func_transforms_path):
    _func_transforms_spec = _importlib_util.spec_from_file_location(
        'tenzor.func', _func_transforms_path)
    _func_transforms_module = _importlib_util.module_from_spec(
        _func_transforms_spec)
    _func_transforms_spec.loader.exec_module(_func_transforms_module)
    _sys.modules['tenzor.func'] = _func_transforms_module
    func = _func_transforms_module

# Expose linalg submodule from C++ bindings (det, inv, solve, svd, qr, etc.)
from .tenzor_core import linalg
_sys.modules['tenzor.linalg'] = linalg

# PyTorch interop submodule (optional + lazy). The libtorch-backed bindings
# live in a separate plugin shared library (tenzor_torch_interop.<abi>.so)
# that tenzor_core dlopens on FIRST use -- NOT at import. This keeps libtorch
# (and its libmpi/libfabric transitive dependencies) out of tenzor_core.so's
# DT_NEEDED, so `import tenzor` succeeds even when libtorch cannot be loaded
# (e.g. oneAPI's setvars.sh shadows the system libfabric with one that lacks
# FABRIC_1.9, which breaks libtorch's libmpi). Only an actual call into
# tenzor.torch_interop / to_torch / from_torch then attempts the dlopen and
# surfaces a clear ImportError if libtorch is unavailable. The shipped
# ``tenzor/torch_interop.pyi`` promises this API unconditionally; the lazy
# proxy below makes that promise resolve to a clear runtime error instead of a
# bare AttributeError when torch support is absent or libtorch won't load.
from . import tenzor_core as _tenzor_core_mod


class _TorchInteropLazy:
    """Lazy proxy for ``tenzor.torch_interop``.

    The first attribute access dlopens the libtorch plugin (via
    ``tenzor_core._load_torch_interop``), caches the real submodule as the
    ``tenzor.torch_interop`` global, and forwards the attribute. If tenzor was
    built without torch support (no ``_load_torch_interop`` on tenzor_core) or
    libtorch cannot be loaded at runtime, a clear ImportError is raised.
    """

    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"):
            raise AttributeError(name)
        global torch_interop
        if not hasattr(_tenzor_core_mod, "_load_torch_interop"):
            raise ImportError(
                "Tenzor was built without PyTorch interop; rebuild with "
                "TENZOR_BUILD_TORCH_INTEROP=ON "
                "(e.g. CMAKE_ARGS=\"-DTENZOR_BUILD_TORCH_INTEROP=ON\" pip install .) "
                "to enable tenzor.torch_interop."
            )
        real = _tenzor_core_mod._load_torch_interop()
        torch_interop = real
        _sys.modules['tenzor.torch_interop'] = real
        return getattr(real, name)


torch_interop = _TorchInteropLazy()
_sys.modules['tenzor.torch_interop'] = torch_interop

# Audit-8 II.12: expose ``tenzor.exceptions`` as a typed-namespace alias to
# the C++ exception classes registered on ``tenzor_core``. This gives users a
# stable ``except tenzor.exceptions.ValueError`` surface that doesn't depend
# on the wildcard ``from .tenzor_core import *`` import order and doesn't
# shadow Python builtins when consumers write ``from tenzor.exceptions
# import ...`` explicitly. The original ``tz.MemoryError``-style attribute
# access continues to work (the typed exception names are still attributes of
# the ``tenzor`` namespace via the wildcard import above).
from . import exceptions as exceptions  # noqa: E402,F401

# Load special functions submodule (Bessel, Erf, Gamma, Ndtr, ...)
# Manually load to bypass the wildcard-import binding of `special` if
# tenzor_core ever grows a `special` submodule (currently it does not, so
# `from . import special` works, but the manual load is robust either way).
_special_path = _os.path.join(_os.path.dirname(__file__), 'special', '__init__.py')
if _os.path.exists(_special_path):
    _special_spec = _importlib_util.spec_from_file_location(
        'tenzor.special', _special_path,
        submodule_search_locations=[_os.path.dirname(_special_path)])
    _special_module = _importlib_util.module_from_spec(_special_spec)
    _sys.modules['tenzor.special'] = _special_module
    _special_spec.loader.exec_module(_special_module)
    special = _special_module
else:  # pragma: no cover — defensive only.
    from . import special as special  # type: ignore
    _sys.modules['tenzor.special'] = special

# Phase 13: MLIR/StableHLO/IREE JIT pipeline.
#
# `from .tenzor_core import *` above bound `tenzor.jit` to the C++ submodule
# `tenzor_core.jit` (a pybind11 module exposing show_graph/show_mlir/... and
# compile_function). The Python user-facing API is the sibling
# `python/tenzor/jit.py` module, which wraps `tenzor_core.jit.compile_function`
# in a @tz.jit decorator plus show_* helpers that accept either a raw fn or
# a wrapped fn. We load the Python module explicitly and re-bind:
#   tz.jit  -> the @tz.jit decorator (callable)
# while `tenzor.jit` as a sys.modules entry points at the Python wrapper so
# `tz.jit.show_graph(fn)` etc. resolve through it.
_jit_path = _os.path.join(_os.path.dirname(__file__), 'jit.py')
if _os.path.exists(_jit_path):
    _jit_spec = _importlib_util.spec_from_file_location('tenzor.jit', _jit_path)
    _jit_mod = _importlib_util.module_from_spec(_jit_spec)
    _sys.modules['tenzor.jit'] = _jit_mod
    _jit_spec.loader.exec_module(_jit_mod)
    jit = _jit_mod.jit  # the decorator (callable)
    # Expose show_* / cache_stats helpers as attributes of the decorator so
    # `tz.jit.show_graph(fn)` works (in addition to `tz._jit_mod.show_graph`).
    for _attr in ('show_graph', 'show_mlir', 'show_stablehlo', 'show_iree',
                  'cache_stats', 'reset_cache_stats', 'JitNotEnabledError'):
        if hasattr(_jit_mod, _attr):
            setattr(jit, _attr, getattr(_jit_mod, _attr))
    # Pre-Phase-13 tests use `tz.jit.trace`, `tz.jit.Compiler`,
    # `tz.jit.export_graph_text`, etc. — these are pybind11 attributes on
    # the C++ submodule `tenzor_core.jit`. To keep both APIs working we
    # also copy every non-private attribute from the C++ submodule onto
    # the Python decorator.
    try:
        from .tenzor_core import jit as _cpp_jit_mod  # type: ignore[import]
        for _attr in dir(_cpp_jit_mod):
            if not _attr.startswith('_') and not hasattr(jit, _attr):
                setattr(jit, _attr, getattr(_cpp_jit_mod, _attr))
    except (ImportError, AttributeError):
        pass
else:  # pragma: no cover — defensive only; jit.py is always shipped.
    from . import jit as _jit_mod  # type: ignore
    jit = _jit_mod.jit
    _sys.modules['tenzor.jit'] = _jit_mod

# Load distributions submodule (pure Python — numpy/scipy backend).
# Manually load because `from . import distributions` would resolve through
# the wildcard-import binding of the C++ submodule `tenzor_core.distributions`
# rather than the sibling Python package `python/tenzor/distributions/`.
_dist_path = _os.path.join(_os.path.dirname(__file__), 'distributions',
                           '__init__.py')
if _os.path.exists(_dist_path):
    _dist_spec = _importlib_util.spec_from_file_location(
        'tenzor.distributions', _dist_path,
        submodule_search_locations=[_os.path.dirname(_dist_path)])
    _dist_module = _importlib_util.module_from_spec(_dist_spec)
    _sys.modules['tenzor.distributions'] = _dist_module
    _dist_spec.loader.exec_module(_dist_module)
    distributions = _dist_module
else:  # pragma: no cover — defensive only.
    from . import distributions as distributions  # type: ignore
    _sys.modules['tenzor.distributions'] = distributions

# ----------------------------------------------------------------
# Phase 2.6 — __tensor_function__ subclass override protocol.
#
# Load the override helper module and wrap a curated set of the most
# commonly used public ops so Tensor subclasses that define
# __tensor_function__ intercept them. Covers:
#   add/sub/mul/div/matmul/bmm/sum/mean/max/min
#
# Users can extend the wrapped set via tz.overrides.implements; see
# tenzor/overrides.py for the full protocol semantics.
# ----------------------------------------------------------------
_overrides_path = _os.path.join(_os.path.dirname(__file__), 'overrides.py')
_overrides_spec = _importlib_util.spec_from_file_location(
    'tenzor.overrides', _overrides_path)
_overrides_module = _importlib_util.module_from_spec(_overrides_spec)
_overrides_spec.loader.exec_module(_overrides_module)
_sys.modules['tenzor.overrides'] = _overrides_module
overrides = _overrides_module

# X.8: `tenzor.optim` was bound as an attribute via `from .tenzor_core import *`
# above (it is a pybind11 submodule), but was never registered in sys.modules.
# That meant `import tenzor.optim as optim` failed with ModuleNotFoundError
# even though `tz.optim.Adam` worked fine.  Register it so the standard import
# form works (matches the pattern used for nn, data, autograd, linalg, etc.).
try:
    from .tenzor_core import optim as _cpp_optim  # type: ignore[import]
    _sys.modules['tenzor.optim'] = _cpp_optim
    optim = _cpp_optim
    # S10: LR-scheduler namespace fix. The C++ bindings register all LR
    # schedulers (StepLR, CyclicLR, OneCycleLR, ...) under the submodule
    # ``tenzor.optim.lr_scheduler.*`` for PyTorch parity, but the .pyi stub
    # and historical usage expect them on the top-level ``tenzor.optim.*``
    # namespace too. Hoist every public name from ``lr_scheduler`` to the
    # parent ``optim`` module so BOTH import paths resolve to the same class.
    if hasattr(_cpp_optim, "lr_scheduler"):
        _lr_sched = _cpp_optim.lr_scheduler
        _sys.modules['tenzor.optim.lr_scheduler'] = _lr_sched
        for _lr_name in dir(_lr_sched):
            if _lr_name.startswith("_"):
                continue
            # Don't clobber an existing attr if pybind11 happened to also
            # register the same name at top level (identity must hold).
            if not hasattr(_cpp_optim, _lr_name):
                setattr(_cpp_optim, _lr_name, getattr(_lr_sched, _lr_name))
        del _lr_name, _lr_sched
except (ImportError, AttributeError):
    pass

# Apply the @implements wrapper to the curated set of common ops.
# Only wrap names that exist on this module (the C++ binding surface
# can vary between builds, so be tolerant).
for _op_name in (
    # Arithmetic
    "add", "sub", "mul", "div", "matmul", "bmm", "dot",
    # Reduction
    "sum", "mean", "max", "min", "prod", "var", "std", "norm",
    "argmax", "argmin", "any", "all",
    # Element-wise math
    "sqrt", "exp", "log", "abs", "neg", "pow", "reciprocal",
    "sin", "cos", "tan", "asin", "acos", "atan",
    "sinh", "cosh", "tanh", "sigmoid",
    "floor", "ceil", "round", "sign", "clamp",
    "log2", "log10", "log1p", "exp2", "expm1",
    "erf", "erfc", "rsqrt", "square",
    # Comparison
    "eq", "ne", "lt", "le", "gt", "ge",
    # Shape
    "reshape", "transpose", "permute", "squeeze", "unsqueeze",
    "flatten", "cat", "stack", "split", "chunk",
    # Indexing
    "gather", "scatter", "index_select", "where", "masked_select",
    # Creation
    "zeros", "ones", "full", "randn", "rand", "arange", "linspace", "eye",
    # Advanced
    "einsum", "topk", "sort", "unique", "flip", "roll",
    # New ops
    "normal", "poisson", "exponential", "bernoulli", "multinomial",
    "cov", "corrcoef", "channel_shuffle",
    "hann_window", "hamming_window", "blackman_window",
    "unique_consecutive",
):
    _op = globals().get(_op_name)
    if _op is not None and callable(_op):
        globals()[_op_name] = overrides.implements(_op)
del _op_name, _op

# ----------------------------------------------------------------
# Ergonomics: `requires_grad=` on tensor-creation functions.
#
# PyTorch parity: ``tz.randn([3, 3], requires_grad=True)`` returns a
# Variable directly instead of requiring the explicit two-step
# ``tz.Variable(tz.randn([3, 3]), requires_grad=True)``. The C++ factory
# bindings return plain Tensors; this thin wrapper intercepts the kwarg
# at the Python boundary (zero overhead when requires_grad is False
# beyond one kwarg check).
# ----------------------------------------------------------------
import functools as _functools
import builtins as _builtins  # `all`/`any`/`min`/`max` are shadowed by tenzor ops above


def _with_requires_grad(fn, variadic_shape: bool = False):
    @_functools.wraps(fn)
    def _factory_wrapper(*args, requires_grad: bool = False, **kwargs):
        # Variadic-shape sugar (``tz.randn(3, 4)`` == ``tz.randn([3, 4])``)
        # for the pure-shape factories, matching the .pyi stubs and PyTorch.
        if variadic_shape and args and _builtins.all(
            isinstance(a, int) and not isinstance(a, bool) for a in args
        ):
            args = (list(args),)
        result = fn(*args, **kwargs)
        # Tensor/Variable merge: factories ALWAYS return a Variable
        # (autograd dormant unless requires_grad=True), so
        #   x = tz.randn(3, 3); x.requires_grad = True
        # works with object identity preserved — PyTorch 0.4 semantics.
        from .tenzor_core import Variable as _V
        if isinstance(result, _V):
            if requires_grad:
                result.requires_grad = True
            return result
        return _V(result, requires_grad)
    return _factory_wrapper


# Pure-shape factories: every positional argument is a dimension, so the
# variadic form is unambiguous. (randint/full/arange/... have leading
# non-shape scalars and keep their list-shape signatures.)
for _factory_name in ("zeros", "ones", "randn", "rand", "empty"):
    _factory = globals().get(_factory_name)
    if _factory is not None and callable(_factory):
        globals()[_factory_name] = _with_requires_grad(_factory, variadic_shape=True)
for _factory_name in (
    "randint", "randperm", "full", "eye", "arange", "linspace", "logspace",
    "tensor",
):
    _factory = globals().get(_factory_name)
    if _factory is not None and callable(_factory):
        globals()[_factory_name] = _with_requires_grad(_factory)
del _factory_name, _factory

# ----------------------------------------------------------------
# Ergonomics: method-style reductions on Variable.
#
# Lets the canonical loss idiom ``(v * v).sum().backward()`` work without
# reaching for the top-level ``tz.sum(...)``. Delegates to the module-level
# autograd-aware functions; only attaches names the C++ binding does not
# already provide.
# ----------------------------------------------------------------
def _attach_variable_methods():
    from .tenzor_core import Variable as _V

    def _make_method(func, name):
        def _method(self, *args, **kwargs):
            return func(self, *args, **kwargs)
        _method.__name__ = name
        _method.__qualname__ = f"Variable.{name}"
        _method.__doc__ = (
            f"Method form of ``tenzor.{name}`` (autograd-aware); "
            f"equivalent to ``tz.{name}(self, ...)``."
        )
        return _method

    for _name in ("sum", "mean", "var", "std", "norm"):
        _func = globals().get(_name)
        if _func is not None and callable(_func) and not hasattr(_V, _name):
            setattr(_V, _name, _make_method(_func, _name))


_attach_variable_methods()
del _attach_variable_methods

# ----------------------------------------------------------------
# Tensor/Variable merge (PyTorch-0.4-style unification).
#
# Three pieces complete the merge started by the factory wrappers above:
#   1. Variable gains the full Tensor method/property surface by
#      delegation to its underlying tensor. Non-autograd methods on an
#      actively-tracking variable FAIL LOUD instead of silently severing
#      the gradient graph (pure reads like .numpy() are always allowed).
#   2. The raw Tensor class gains a read-only ``requires_grad`` (False)
#      so generic code can probe either type uniformly.
#   3. ``tz.Tensor`` becomes a facade whose isinstance()/issubclass()
#      accept BOTH the raw C++ Tensor and Variable, so existing
#      ``isinstance(x, tz.Tensor)`` checks keep passing now that
#      factories return Variables.
# ----------------------------------------------------------------
def _unify_variable_surface():
    from .tenzor_core import Tensor as _T, Variable as _V

    # Pure reads: safe on any variable, never touch the graph.
    _SAFE_READONLY = frozenset({
        "numpy", "item", "tolist", "dim", "size", "ndim", "numel",
        "is_contiguous", "stride", "storage_offset", "data_ptr",
        "device_type", "has_names", "names", "memory_format", "version",
        "is_pinned", "is_quantized", "is_per_channel_quantized",
        "q_scale", "q_zero_point", "q_per_channel_axis",
        "q_per_channel_scales", "q_per_channel_zero_points", "int_repr",
        "dim_index",
    })
    # Constructors/statics stay on Tensor (reachable via the tz.Tensor facade).
    _SKIP = frozenset({"from_numpy", "from_blob"})

    def _wrap_out(out):
        if isinstance(out, _T):
            return _V(out, False)
        if isinstance(out, (list, tuple)):
            return type(out)(_wrap_out(o) for o in out)
        return out

    def _make_delegate(name):
        def _delegate(self, *args, **kwargs):
            if name not in _SAFE_READONLY and self.requires_grad and is_grad_enabled():
                raise RuntimeError(
                    f"Variable.{name}() is not autograd-aware and this "
                    f"variable has requires_grad=True — the gradient graph "
                    f"would be silently severed. Use the autograd-aware "
                    f"tz.{name}(...) if it exists, call .detach() first if "
                    f"you intend to leave the graph, or wrap the call in "
                    f"tz.no_grad() (e.g. for in-place parameter init)."
                )
            out = getattr(self.tensor(), name)(*args, **kwargs)
            return out if name in _SAFE_READONLY else _wrap_out(out)
        _delegate.__name__ = name
        _delegate.__qualname__ = f"Variable.{name}"
        _delegate.__doc__ = f"Delegates to Tensor.{name} on the underlying tensor."
        return _delegate

    def _make_property(name):
        def fget(self):
            return _wrap_out(getattr(self.tensor(), name))
        fget.__name__ = name
        return property(fget, doc=f"Delegates to Tensor.{name}.")

    for _name in dir(_T):
        if _name.startswith("_") or _name in _SKIP or hasattr(_V, _name):
            continue
        _attr = getattr(_T, _name, None)
        if isinstance(_attr, property):
            setattr(_V, _name, _make_property(_name))
        elif callable(_attr):
            setattr(_V, _name, _make_delegate(_name))

    # Raw Tensor: uniform requires_grad probe (always False; raw tensors
    # cannot track gradients — use a factory with requires_grad=True or
    # tz.Variable(t, True), which preserve/establish a Variable identity).
    if not hasattr(_T, "requires_grad"):
        def _t_rg_get(self):
            return False

        def _t_rg_set(self, value):
            raise RuntimeError(
                "Cannot set requires_grad on a raw Tensor: it has no autograd "
                "state to enable in place. Create it as a Variable instead — "
                "tz.<factory>(..., requires_grad=True) or "
                "tz.Variable(tensor, requires_grad=True)."
            )
        _T.requires_grad = property(_t_rg_get, _t_rg_set)


_unify_variable_surface()
del _unify_variable_surface


# ----------------------------------------------------------------
# Tensor/Variable merge: unified op outputs and mixed arithmetic.
#
# 1. Module-level ops (and tz.fft / tz.linalg) lift raw-Tensor outputs to
#    dormant Variables, so the user-facing world is uniformly Variable and
#    chains like ``tz.matmul(a, b) - model(x)`` compose.
# 2. Variable's binary operators lift raw-Tensor operands to dormant
#    Variables (``variable - tensor`` works), and the reflected forms keep
#    autograd when a Variable appears on the right of a raw Tensor.
# ----------------------------------------------------------------
def _unify_op_outputs():
    from .tenzor_core import Tensor as _T, Variable as _V
    _pyb_fn = type(_V.backward)  # pybind11 builtin-function type proxy

    def _lift(out):
        if isinstance(out, _T):
            return _V(out, False)
        if isinstance(out, tuple):
            return tuple(_lift(o) for o in out)
        if isinstance(out, list):
            return [_lift(o) for o in out]
        if isinstance(out, dict):
            return {k: _lift(v) for k, v in out.items()}
        return out

    def _lifting(fn):
        @_functools.wraps(fn)
        def _lifted(*args, **kwargs):
            return _lift(fn(*args, **kwargs))
        return _lifted

    def _is_pyb_function(obj):
        return type(obj).__name__ == "builtin_function_or_method" or \
            type(obj) is _pyb_fn

    # Top-level callables: pybind functions AND the Python wrappers layered
    # earlier (overrides.implements, factory wrappers). Lifting an op that
    # already returns Variables is a no-op passthrough. Classes and modules
    # are excluded structurally; `jit` is excluded because it is a decorator
    # whose identity/attributes are part of the API.
    import types as _types
    _LIFT_EXCLUDE = {"jit", "initialize", "finalize"}
    g = globals()
    for _name in list(g):
        if _name.startswith("_") or _name in _LIFT_EXCLUDE:
            continue
        _obj = g[_name]
        if isinstance(_obj, type) or isinstance(_obj, _types.ModuleType):
            continue
        if _is_pyb_function(_obj) or isinstance(_obj, _types.FunctionType):
            g[_name] = _lifting(_obj)

    # High-traffic pybind submodules used in math chains.
    for _mod in (g.get("fft"), g.get("linalg")):
        if _mod is None:
            continue
        for _name in dir(_mod):
            if _name.startswith("_"):
                continue
            _obj = getattr(_mod, _name)
            if _is_pyb_function(_obj):
                try:
                    setattr(_mod, _name, _lifting(_obj))
                except (AttributeError, TypeError):
                    pass  # read-only module attribute

    # Mixed Variable <op> Tensor arithmetic: lift the raw-Tensor operand.
    def _patch_binop(dunder):
        orig = getattr(_V, dunder, None)
        if orig is None:
            return

        def _binop(self, other, _orig=orig):
            if isinstance(other, _T):
                other = _V(other, False)
            return _orig(self, other)
        _binop.__name__ = dunder
        _binop.__qualname__ = f"Variable.{dunder}"
        setattr(_V, dunder, _binop)

    for _dunder in ("__add__", "__radd__", "__sub__", "__rsub__",
                    "__mul__", "__rmul__", "__truediv__", "__rtruediv__",
                    "__pow__", "__mod__", "__matmul__", "__rmatmul__"):
        _patch_binop(_dunder)

    # Raw Tensor <op> Variable: pybind raises TypeError before Python can
    # try Variable's reflected operator, so route through the (patched)
    # Variable op directly — lifting the raw tensor preserves autograd when
    # the Variable operand is tracking.
    def _patch_tensor_binop(dunder):
        orig = getattr(_T, dunder, None)
        if orig is None:
            return

        def _binop(self, other, _orig=orig, _dunder=dunder):
            if isinstance(other, _V):
                return getattr(_V(self, False), _dunder)(other)
            return _orig(self, other)
        _binop.__name__ = dunder
        _binop.__qualname__ = f"Tensor.{dunder}"
        setattr(_T, dunder, _binop)

    for _dunder in ("__add__", "__sub__", "__mul__", "__truediv__",
                    "__pow__", "__mod__", "__matmul__"):
        _patch_tensor_binop(_dunder)


_unify_op_outputs()
del _unify_op_outputs


class _TensorFacadeMeta(type):
    """Metaclass making ``tz.Tensor`` cover both raw Tensor and Variable.

    After the merge, factories return Variables; the facade keeps every
    existing ``isinstance(x, tz.Tensor)`` / ``issubclass`` check passing for
    both types, while construction and class attributes (``tz.Tensor(...)``,
    ``tz.Tensor.from_numpy``) forward to the raw C++ class.
    """

    def __instancecheck__(cls, instance):
        from .tenzor_core import Tensor as _T, Variable as _V
        return isinstance(instance, (_T, _V))

    def __subclasscheck__(cls, subclass):
        from .tenzor_core import Tensor as _T, Variable as _V
        if subclass is cls:
            return True
        return issubclass(subclass, (_T, _V))

    def __getattr__(cls, name):
        from .tenzor_core import Tensor as _T
        return getattr(_T, name)


class _TensorFacade(metaclass=_TensorFacadeMeta):
    def __new__(cls, *args, **kwargs):
        from .tenzor_core import Tensor as _T
        return _T(*args, **kwargs)


_TensorFacade.__name__ = "Tensor"
_TensorFacade.__qualname__ = "Tensor"
Tensor = _TensorFacade

# Single source of truth for the version: read the installed distribution
# metadata (populated from pyproject.toml's [project].version at build time)
# rather than hardcoding a literal that silently drifts from the package
# version. Falls back to a local-dev marker when the package is imported
# from a source tree that was never `pip install`-ed.
try:
    from importlib.metadata import version as _pkg_version, PackageNotFoundError as _PkgNotFound
    try:
        __version__ = _pkg_version("tenzor")
    except _PkgNotFound:
        __version__ = "0.0.0+local"
    del _pkg_version, _PkgNotFound
except ImportError:  # pragma: no cover - importlib.metadata is stdlib on >=3.8
    __version__ = "0.0.0+local"

__all__ = [
    # Core
    "Tensor",
    "Variable",
    "Device",
    "DeviceType",
    "dtype",
    "tensor",
    "manual_seed",
    "initial_seed",

    # Autograd
    "is_grad_enabled",
    "set_grad_enabled",

    # Tensor creation
    "zeros",
    "ones",
    "randn",
    "rand",
    "randint",
    "eye",
    "arange",
    "linspace",
    "full",
    "empty",
    "randperm",

    # Arithmetic operations
    "matmul",
    "bmm",
    "addmm",
    "addmv",
    "baddbmm",
    "add",
    "sub",
    "mul",
    "div",

    # Reduction operations
    "sum",
    "mean",
    "max",
    "min",
    "argmax",
    "argmin",

    # Math operations
    "sqrt",
    "exp",
    "log",
    "abs",
    "pow",
    "neg",
    "sign",
    "sigmoid",
    "reciprocal",
    "sin",
    "cos",
    "tan",
    "asin",
    "acos",
    "atan",
    "sinh",
    "cosh",
    "tanh",
    "log2",
    "log10",
    "log1p",
    "exp2",
    "expm1",
    "erf",
    "erfc",
    "atan2",
    "fmod",
    "remainder",
    "lerp",
    "floor",
    "ceil",
    "round",

    # Clamping
    "clamp",
    "clamp_min",
    "clamp_max",
    "minimum",
    "maximum",

    # Classification
    "isnan",
    "isinf",
    "isfinite",

    # Logical operations
    "logical_and",
    "logical_or",
    "logical_not",
    "logical_xor",

    # Comparison
    "eq",
    "ne",
    "lt",
    "le",
    "gt",
    "ge",

    # Shape operations
    "reshape",
    "transpose",
    "permute",
    "flatten",
    "squeeze",
    "unsqueeze",
    "contiguous",
    "cat",
    "stack",
    "split",

    # Tensor manipulation
    "triu",
    "tril",
    "diag",
    "trace",
    "flip",
    "chunk",
    "sort",
    "topk",
    "unique",

    # Indexing operations
    "gather",
    "scatter",
    "scatter_add",
    "scatter_reduce",
    "select_scatter",
    "slice_scatter",
    "diagonal_scatter",
    "index_select",
    "masked_select",
    "masked_fill",
    "where",
    "meshgrid",
    "cross",

    # Cumulative operations
    "cumsum",
    "cumprod",
    "logcumsumexp",

    # Histogram / counting
    "bincount",

    # Index reduce
    "index_reduce",

    # Composed math operations
    "diff",
    "logaddexp",
    "logaddexp2",
    "xlogy",
    "tensordot",

    # Search/sampling operations
    "searchsorted",
    "gumbel_softmax",
    "roll",
    "split_with_sizes",

    # Neural network
    "nn",
    "optim",
    "autograd",
    "func",
    "linalg",

    # Submodules
    "fft",
    "sparse",
    "amp",
    "data",

    # Serialization
    "save",
    "load",

    # Utilities
    "cuda_is_available",
    "no_grad",
    "enable_grad",
    "inference_mode",
    "torch_interop",
    "initialize",
    "empty_cache",
    "memory_stats",
    "reset_memory_stats",
    "set_anomaly_detection",
    "is_anomaly_detection_enabled",
    "memory_format",
    "list_backends",
    "is_backend_available",

    # Quantization
    "quantize_per_tensor",
    "qint8",
    "quint8",
    "qint4x2",

    # JIT compilation
    "compile",

    # FP8 scaling
    "fp8_max_value",
    "compute_amax",
    "compute_fp8_scale",
    "quantize_to_fp8",
    "dequantize_from_fp8",

    # Special functions submodule
    "special",

    # Probability distributions submodule
    "distributions",
    "jit",      # @tz.jit decorator (Phase 13 MLIR pipeline)
    "_jit_mod", # full jit submodule for show_*/cache_stats helpers

    # Special functions (also accessible via tz.special.*) — erf, erfc,
    # xlogy are exported from the earlier "Math operations" block to keep
    # __all__ free of duplicates (audit item H.4).
    "erfinv",
    "lgamma",
    "digamma",
    "polygamma",
    "sinc",
    "zeta",
    "ndtri",
    "xlog1py",
    "bessel_j0",
    "bessel_j1",
    "bessel_y0",
    "bessel_y1",
    "bessel_i0",
    "bessel_i1",

    # Tensor utilities (previously missing)
    "allclose",
    "aminmax",
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "bitwise_not",
    "bitwise_left_shift",
    "bitwise_right_shift",
    "block_diag",
    "broadcast_tensors",
    "broadcast_to",
    "cartesian_prod",
    "column_stack",
    "combinations",
    "count_nonzero",
    "cuda_device_count",
    "current_device",
    "deg2rad",
    "dsplit",
    "dstack",
    "enable_auto_checkpoint",
    "expand",
    "float_power",
    "frac",
    "frexp",
    "heaviside",
    "histogramdd",
    "hsplit",
    "hstack",
    "index_add",
    "index_copy",
    "index_fill",
    "isclose",
    "isneginf",
    "isposinf",
    "isreal",
    "kron",
    "ldexp",
    "logit",
    "logspace",
    "moveaxis",
    "movedim",
    "nanmean",
    "nanstd",
    "nansum",
    "nan_to_num",
    "nanvar",
    "narrow_copy",
    "one_hot",
    "oneapi_device_count",
    "oneapi_is_available",
    "pairwise_distance",
    "pdist",
    "pixel_shuffle",
    "pixel_unshuffle",
    "put",
    "rad2deg",
    "randn_with_generator",
    "rand_with_generator",
    "repeat",
    "repeat_interleave",
    "rocm_device_count",
    "rocm_is_available",
    "row_stack",
    "signbit",
    "slice",
    "swapaxes",
    "take",
    "tensor_split",
    "tile",
    "vander",
    "view_as_complex",
    "view_as_real",
    "vsplit",
    "vstack",
    "vulkan_device_count",
    "vulkan_is_available",

    # Multi-tensor foreach optimizer primitives (Phase 9-W2)
    "_foreach_add", "_foreach_add_", "_foreach_sub", "_foreach_sub_",
    "_foreach_mul", "_foreach_mul_", "_foreach_div", "_foreach_div_",
    "_foreach_neg", "_foreach_neg_", "_foreach_abs", "_foreach_abs_",
    "_foreach_sqrt", "_foreach_sqrt_", "_foreach_zero_", "_foreach_copy",
    "_foreach_addcdiv_", "_foreach_addcmul_", "_foreach_lerp_", "_foreach_norm",
]

# Quantized dtype aliases (PyTorch-compatible names)
qint8 = dtype.qint8
quint8 = dtype.quint8
qint4x2 = dtype.qint4x2

# ----------------------------------------------------------------
# Auto-initialization (PyTorch parity: ``import tenzor`` is ready to use).
#
# ``initialize()`` is idempotent, so existing code that calls
# ``tz.initialize()`` explicitly keeps working as a no-op. Set
# TENZOR_AUTO_INIT=0 to defer initialization — useful when environment
# knobs (TENZOR_BACKEND_DIR, TENZOR_SKIP_BACKENDS, ...) must be set from
# Python before the backends load; call ``tz.initialize()`` manually after.
# ----------------------------------------------------------------
if _os.environ.get("TENZOR_AUTO_INIT", "1") != "0":
    initialize()
