"""Type stubs for tenzor core module."""

from __future__ import annotations
from typing import Optional, Tuple, List, Union, Sequence, Any, overload
from enum import Enum
import numpy as np

# Audit-8 II.12: ``tenzor.exceptions`` is the namespaced surface for the
# typed Tenzor exceptions (ShapeError, DTypeError, ValueError, ...). The
# typed exceptions live there rather than at the root to avoid shadowing
# Python builtins on ``from tenzor import *``. Unqualified attribute access
# such as ``tz.ShapeError`` still works at runtime through the wildcard
# import of ``tenzor_core``.
from . import exceptions as exceptions

# Type aliases
Shape = Union[Tuple[int, ...], List[int]]
Scalar = Union[int, float, bool]
ArrayLike = Union[Scalar, Sequence[Scalar], np.ndarray]

class DType(Enum):
    """Data type enumeration."""
    Float32: DType
    Float64: DType
    Float16: DType
    BFloat16: DType
    Int8: DType
    Int16: DType
    Int32: DType
    Int64: DType
    UInt8: DType
    Bool: DType
    Complex64: DType
    Complex128: DType

class DeviceType(Enum):
    """Device type enumeration."""
    CPU: DeviceType
    CUDA: DeviceType
    ROCM: DeviceType
    OneAPI: DeviceType

class Device:
    """Device specification for tensor operations."""

    type: DeviceType
    index: int

    def __init__(self, type: DeviceType, index: int = 0) -> None: ...

    @staticmethod
    def cpu() -> Device: ...

    @staticmethod
    def cuda(index: int = 0) -> Device: ...

    @staticmethod
    def rocm(index: int = 0) -> Device: ...

    @staticmethod
    def oneapi(index: int = 0) -> Device: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Tensor:
    """Multi-dimensional array with automatic differentiation support."""

    def __init__(
        self,
        data: ArrayLike,
        dtype: Optional[DType] = None,
        device: Optional[Device] = None,
        requires_grad: bool = False
    ) -> None: ...

    # Properties
    @property
    def shape(self) -> Tuple[int, ...]: ...

    @property
    def dtype(self) -> DType: ...

    @property
    def device(self) -> Device: ...

    @property
    def is_cuda(self) -> bool: ...

    @property
    def is_cpu(self) -> bool: ...

    @property
    def requires_grad(self) -> bool: ...

    @property
    def grad(self) -> Optional[Tensor]: ...

    @property
    def ndim(self) -> int: ...

    @property
    def size(self) -> Tuple[int, ...]: ...

    def numel(self) -> int: ...

    # Device operations
    def to(self, device: Device) -> Tensor: ...
    def cpu(self) -> Tensor: ...
    def cuda(self, index: int = 0) -> Tensor: ...

    # Type conversions
    def type(self, dtype: DType) -> Tensor: ...
    def float(self) -> Tensor: ...
    def double(self) -> Tensor: ...
    def half(self) -> Tensor: ...
    def bfloat16(self) -> Tensor: ...
    def int(self) -> Tensor: ...
    def long(self) -> Tensor: ...
    def bool(self) -> Tensor: ...

    # Shape operations
    def reshape(self, *shape: int) -> Tensor: ...
    def view(self, *shape: int) -> Tensor: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def permute(self, *dims: int) -> Tensor: ...
    def squeeze(self, dim: Optional[int] = None) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def flatten(self, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def is_contiguous(self) -> bool: ...

    # Indexing and slicing
    def __getitem__(self, key: Any) -> Tensor: ...
    def __setitem__(self, key: Any, value: Union[Tensor, Scalar]) -> None: ...

    # Arithmetic operations
    def __add__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __radd__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __iadd__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __sub__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rsub__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __isub__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __mul__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rmul__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __imul__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __truediv__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rtruediv__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __itruediv__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __pow__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __abs__(self) -> Tensor: ...
    def __mod__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rmod__(self, other: Scalar) -> Tensor: ...
    def __floordiv__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rfloordiv__(self, other: Scalar) -> Tensor: ...

    # Matrix operations
    def matmul(self, other: Tensor) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def mm(self, other: Tensor) -> Tensor: ...
    def bmm(self, other: Tensor) -> Tensor: ...

    # Comparison operations
    def __lt__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __le__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __gt__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __ge__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __eq__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __ne__(self, other: Union[Tensor, Scalar]) -> Tensor: ...

    # Reduction operations
    def sum(self, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
    def mean(self, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
    def max(self, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
    def min(self, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
    def prod(self, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
    def var(self, dim: Optional[int] = None, keepdim: bool = False, unbiased: bool = True) -> Tensor: ...
    def std(self, dim: Optional[int] = None, keepdim: bool = False, unbiased: bool = True) -> Tensor: ...

    # Autograd operations
    def backward(self, gradient: Optional[Tensor] = None, retain_graph: bool = False) -> None: ...
    def detach(self) -> Tensor: ...
    def requires_grad_(self, requires_grad: bool = True) -> Tensor: ...
    def zero_grad(self) -> None: ...

    # Utility operations
    def clone(self) -> Tensor: ...
    def copy_(self, other: Tensor) -> Tensor: ...
    def fill_(self, value: Scalar) -> Tensor: ...
    def zero_(self) -> Tensor: ...
    def item(self) -> Scalar: ...
    def tolist(self) -> List[Any]: ...
    def numpy(self) -> np.ndarray: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    # Pickle support
    def __getstate__(self) -> Tuple[List[int], int, str, bytes]: ...
    def __setstate__(self, state: Tuple[List[int], int, str, bytes]) -> None: ...

class GradFn:
    """Opaque autograd graph node (returned by Variable.grad_fn)."""

    def name(self) -> str: ...
    def __repr__(self) -> str: ...

class Variable:
    """Tensor wrapper with automatic differentiation and gradient tracking."""

    def __init__(self, data: Tensor, requires_grad: bool = False) -> None: ...

    # Properties
    @property
    def data(self) -> Tensor: ...
    @property
    def grad(self) -> Optional[Tensor]: ...
    def set_grad(self, gradient: Tensor) -> None: ...
    @property
    def grad_fn(self) -> Optional[GradFn]: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def is_cuda(self) -> bool: ...
    @property
    def is_cpu(self) -> bool: ...
    # Settable (Tensor/Variable merge): x.requires_grad = True enables
    # gradient tracking in place.
    requires_grad: bool

    # Methods
    def tensor(self) -> Tensor: ...
    def backward(self, gradient: Optional[Tensor] = None, retain_graph: bool = False, create_graph: bool = False) -> None: ...
    # Method-style autograd-aware reductions (delegate to the module-level
    # functions; attached in __init__.py).
    def sum(self, *args: Any, **kwargs: Any) -> Variable: ...
    def mean(self, *args: Any, **kwargs: Any) -> Variable: ...
    def var(self, *args: Any, **kwargs: Any) -> Variable: ...
    def std(self, *args: Any, **kwargs: Any) -> Variable: ...
    def norm(self, *args: Any, **kwargs: Any) -> Variable: ...
    def detach(self) -> Variable: ...
    def zero_grad(self) -> None: ...
    def requires_grad_(self, requires_grad: bool = True) -> Variable: ...
    def register_hook(self, hook: Any) -> int: ...
    def retain_grad(self) -> None: ...

    # Device and type
    def device(self) -> Device: ...
    def dtype(self) -> DType: ...
    def to(self, device: Device) -> Variable: ...

    # Arithmetic operators
    def __add__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __radd__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __sub__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rsub__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __mul__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rmul__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __truediv__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rtruediv__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __pow__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __neg__(self) -> Variable: ...
    def __mod__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rmod__(self, other: Scalar) -> Variable: ...
    def __floordiv__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rfloordiv__(self, other: Scalar) -> Variable: ...
    def __matmul__(self, other: Variable) -> Variable: ...
    def __rmatmul__(self, other: Variable) -> Variable: ...
    def __iadd__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __isub__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __imul__(self, other: Union[Variable, Scalar]) -> Variable: ...

    # Comparison operators (return Tensor, not Variable)
    def __eq__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __ne__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __lt__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __le__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __gt__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __ge__(self, other: Union[Variable, Scalar]) -> Tensor: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    # Pickle support
    def __getstate__(self) -> Tuple[List[int], int, str, bytes, bool]: ...
    def __setstate__(self, state: Tuple[List[int], int, str, bytes, bool]) -> None: ...

# Tensor creation functions
def tensor(
    data: ArrayLike,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def empty(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def zeros(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def ones(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def full(
    shape: Shape,
    fill_value: Scalar,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def randn(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def rand(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def randint(
    low: int,
    high: int,
    size: Shape,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def arange(
    start: Scalar,
    end: Optional[Scalar] = None,
    step: Scalar = 1,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def linspace(
    start: Scalar,
    end: Scalar,
    steps: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def eye(
    n: int,
    m: Optional[int] = None,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def from_numpy(array: np.ndarray, requires_grad: bool = False) -> Tensor: ...

# Math operations
def add(input: Tensor, other: Union[Tensor, Scalar]) -> Tensor: ...
def sub(input: Tensor, other: Union[Tensor, Scalar]) -> Tensor: ...
def mul(input: Tensor, other: Union[Tensor, Scalar]) -> Tensor: ...
def div(input: Tensor, other: Union[Tensor, Scalar]) -> Tensor: ...
def matmul(input: Tensor, other: Tensor) -> Tensor: ...
def bmm(input: Tensor, other: Tensor) -> Tensor: ...
def addmm(input: Tensor, mat1: Tensor, mat2: Tensor, *, beta: float = 1.0, alpha: float = 1.0) -> Tensor: ...
def addmv(input: Tensor, mat: Tensor, vec: Tensor, *, beta: float = 1.0, alpha: float = 1.0) -> Tensor: ...
def baddbmm(input: Tensor, batch1: Tensor, batch2: Tensor, *, beta: float = 1.0, alpha: float = 1.0) -> Tensor: ...
def pow(input: Tensor, exponent: Union[Tensor, Scalar]) -> Tensor: ...
def sqrt(input: Tensor) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def sin(input: Tensor) -> Tensor: ...
def cos(input: Tensor) -> Tensor: ...
def tan(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def abs(input: Tensor) -> Tensor: ...
def sign(input: Tensor) -> Tensor: ...
def floor(input: Tensor) -> Tensor: ...
def ceil(input: Tensor) -> Tensor: ...
def round(input: Tensor) -> Tensor: ...
def clamp(input: Tensor, min: Optional[Scalar] = None, max: Optional[Scalar] = None) -> Tensor: ...

# Reduction operations
def sum(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def mean(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def max(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
def min(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
def argmax(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def argmin(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...

# Concatenation and stacking
def cat(tensors: Sequence[Tensor], dim: int = 0) -> Tensor: ...
def stack(tensors: Sequence[Tensor], dim: int = 0) -> Tensor: ...
def split(tensor: Tensor, split_size_or_sections: Union[int, List[int]], dim: int = 0) -> List[Tensor]: ...
def chunk(tensor: Tensor, chunks: int, dim: int = 0) -> List[Tensor]: ...
def hstack(tensors: Sequence[Tensor]) -> Tensor: ...
def vstack(tensors: Sequence[Tensor]) -> Tensor: ...
def dstack(tensors: Sequence[Tensor]) -> Tensor: ...
@overload
def tensor_split(input: Tensor, sections: int, dim: int = 0) -> List[Tensor]: ...
@overload
def tensor_split(input: Tensor, indices: List[int], dim: int = 0) -> List[Tensor]: ...
def hsplit(input: Tensor, sections: int) -> List[Tensor]: ...
def vsplit(input: Tensor, sections: int) -> List[Tensor]: ...
def dsplit(input: Tensor, sections: int) -> List[Tensor]: ...
def inner(a: Tensor, b: Tensor) -> Tensor: ...
def outer(a: Tensor, b: Tensor) -> Tensor: ...
def vdot(a: Tensor, b: Tensor) -> Tensor: ...

# Autograd context managers
class _NoGradContext:
    """Context manager and decorator to disable gradient computation."""
    def __enter__(self) -> _NoGradContext: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __call__(self, func: Any) -> Any: ...

class _EnableGradContext:
    """Context manager and decorator to enable gradient computation."""
    def __enter__(self) -> _EnableGradContext: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __call__(self, func: Any) -> Any: ...

class _SetGradEnabledContext:
    """Context manager to set gradient computation mode."""
    def __enter__(self) -> _SetGradEnabledContext: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

def no_grad() -> _NoGradContext: ...
def enable_grad() -> _EnableGradContext: ...
def set_grad_enabled(mode: bool) -> _SetGradEnabledContext: ...

# FP8 scaling utilities
def fp8_max_value(fp8_dtype: DType) -> float: ...
def compute_amax(tensor: Tensor) -> float: ...
def compute_fp8_scale(amax: float, fp8_dtype: DType) -> float: ...
def quantize_to_fp8(
    input: Tensor,
    fp8_dtype: DType,
    scale: Optional[float] = None,
    stochastic_rounding: bool = False
) -> Tuple[Tensor, Any]: ...
def dequantize_from_fp8(fp8_tensor: Tensor, scale: float) -> Tensor: ...

# Version info
__version__: str

# ---------------------------------------------------------------------------
# Audit-8 II.12: minimal stubs for runtime classes that were missing from the
# stub but are pulled in via ``from .tenzor_core import *``. Full typing is a
# follow-up; ``class Foo: ...`` documents existence so static checkers stop
# complaining about ``module 'tenzor' has no attribute 'Foo'``.
# ---------------------------------------------------------------------------
class CUDAGraph:
    """CUDA graph capture/replay handle (see tenzor_core)."""

class Event:
    """Backend synchronization event (CUDA / ROCm / OneAPI)."""
    def synchronize(self) -> None: ...
    def record(self, stream: Any = ...) -> None: ...
    def wait(self, stream: Any = ...) -> None: ...
    def elapsed_time(self, end_event: "Event") -> float: ...

class MixedPrecisionConfig: ...
class MixedPrecisionTrainer: ...
class FP8ScalingParams: ...
class FunctionCtx: ...
class Generator: ...
class AutoCheckpointPolicy: ...
class CheckpointStrategy: ...
class DeviceGuard: ...
class DeviceInfo: ...
class TensorFuture: ...
class TensorListFuture: ...

# ---------------------------------------------------------------------------
# Stream S23: .pyi parity sweep.
#
# ``from .tenzor_core import *`` in ``python/tenzor/__init__.py`` bulk-imports
# every pybind11 binding registered on the C++ extension. The block below
# enumerates the runtime surface so static checkers stop reporting
# ``module 'tenzor' has no attribute 'X'``. Signatures are deliberately
# minimal (``def foo(*args: Any, **kwargs: Any) -> Any: ...``) — full
# typing per-op is tracked separately. Adding the names is the load-bearing
# fix: it lets IDEs and mypy/pyright resolve the attributes.
#
# The check_pyi_parity.py drift checker (and its CTest entry
# ``cpu_python_test_pyi_drift``) keeps this list in sync.
# ---------------------------------------------------------------------------

# Sub-packages and pybind11 submodules surfaced via the wildcard import.
from . import autograd as autograd
from . import data as data
from . import distributions as distributions
from . import exceptions as exceptions
from . import func as func
from . import nn as nn
from . import optim as optim
from . import overrides as overrides
from . import special as special

# C++ pybind11 submodules (registered under ``tenzor_core`` and re-exposed
# at the top level by the wildcard import).
from . import tenzor_core as tenzor_core
amp: Any                # mixed-precision sub-namespace (autocast / GradScaler)
async_ops: Any          # async-op submodule
benchmark: Any          # benchmarking sub-namespace (flops, memory submodules)
compression: Any        # tenzor.compression — see compression.pyi
cuda: Any               # tenzor.cuda — CUDA-specific runtime helpers
detection: Any          # object-detection helpers (anchor, NMS, IOU)
distributed: Any        # tenzor.distributed — see distributed.pyi
export_program: Any     # graph-export pipeline (ExportedProgram, …)
fft: Any                # tenzor.fft — see fft.pyi
fused: Any              # fused-op sub-namespace
io: Any                 # tensor (de)serialization helpers
jit: Any                # @tz.jit decorator + show_*/cache_stats — see jit.pyi
lazy: Any               # lazy-tensor execution
linalg: Any             # tenzor.linalg — det, inv, solve, svd, qr, …
lite: Any               # mobile-runtime helpers
models: Any             # tenzor.models — preset architectures (ResNet, …)
monitor: Any            # runtime monitoring (FlightRecorder, etc.)
nested: Any             # nested-tensor helpers
onnx: Any               # ONNX import/export
profiler: Any           # tenzor.profiler — see profiler.pyi
quantization: Any       # tenzor.quantization — see quantization.pyi
serving: Any            # model-serving HTTP/gRPC entry points
sparse: Any             # tenzor.sparse — see sparse.pyi
tensorboard: Any        # TensorBoard summary-writer integration
vision: Any             # vision-domain transforms / layers

# Typed exception namespace surfaced at top level via ``tenzor_core``
# wildcard import (the canonical home is ``tenzor.exceptions``; these
# attribute-access aliases keep ``tz.ShapeError`` working).
class TenzorError(RuntimeError): ...
class ShapeError(TenzorError): ...
class DTypeError(TenzorError): ...
class DeviceError(TenzorError): ...
class AutogradError(TenzorError): ...
class BackendError(TenzorError): ...
class TensorBoardError(TenzorError): ...
class IndexError(IndexError): ...           # type: ignore[no-redef,misc]
class MemoryError(MemoryError): ...         # type: ignore[no-redef,misc]
class NotImplementedError(NotImplementedError): ...  # type: ignore[no-redef,misc]
class RuntimeError(RuntimeError): ...       # type: ignore[no-redef,misc]
class TypeError(TypeError): ...             # type: ignore[no-redef,misc]
class ValueError(ValueError): ...           # type: ignore[no-redef,misc]

# Context managers / decorators exposed by ``tenzor_core``.
class detect_anomaly:
    """Context manager that enables anomaly detection during backward."""
    def __enter__(self) -> "detect_anomaly": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class inference_mode:
    """Context manager that disables autograd and inference-time bookkeeping."""
    def __init__(self, mode: bool = True) -> None: ...
    def __enter__(self) -> "inference_mode": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class offload_activations:
    """Context manager that offloads activations to CPU during forward."""
    def __enter__(self) -> "offload_activations": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

# Top-level dtype / memory_format objects (``tenzor.qint8``, etc.).
dtype: Any
qint4x2: Any
qint8: Any
quint8: Any
channels_last: Any
channels_last_3d: Any
contiguous_format: Any
preserve_format: Any

# Math / elementwise / reduction operations registered by ``tenzor_core``.
def acos(input: Tensor) -> Tensor: ...
def all(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def allclose(input: Tensor, other: Tensor, rtol: float = 1e-05, atol: float = 1e-08, equal_nan: bool = False) -> bool: ...
def aminmax(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tuple[Tensor, Tensor]: ...
def any(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def asin(input: Tensor) -> Tensor: ...
def atan(input: Tensor) -> Tensor: ...
def atan2(input: Tensor, other: Tensor) -> Tensor: ...
def bernoulli(input: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def gamma_sample(concentration: Tensor, rate: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def bessel_i0(input: Tensor) -> Tensor: ...
def bessel_i1(input: Tensor) -> Tensor: ...
def bessel_j0(input: Tensor) -> Tensor: ...
def bessel_j1(input: Tensor) -> Tensor: ...
def bessel_y0(input: Tensor) -> Tensor: ...
def bessel_y1(input: Tensor) -> Tensor: ...
def beta(input: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def betainc(input: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def bincount(input: Tensor, weights: Optional[Tensor] = None, minlength: int = 0) -> Tensor: ...
def bitwise_and(input: Tensor, other: Tensor) -> Tensor: ...
def bitwise_left_shift(input: Tensor, other: Tensor) -> Tensor: ...
def bitwise_not(input: Tensor) -> Tensor: ...
def bitwise_or(input: Tensor, other: Tensor) -> Tensor: ...
def bitwise_right_shift(input: Tensor, other: Tensor) -> Tensor: ...
def bitwise_xor(input: Tensor, other: Tensor) -> Tensor: ...
def blackman_window(window_length: int, *args: Any, **kwargs: Any) -> Tensor: ...
def block_diag(*tensors: Tensor) -> Tensor: ...
def broadcast_tensors(*tensors: Tensor) -> List[Tensor]: ...
def broadcast_to(input: Tensor, shape: Shape) -> Tensor: ...
def cartesian_prod(*tensors: Tensor) -> Tensor: ...
def channel_shuffle(input: Tensor, groups: int) -> Tensor: ...
def clamp_max(input: Tensor, max: Scalar) -> Tensor: ...
def clamp_min(input: Tensor, min: Scalar) -> Tensor: ...
def column_stack(tensors: Sequence[Tensor]) -> Tensor: ...
def combinations(input: Tensor, r: int = 2, with_replacement: bool = False) -> Tensor: ...
def compile(fn: Any = None, *args: Any, **kwargs: Any) -> Any: ...
def contiguous(input: Tensor) -> Tensor: ...
def corrcoef(input: Tensor) -> Tensor: ...
def cosh(input: Tensor) -> Tensor: ...
def count_nonzero(input: Tensor, dim: Optional[int] = None) -> Tensor: ...
def cov(input: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def cross(input: Tensor, other: Tensor, dim: Optional[int] = None) -> Tensor: ...
def cumprod(input: Tensor, dim: int) -> Tensor: ...
def cumsum(input: Tensor, dim: int) -> Tensor: ...
def deg2rad(input: Tensor) -> Tensor: ...
def diag(input: Tensor, diagonal: int = 0) -> Tensor: ...
def diagonal_scatter(input: Tensor, src: Tensor, offset: int = 0, dim1: int = 0, dim2: int = 1) -> Tensor: ...
def diff(input: Tensor, n: int = 1, dim: int = -1) -> Tensor: ...
def digamma(input: Tensor) -> Tensor: ...
def einsum(equation: str, *operands: Tensor) -> Tensor: ...
def eq(input: Tensor, other: Any) -> Tensor: ...
def erf(input: Tensor) -> Tensor: ...
def erfc(input: Tensor) -> Tensor: ...
def erfinv(input: Tensor) -> Tensor: ...
def exp2(input: Tensor) -> Tensor: ...
def expand(input: Tensor, *sizes: int) -> Tensor: ...
def expm1(input: Tensor) -> Tensor: ...
def exponential(input: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def flatten(input: Tensor, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
def flip(input: Tensor, dims: Sequence[int]) -> Tensor: ...
def float_power(input: Tensor, exponent: Any) -> Tensor: ...
def fmod(input: Tensor, other: Any) -> Tensor: ...
def frac(input: Tensor) -> Tensor: ...
def frexp(input: Tensor) -> Tuple[Tensor, Tensor]: ...
def gamma(input: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def gammainc(input: Tensor, other: Tensor) -> Tensor: ...
def gammaincc(input: Tensor, other: Tensor) -> Tensor: ...
def gather(input: Tensor, dim: int, index: Tensor) -> Tensor: ...
def ge(input: Tensor, other: Any) -> Tensor: ...
def gt(input: Tensor, other: Any) -> Tensor: ...
def gumbel_softmax(logits: Tensor, tau: float = 1.0, hard: bool = False, dim: int = -1) -> Tensor: ...
def hamming_window(window_length: int, *args: Any, **kwargs: Any) -> Tensor: ...
def hann_window(window_length: int, *args: Any, **kwargs: Any) -> Tensor: ...
def heaviside(input: Tensor, values: Tensor) -> Tensor: ...
def histogramdd(input: Tensor, *args: Any, **kwargs: Any) -> Any: ...
def index_add(input: Tensor, dim: int, index: Tensor, source: Tensor) -> Tensor: ...
def index_copy(input: Tensor, dim: int, index: Tensor, source: Tensor) -> Tensor: ...
def index_fill(input: Tensor, dim: int, index: Tensor, value: Scalar) -> Tensor: ...
def index_reduce(input: Tensor, dim: int, index: Tensor, source: Tensor, reduce: str) -> Tensor: ...
def index_select(input: Tensor, dim: int, index: Tensor) -> Tensor: ...
def isclose(input: Tensor, other: Tensor, rtol: float = 1e-05, atol: float = 1e-08, equal_nan: bool = False) -> Tensor: ...
def isfinite(input: Tensor) -> Tensor: ...
def isinf(input: Tensor) -> Tensor: ...
def isnan(input: Tensor) -> Tensor: ...
def isneginf(input: Tensor) -> Tensor: ...
def isposinf(input: Tensor) -> Tensor: ...
def isreal(input: Tensor) -> Tensor: ...
def kron(input: Tensor, other: Tensor) -> Tensor: ...
def ldexp(input: Tensor, other: Tensor) -> Tensor: ...
def le(input: Tensor, other: Any) -> Tensor: ...
def lerp(input: Tensor, end: Tensor, weight: Any) -> Tensor: ...
def lgamma(input: Tensor) -> Tensor: ...
def log10(input: Tensor) -> Tensor: ...
def log1p(input: Tensor) -> Tensor: ...
def log2(input: Tensor) -> Tensor: ...
def logaddexp(input: Tensor, other: Tensor) -> Tensor: ...
def logaddexp2(input: Tensor, other: Tensor) -> Tensor: ...
def logcumsumexp(input: Tensor, dim: int) -> Tensor: ...
def logical_and(input: Tensor, other: Tensor) -> Tensor: ...
def logical_not(input: Tensor) -> Tensor: ...
def logical_or(input: Tensor, other: Tensor) -> Tensor: ...
def logical_xor(input: Tensor, other: Tensor) -> Tensor: ...
def logit(input: Tensor, eps: Optional[float] = None) -> Tensor: ...
def logspace(start: Scalar, end: Scalar, steps: int, base: float = 10.0, *args: Any, **kwargs: Any) -> Tensor: ...
def lt(input: Tensor, other: Any) -> Tensor: ...
def masked_fill(input: Tensor, mask: Tensor, value: Scalar) -> Tensor: ...
def masked_select(input: Tensor, mask: Tensor) -> Tensor: ...
def maximum(input: Tensor, other: Tensor) -> Tensor: ...
def median(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Any: ...
def meshgrid(*tensors: Tensor, indexing: str = "ij") -> List[Tensor]: ...
def minimum(input: Tensor, other: Tensor) -> Tensor: ...
def mode(input: Tensor, dim: int = -1, keepdim: bool = False) -> Tuple[Tensor, Tensor]: ...
def moveaxis(input: Tensor, source: Any, destination: Any) -> Tensor: ...
def movedim(input: Tensor, source: Any, destination: Any) -> Tensor: ...
def multinomial(input: Tensor, num_samples: int, replacement: bool = False, *args: Any, **kwargs: Any) -> Tensor: ...
def nan_to_num(input: Tensor, nan: float = 0.0, posinf: Optional[float] = None, neginf: Optional[float] = None) -> Tensor: ...
def nanmean(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def nanstd(input: Tensor, dim: Optional[int] = None, keepdim: bool = False, correction: int = 1) -> Tensor: ...
def nansum(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def nanvar(input: Tensor, dim: Optional[int] = None, keepdim: bool = False, correction: int = 1) -> Tensor: ...
def narrow_copy(input: Tensor, dim: int, start: int, length: int) -> Tensor: ...
def ndtri(input: Tensor) -> Tensor: ...
def ne(input: Tensor, other: Any) -> Tensor: ...
def neg(input: Tensor) -> Tensor: ...
def normal(*args: Any, **kwargs: Any) -> Tensor: ...
def one_hot(input: Tensor, num_classes: int = -1) -> Tensor: ...
def pairwise_distance(x1: Tensor, x2: Tensor, p: float = 2.0, eps: float = 1e-6) -> Tensor: ...
def pdist(input: Tensor, p: float = 2.0) -> Tensor: ...
def permute(input: Tensor, dims: Sequence[int]) -> Tensor: ...
def pixel_shuffle(input: Tensor, upscale_factor: int) -> Tensor: ...
def pixel_unshuffle(input: Tensor, downscale_factor: int) -> Tensor: ...
def poisson(input: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def polygamma(n: int, input: Tensor) -> Tensor: ...
def put(input: Tensor, index: Tensor, source: Tensor, accumulate: bool = False) -> Tensor: ...
def quantize_per_tensor(*args: Any, **kwargs: Any) -> Any: ...
def rad2deg(input: Tensor) -> Tensor: ...
def rand_with_generator(*args: Any, **kwargs: Any) -> Tensor: ...
def randn_with_generator(*args: Any, **kwargs: Any) -> Tensor: ...
def randperm(n: int, *args: Any, **kwargs: Any) -> Tensor: ...
def reciprocal(input: Tensor) -> Tensor: ...
def remainder(input: Tensor, other: Any) -> Tensor: ...
def repeat(input: Tensor, *sizes: int) -> Tensor: ...
def repeat_interleave(input: Tensor, repeats: Any, dim: Optional[int] = None) -> Tensor: ...
def reshape(input: Tensor, *shape: int) -> Tensor: ...
def roll(input: Tensor, shifts: Any, dims: Any = None) -> Tensor: ...
def row_stack(tensors: Sequence[Tensor]) -> Tensor: ...
def scatter(input: Tensor, dim: int, index: Tensor, src: Any) -> Tensor: ...
def scatter_add(input: Tensor, dim: int, index: Tensor, src: Tensor) -> Tensor: ...
def scatter_reduce(input: Tensor, dim: int, index: Tensor, src: Tensor, reduce: str) -> Tensor: ...
def searchsorted(sorted_sequence: Tensor, values: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def select_scatter(input: Tensor, src: Tensor, dim: int, index: int) -> Tensor: ...
def signbit(input: Tensor) -> Tensor: ...
def sinc(input: Tensor) -> Tensor: ...
def sinh(input: Tensor) -> Tensor: ...
def slice(input: Tensor, dim: int, start: int, end: int, step: int = 1) -> Tensor: ...
def slice_scatter(input: Tensor, src: Tensor, dim: int = 0, start: Optional[int] = None, end: Optional[int] = None, step: int = 1) -> Tensor: ...
def sort(input: Tensor, dim: int = -1, descending: bool = False, stable: bool = False) -> Tuple[Tensor, Tensor]: ...
def split_with_sizes(input: Tensor, split_sizes: List[int], dim: int = 0) -> List[Tensor]: ...
def squeeze(input: Tensor, dim: Optional[int] = None) -> Tensor: ...
def swapaxes(input: Tensor, dim0: int, dim1: int) -> Tensor: ...
def take(input: Tensor, index: Tensor) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, dims: Any = 2) -> Tensor: ...
def tile(input: Tensor, dims: Sequence[int]) -> Tensor: ...
def topk(input: Tensor, k: int, dim: int = -1, largest: bool = True, sorted: bool = True) -> Tuple[Tensor, Tensor]: ...
def trace(input: Tensor) -> Tensor: ...
def transpose(input: Tensor, dim0: int, dim1: int) -> Tensor: ...
def tril(input: Tensor, diagonal: int = 0) -> Tensor: ...
def triu(input: Tensor, diagonal: int = 0) -> Tensor: ...
def unbind(input: Tensor, dim: int = 0) -> Tuple[Tensor, ...]: ...
def unique(input: Tensor, *args: Any, **kwargs: Any) -> Any: ...
def unique_consecutive(input: Tensor, *args: Any, **kwargs: Any) -> Any: ...
def unsqueeze(input: Tensor, dim: int) -> Tensor: ...
def vander(x: Tensor, N: Optional[int] = None, increasing: bool = False) -> Tensor: ...
def view_as_complex(input: Tensor) -> Tensor: ...
def view_as_real(input: Tensor) -> Tensor: ...
def where(condition: Tensor, x: Any = None, y: Any = None) -> Tensor: ...
def xlog1py(x: Tensor, y: Any) -> Tensor: ...
def xlogy(x: Tensor, y: Any) -> Tensor: ...
def zeta(x: Tensor, q: Any) -> Tensor: ...

# Backend / device / runtime introspection.
def backend_device_count(backend: str) -> int: ...
def cuda_device_count() -> int: ...
def cuda_is_available() -> bool: ...
def cuda_is_initialized() -> bool: ...
def current_device() -> Device: ...
def dispatch_custom_op(*args: Any, **kwargs: Any) -> Any: ...
def from_dlpack(*args: Any, **kwargs: Any) -> Tensor: ...
def get_all_devices() -> List[Device]: ...
def get_device_info(device: Any) -> Any: ...
def get_device_properties(device: Any) -> Any: ...
def get_supported_ops(*args: Any, **kwargs: Any) -> List[str]: ...
def initialize(*args: Any, **kwargs: Any) -> None: ...
def is_activation_offload_enabled() -> bool: ...
def is_anomaly_detection_enabled() -> bool: ...
def is_backend_available(backend: str) -> bool: ...
def is_deterministic() -> bool: ...
def is_grad_enabled() -> bool: ...
def is_inference_mode() -> bool: ...
def list_backends() -> List[str]: ...
def manual_seed(seed: int) -> None: ...
def memory_format(*args: Any, **kwargs: Any) -> Any: ...
def memory_stats(*args: Any, **kwargs: Any) -> Any: ...
def memory_profiler_stats(*args: Any, **kwargs: Any) -> Any: ...
def memory_profiler_summary(*args: Any, **kwargs: Any) -> Any: ...
def mkl_cleanup() -> None: ...
def mps_device_count() -> int: ...
def mps_is_available() -> bool: ...
def empty_cache(*args: Any, **kwargs: Any) -> None: ...
def enable_auto_checkpoint(*args: Any, **kwargs: Any) -> Any: ...
def oneapi_device_count() -> int: ...
def oneapi_is_available() -> bool: ...
def oneapi_is_initialized() -> bool: ...
def op_count(*args: Any, **kwargs: Any) -> Any: ...
def register_custom_op(*args: Any, **kwargs: Any) -> Any: ...
def reset_memory_stats(*args: Any, **kwargs: Any) -> None: ...
def reset_peak_memory_stats(*args: Any, **kwargs: Any) -> None: ...
def rocm_device_count() -> int: ...
def rocm_is_available() -> bool: ...
def rocm_is_initialized() -> bool: ...
def save(*args: Any, **kwargs: Any) -> None: ...
def load(*args: Any, **kwargs: Any) -> Any: ...
def set_activation_offload(enabled: bool) -> None: ...
def set_anomaly_detection(enabled: bool) -> None: ...
def set_deterministic(enabled: bool) -> None: ...
def set_max_cached_bytes(*args: Any, **kwargs: Any) -> None: ...
def supports_op(*args: Any, **kwargs: Any) -> bool: ...
def vulkan_device_count() -> int: ...
def vulkan_is_available() -> bool: ...
def vulkan_is_initialized() -> bool: ...

# Higher-order / function-transform helpers (also reachable via tenzor.func).
def hessian(*args: Any, **kwargs: Any) -> Any: ...
def jacobian(*args: Any, **kwargs: Any) -> Any: ...
def jvp(*args: Any, **kwargs: Any) -> Any: ...
def vmap(*args: Any, **kwargs: Any) -> Any: ...

# Mixed-precision trainer constructors.
def create_bfloat16_trainer(*args: Any, **kwargs: Any) -> MixedPrecisionTrainer: ...
def create_fp16_trainer(*args: Any, **kwargs: Any) -> MixedPrecisionTrainer: ...

