"""Type stubs for tenzor core module."""

from __future__ import annotations
from typing import Optional, Tuple, List, Union, Sequence, Any, overload
from enum import Enum
import numpy as np

# Type aliases
Shape = Union[Tuple[int, ...], List[int]]
Scalar = Union[int, float, bool]
ArrayLike = Union[Scalar, Sequence[Scalar], np.ndarray]

class DType(Enum):
    """Data type enumeration."""
    Float32: DType
    Float64: DType
    Float16: DType
    BFloat16: DType
    Int8: DType
    Int16: DType
    Int32: DType
    Int64: DType
    UInt8: DType
    Bool: DType
    Complex64: DType
    Complex128: DType

class DeviceType(Enum):
    """Device type enumeration."""
    CPU: DeviceType
    CUDA: DeviceType
    ROCM: DeviceType
    OneAPI: DeviceType

class Device:
    """Device specification for tensor operations."""

    type: DeviceType
    index: int

    def __init__(self, type: DeviceType, index: int = 0) -> None: ...

    @staticmethod
    def cpu() -> Device: ...

    @staticmethod
    def cuda(index: int = 0) -> Device: ...

    @staticmethod
    def rocm(index: int = 0) -> Device: ...

    @staticmethod
    def oneapi(index: int = 0) -> Device: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Tensor:
    """Multi-dimensional array with automatic differentiation support."""

    def __init__(
        self,
        data: ArrayLike,
        dtype: Optional[DType] = None,
        device: Optional[Device] = None,
        requires_grad: bool = False
    ) -> None: ...

    # Properties
    @property
    def shape(self) -> Tuple[int, ...]: ...

    @property
    def dtype(self) -> DType: ...

    @property
    def device(self) -> Device: ...

    @property
    def is_cuda(self) -> bool: ...

    @property
    def is_cpu(self) -> bool: ...

    @property
    def requires_grad(self) -> bool: ...

    @property
    def grad(self) -> Optional[Tensor]: ...

    @property
    def ndim(self) -> int: ...

    @property
    def size(self) -> Tuple[int, ...]: ...

    def numel(self) -> int: ...

    # Device operations
    def to(self, device: Device) -> Tensor: ...
    def cpu(self) -> Tensor: ...
    def cuda(self, index: int = 0) -> Tensor: ...

    # Type conversions
    def type(self, dtype: DType) -> Tensor: ...
    def float(self) -> Tensor: ...
    def double(self) -> Tensor: ...
    def half(self) -> Tensor: ...
    def bfloat16(self) -> Tensor: ...
    def int(self) -> Tensor: ...
    def long(self) -> Tensor: ...
    def bool(self) -> Tensor: ...

    # Shape operations
    def reshape(self, *shape: int) -> Tensor: ...
    def view(self, *shape: int) -> Tensor: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def permute(self, *dims: int) -> Tensor: ...
    def squeeze(self, dim: Optional[int] = None) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def flatten(self, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def is_contiguous(self) -> bool: ...

    # Indexing and slicing
    def __getitem__(self, key: Any) -> Tensor: ...
    def __setitem__(self, key: Any, value: Union[Tensor, Scalar]) -> None: ...

    # Arithmetic operations
    def __add__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __radd__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __iadd__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __sub__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rsub__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __isub__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __mul__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rmul__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __imul__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __truediv__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rtruediv__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __itruediv__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __pow__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __abs__(self) -> Tensor: ...
    def __mod__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rmod__(self, other: Scalar) -> Tensor: ...
    def __floordiv__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __rfloordiv__(self, other: Scalar) -> Tensor: ...

    # Matrix operations
    def matmul(self, other: Tensor) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def mm(self, other: Tensor) -> Tensor: ...
    def bmm(self, other: Tensor) -> Tensor: ...

    # Comparison operations
    def __lt__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __le__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __gt__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __ge__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __eq__(self, other: Union[Tensor, Scalar]) -> Tensor: ...
    def __ne__(self, other: Union[Tensor, Scalar]) -> Tensor: ...

    # Reduction operations
    def sum(self, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> Tensor: ...
    def mean(self, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> Tensor: ...
    def max(self, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
    def min(self, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
    def prod(self, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> Tensor: ...
    def var(self, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False, unbiased: bool = True) -> Tensor: ...
    def std(self, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False, unbiased: bool = True) -> Tensor: ...

    # Autograd operations
    def backward(self, gradient: Optional[Tensor] = None, retain_graph: bool = False) -> None: ...
    def detach(self) -> Tensor: ...
    def requires_grad_(self, requires_grad: bool = True) -> Tensor: ...
    def zero_grad(self) -> None: ...

    # Utility operations
    def clone(self) -> Tensor: ...
    def copy_(self, other: Tensor) -> Tensor: ...
    def fill_(self, value: Scalar) -> Tensor: ...
    def zero_(self) -> Tensor: ...
    def item(self) -> Scalar: ...
    def tolist(self) -> List[Any]: ...
    def numpy(self) -> np.ndarray: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    # Pickle support
    def __getstate__(self) -> Tuple[List[int], int, str, bytes]: ...
    def __setstate__(self, state: Tuple[List[int], int, str, bytes]) -> None: ...

class Variable:
    """Tensor wrapper with automatic differentiation and gradient tracking."""

    def __init__(self, data: Tensor, requires_grad: bool = False) -> None: ...

    # Properties
    @property
    def data(self) -> Tensor: ...
    @property
    def grad(self) -> Optional[Tensor]: ...
    @property
    def grad_fn(self) -> Optional[Any]: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def is_cuda(self) -> bool: ...
    @property
    def is_cpu(self) -> bool: ...
    @property
    def requires_grad(self) -> bool: ...

    # Methods
    def tensor(self) -> Tensor: ...
    def backward(self, gradient: Optional[Tensor] = None, retain_graph: bool = False, create_graph: bool = False) -> None: ...
    def detach(self) -> Variable: ...
    def zero_grad(self) -> None: ...
    def requires_grad_(self, requires_grad: bool = True) -> Variable: ...
    def register_hook(self, hook: Any) -> int: ...
    def retain_grad(self) -> None: ...

    # Device and type
    def device(self) -> Device: ...
    def dtype(self) -> DType: ...
    def to(self, device: Device) -> Variable: ...

    # Arithmetic operators
    def __add__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __radd__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __sub__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rsub__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __mul__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rmul__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __truediv__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rtruediv__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __pow__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __neg__(self) -> Variable: ...
    def __mod__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rmod__(self, other: Scalar) -> Variable: ...
    def __floordiv__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __rfloordiv__(self, other: Scalar) -> Variable: ...
    def __matmul__(self, other: Variable) -> Variable: ...
    def __rmatmul__(self, other: Variable) -> Variable: ...
    def __iadd__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __isub__(self, other: Union[Variable, Scalar]) -> Variable: ...
    def __imul__(self, other: Union[Variable, Scalar]) -> Variable: ...

    # Comparison operators (return Tensor, not Variable)
    def __eq__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __ne__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __lt__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __le__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __gt__(self, other: Union[Variable, Scalar]) -> Tensor: ...
    def __ge__(self, other: Union[Variable, Scalar]) -> Tensor: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    # Pickle support
    def __getstate__(self) -> Tuple[List[int], int, str, bytes, bool]: ...
    def __setstate__(self, state: Tuple[List[int], int, str, bytes, bool]) -> None: ...

# Tensor creation functions
def tensor(
    data: ArrayLike,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def empty(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def zeros(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def ones(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def full(
    shape: Shape,
    fill_value: Scalar,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def randn(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def rand(
    *shape: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def randint(
    low: int,
    high: int,
    size: Shape,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def arange(
    start: Scalar,
    end: Optional[Scalar] = None,
    step: Scalar = 1,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def linspace(
    start: Scalar,
    end: Scalar,
    steps: int,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def eye(
    n: int,
    m: Optional[int] = None,
    dtype: Optional[DType] = None,
    device: Optional[Device] = None,
    requires_grad: bool = False
) -> Tensor: ...

def from_numpy(array: np.ndarray, requires_grad: bool = False) -> Tensor: ...

# Math operations
def add(input: Tensor, other: Union[Tensor, Scalar]) -> Tensor: ...
def sub(input: Tensor, other: Union[Tensor, Scalar]) -> Tensor: ...
def mul(input: Tensor, other: Union[Tensor, Scalar]) -> Tensor: ...
def div(input: Tensor, other: Union[Tensor, Scalar]) -> Tensor: ...
def matmul(input: Tensor, other: Tensor) -> Tensor: ...
def bmm(input: Tensor, other: Tensor) -> Tensor: ...
def pow(input: Tensor, exponent: Union[Tensor, Scalar]) -> Tensor: ...
def sqrt(input: Tensor) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def sin(input: Tensor) -> Tensor: ...
def cos(input: Tensor) -> Tensor: ...
def tan(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def abs(input: Tensor) -> Tensor: ...
def sign(input: Tensor) -> Tensor: ...
def floor(input: Tensor) -> Tensor: ...
def ceil(input: Tensor) -> Tensor: ...
def round(input: Tensor) -> Tensor: ...
def clamp(input: Tensor, min: Optional[Scalar] = None, max: Optional[Scalar] = None) -> Tensor: ...

# Reduction operations
def sum(input: Tensor, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> Tensor: ...
def mean(input: Tensor, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> Tensor: ...
def max(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
def min(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
def argmax(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def argmin(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...

# Concatenation and stacking
def cat(tensors: Sequence[Tensor], dim: int = 0) -> Tensor: ...
def stack(tensors: Sequence[Tensor], dim: int = 0) -> Tensor: ...
def split(tensor: Tensor, split_size_or_sections: Union[int, List[int]], dim: int = 0) -> List[Tensor]: ...
def chunk(tensor: Tensor, chunks: int, dim: int = 0) -> List[Tensor]: ...

# Autograd context managers
class _NoGradContext:
    """Context manager and decorator to disable gradient computation."""
    def __enter__(self) -> _NoGradContext: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __call__(self, func: Any) -> Any: ...

class _EnableGradContext:
    """Context manager and decorator to enable gradient computation."""
    def __enter__(self) -> _EnableGradContext: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __call__(self, func: Any) -> Any: ...

class _SetGradEnabledContext:
    """Context manager to set gradient computation mode."""
    def __enter__(self) -> _SetGradEnabledContext: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

def no_grad() -> _NoGradContext: ...
def enable_grad() -> _EnableGradContext: ...
def set_grad_enabled(mode: bool) -> _SetGradEnabledContext: ...

# FP8 scaling utilities
def fp8_max_value(fp8_dtype: DType) -> float: ...
def compute_amax(tensor: Tensor) -> float: ...
def compute_fp8_scale(amax: float, fp8_dtype: DType) -> float: ...
def quantize_to_fp8(
    input: Tensor,
    fp8_dtype: DType,
    scale: Optional[float] = None,
    stochastic_rounding: bool = False
) -> Tuple[Tensor, Any]: ...
def dequantize_from_fp8(fp8_tensor: Tensor, scale: float) -> Tensor: ...

# Version info
__version__: str
