"""Type stubs for tenzor.nn.functional module."""

from __future__ import annotations
from typing import Optional, List
from tenzor import Tensor

# Activation functions
def relu(input: Tensor, inplace: bool = False) -> Tensor: ...
def leaky_relu(input: Tensor, negative_slope: float = 0.01, inplace: bool = False) -> Tensor: ...
def elu(input: Tensor, alpha: float = 1.0, inplace: bool = False) -> Tensor: ...
def gelu(input: Tensor, approximate: str = 'none') -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def softmax(input: Tensor, dim: int) -> Tensor: ...
def log_softmax(input: Tensor, dim: int) -> Tensor: ...
def selu(input: Tensor, inplace: bool = False) -> Tensor: ...
def swish(input: Tensor) -> Tensor: ...
def mish(input: Tensor) -> Tensor: ...
def hardswish(input: Tensor) -> Tensor: ...
def hardsigmoid(input: Tensor) -> Tensor: ...
def glu(input: Tensor, dim: int = -1) -> Tensor: ...

# Loss functions
def mse_loss(input: Tensor, target: Tensor, reduction: str = 'mean') -> Tensor: ...
def l1_loss(input: Tensor, target: Tensor, reduction: str = 'mean') -> Tensor: ...
def cross_entropy(input: Tensor, target: Tensor, reduction: str = 'mean') -> Tensor: ...
def nll_loss(input: Tensor, target: Tensor, reduction: str = 'mean') -> Tensor: ...
def bce_loss(input: Tensor, target: Tensor, reduction: str = 'mean') -> Tensor: ...

# Functional operations
def dropout(input: Tensor, p: float = 0.5, training: bool = True) -> Tensor: ...
def linear(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None) -> Tensor: ...
def max_pool2d(input: Tensor, kernel_size: int, stride: int = -1, padding: int = 0) -> Tensor: ...
def avg_pool2d(input: Tensor, kernel_size: int, stride: int = -1, padding: int = 0) -> Tensor: ...
def batch_norm(input: Tensor, num_features: int, training: bool = True,
               momentum: float = 0.1, eps: float = 1e-5) -> Tensor: ...
def layer_norm(input: Tensor, normalized_shape: List[int], eps: float = 1e-5) -> Tensor: ...
def group_norm(input: Tensor, num_groups: int, num_channels: int, eps: float = 1e-5) -> Tensor: ...
def interpolate(input: Tensor, size: List[int], mode: str = 'bilinear',
                align_corners: bool = False) -> Tensor: ...
def embedding(input: Tensor, weight: Tensor, padding_idx: int = -1) -> Tensor: ...
def binary_cross_entropy_with_logits(input: Tensor, target: Tensor,
                                      reduction: str = 'mean') -> Tensor: ...

# Gradient clipping utilities
def clip_grad_norm_(parameters: List[Tensor], max_norm: float, norm_type: float = 2.0) -> float: ...
def clip_grad_value_(parameters: List[Tensor], clip_value: float) -> None: ...
