"""Type stubs for tenzor.nn.functional module."""

from __future__ import annotations
from typing import Optional, List, Tuple, Union

from tenzor import Tensor

# ============================================================================
# Activation functions
# ============================================================================
def relu(input: Tensor, inplace: bool = False) -> Tensor: ...
def relu6(input: Tensor, inplace: bool = False) -> Tensor: ...
def leaky_relu(input: Tensor, negative_slope: float = 0.01, inplace: bool = False) -> Tensor: ...
def elu(input: Tensor, alpha: float = 1.0, inplace: bool = False) -> Tensor: ...
def selu(input: Tensor, inplace: bool = False) -> Tensor: ...
def gelu(input: Tensor, approximate: str = 'none') -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def softmax(input: Tensor, dim: int) -> Tensor: ...
def log_softmax(input: Tensor, dim: int) -> Tensor: ...
def swish(input: Tensor) -> Tensor: ...
def mish(input: Tensor) -> Tensor: ...
def hardswish(input: Tensor) -> Tensor: ...
def hardsigmoid(input: Tensor) -> Tensor: ...
def softplus(input: Tensor, beta: float = 1.0, threshold: float = 20.0) -> Tensor: ...
def glu(input: Tensor, dim: int = -1) -> Tensor: ...
def prelu(input: Tensor, weight: Tensor) -> Tensor: ...

# ============================================================================
# Convolution functions
# ============================================================================
def conv1d(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None,
           stride: int = 1, padding: int = 0, dilation: int = 1,
           groups: int = 1) -> Tensor: ...
def conv2d(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None,
           stride: Union[int, Tuple[int, int]] = 1,
           padding: Union[int, Tuple[int, int]] = 0,
           dilation: Union[int, Tuple[int, int]] = 1,
           groups: int = 1) -> Tensor: ...
def conv3d(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None,
           stride: Union[int, Tuple[int, int, int]] = 1,
           padding: Union[int, Tuple[int, int, int]] = 0,
           dilation: Union[int, Tuple[int, int, int]] = 1,
           groups: int = 1) -> Tensor: ...
def conv_transpose2d(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None,
                     stride: Union[int, Tuple[int, int]] = 1,
                     padding: Union[int, Tuple[int, int]] = 0,
                     output_padding: Union[int, Tuple[int, int]] = 0,
                     groups: int = 1, dilation: int = 1) -> Tensor: ...

# ============================================================================
# Pooling functions
# ============================================================================
def max_pool1d(input: Tensor, kernel_size: int, stride: int = -1,
               padding: int = 0) -> Tensor: ...
def max_pool2d(input: Tensor, kernel_size: Union[int, Tuple[int, int]],
               stride: Union[int, Tuple[int, int]] = -1,
               padding: Union[int, Tuple[int, int]] = 0) -> Tensor: ...
def max_pool3d(input: Tensor, kernel_size: Union[int, Tuple[int, int, int]],
               stride: Union[int, Tuple[int, int, int]] = -1,
               padding: Union[int, Tuple[int, int, int]] = 0) -> Tensor: ...
def avg_pool1d(input: Tensor, kernel_size: int, stride: int = -1,
               padding: int = 0, count_include_pad: bool = True) -> Tensor: ...
def avg_pool2d(input: Tensor, kernel_size: Union[int, Tuple[int, int]],
               stride: Union[int, Tuple[int, int]] = -1,
               padding: Union[int, Tuple[int, int]] = 0,
               count_include_pad: bool = True) -> Tensor: ...
def avg_pool3d(input: Tensor, kernel_size: Union[int, Tuple[int, int, int]],
               stride: Union[int, Tuple[int, int, int]] = -1,
               padding: Union[int, Tuple[int, int, int]] = 0,
               count_include_pad: bool = True) -> Tensor: ...
def adaptive_avg_pool1d(input: Tensor, output_size: int) -> Tensor: ...
def adaptive_avg_pool2d(input: Tensor, output_size: Union[int, Tuple[int, int]]) -> Tensor: ...
def adaptive_avg_pool3d(input: Tensor, output_size: Union[int, Tuple[int, int, int]]) -> Tensor: ...
def adaptive_max_pool1d(input: Tensor, output_size: int) -> Tensor: ...
def adaptive_max_pool2d(input: Tensor, output_size: Union[int, Tuple[int, int]]) -> Tensor: ...
def adaptive_max_pool3d(input: Tensor, output_size: Union[int, Tuple[int, int, int]]) -> Tensor: ...

# ============================================================================
# Normalization functions
# ============================================================================
def batch_norm(input: Tensor, running_mean: Optional[Tensor] = None,
               running_var: Optional[Tensor] = None,
               weight: Optional[Tensor] = None, bias: Optional[Tensor] = None,
               training: bool = True, momentum: float = 0.1,
               eps: float = 1e-5) -> Tensor: ...
def layer_norm(input: Tensor, normalized_shape: List[int],
               weight: Optional[Tensor] = None, bias: Optional[Tensor] = None,
               eps: float = 1e-5) -> Tensor: ...
def group_norm(input: Tensor, num_groups: int, weight: Optional[Tensor] = None,
               bias: Optional[Tensor] = None, eps: float = 1e-5) -> Tensor: ...
def instance_norm(input: Tensor, running_mean: Optional[Tensor] = None,
                  running_var: Optional[Tensor] = None,
                  weight: Optional[Tensor] = None, bias: Optional[Tensor] = None,
                  training: bool = True, momentum: float = 0.1,
                  eps: float = 1e-5) -> Tensor: ...
def rms_norm(input: Tensor, normalized_shape: List[int],
             weight: Optional[Tensor] = None, eps: float = 1e-5) -> Tensor: ...

# ============================================================================
# Linear and attention functions
# ============================================================================
def linear(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None) -> Tensor: ...
def scaled_dot_product_attention(query: Tensor, key: Tensor, value: Tensor,
                                  attn_mask: Optional[Tensor] = None,
                                  dropout_p: float = 0.0,
                                  is_causal: bool = False) -> Tensor: ...

# ============================================================================
# Loss functions
# ============================================================================
def mse_loss(input: Tensor, target: Tensor, reduction: str = 'mean') -> Tensor: ...
def l1_loss(input: Tensor, target: Tensor, reduction: str = 'mean') -> Tensor: ...
def smooth_l1_loss(input: Tensor, target: Tensor, reduction: str = 'mean',
                   beta: float = 1.0) -> Tensor: ...
def huber_loss(input: Tensor, target: Tensor, reduction: str = 'mean',
               delta: float = 1.0) -> Tensor: ...
def cross_entropy(input: Tensor, target: Tensor, weight: Optional[Tensor] = None,
                  reduction: str = 'mean', label_smoothing: float = 0.0) -> Tensor: ...
def nll_loss(input: Tensor, target: Tensor, weight: Optional[Tensor] = None,
             reduction: str = 'mean') -> Tensor: ...
def bce_loss(input: Tensor, target: Tensor, weight: Optional[Tensor] = None,
             reduction: str = 'mean') -> Tensor: ...
def binary_cross_entropy_with_logits(input: Tensor, target: Tensor,
                                      weight: Optional[Tensor] = None,
                                      reduction: str = 'mean',
                                      pos_weight: Optional[Tensor] = None) -> Tensor: ...
def kl_div(input: Tensor, target: Tensor, reduction: str = 'mean',
           log_target: bool = False) -> Tensor: ...
def focal_loss(input: Tensor, target: Tensor, alpha: float = 0.25,
               gamma: float = 2.0, reduction: str = 'mean') -> Tensor: ...
def dice_loss(input: Tensor, target: Tensor, smooth: float = 1.0,
              reduction: str = 'mean') -> Tensor: ...
def ctc_loss(log_probs: Tensor, targets: Tensor, input_lengths: Tensor,
             target_lengths: Tensor, blank: int = 0,
             reduction: str = 'mean') -> Tensor: ...
def soft_margin_loss(input: Tensor, target: Tensor, reduction: str = 'mean') -> Tensor: ...
def hinge_embedding_loss(input: Tensor, target: Tensor, margin: float = 1.0,
                         reduction: str = 'mean') -> Tensor: ...
def poisson_nll_loss(input: Tensor, target: Tensor, log_input: bool = True,
                     full: bool = False, eps: float = 1e-8,
                     reduction: str = 'mean') -> Tensor: ...
def cosine_embedding_loss(input1: Tensor, input2: Tensor, target: Tensor,
                          margin: float = 0.0, reduction: str = 'mean') -> Tensor: ...
def triplet_margin_loss(anchor: Tensor, positive: Tensor, negative: Tensor,
                        margin: float = 1.0, p: float = 2.0, swap: bool = False,
                        reduction: str = 'mean') -> Tensor: ...
def margin_ranking_loss(input1: Tensor, input2: Tensor, target: Tensor,
                        margin: float = 0.0, reduction: str = 'mean') -> Tensor: ...
def multi_label_soft_margin_loss(input: Tensor, target: Tensor,
                                  weight: Optional[Tensor] = None,
                                  reduction: str = 'mean') -> Tensor: ...
def multi_margin_loss(input: Tensor, target: Tensor, p: int = 1,
                      margin: float = 1.0, weight: Optional[Tensor] = None,
                      reduction: str = 'mean') -> Tensor: ...
def gaussian_nll_loss(input: Tensor, target: Tensor, var: Tensor,
                      full: bool = False, eps: float = 1e-6,
                      reduction: str = 'mean') -> Tensor: ...

# ============================================================================
# Dropout functions
# ============================================================================
def dropout(input: Tensor, p: float = 0.5, training: bool = True) -> Tensor: ...
def dropout2d(input: Tensor, p: float = 0.5, training: bool = True) -> Tensor: ...
def alpha_dropout(input: Tensor, p: float = 0.5, training: bool = True) -> Tensor: ...

# ============================================================================
# Padding functions
# ============================================================================
def pad(input: Tensor, pad: List[int], mode: str = 'constant',
        value: float = 0.0) -> Tensor: ...

# ============================================================================
# Vision functions
# ============================================================================
def interpolate(input: Tensor, size: Optional[List[int]] = None,
                scale_factor: Optional[float] = None,
                mode: str = 'bilinear',
                align_corners: bool = False) -> Tensor: ...
def unfold(input: Tensor, kernel_size: int, dilation: int = 1,
           padding: int = 0, stride: int = 1) -> Tensor: ...
def fold(input: Tensor, output_size: Tuple[int, int], kernel_size: int,
         dilation: int = 1, padding: int = 0, stride: int = 1) -> Tensor: ...

# ============================================================================
# Embedding functions
# ============================================================================
def embedding(input: Tensor, weight: Tensor, padding_idx: int = -1,
              max_norm: Optional[float] = None, norm_type: float = 2.0,
              scale_grad_by_freq: bool = False) -> Tensor: ...
def one_hot(input: Tensor, num_classes: int = -1) -> Tensor: ...

# ============================================================================
# Gradient clipping utilities
# ============================================================================
def clip_grad_norm_(parameters: List[Tensor], max_norm: float,
                    norm_type: float = 2.0) -> float: ...
def clip_grad_value_(parameters: List[Tensor], clip_value: float) -> None: ...
