"""Type stubs for tenzor.quantization module."""

from __future__ import annotations
from typing import Optional, List, Dict, Any, Tuple
from enum import IntEnum

from tenzor import Tensor, Device, dtype
from tenzor.nn import Module

class QuantizationScheme(IntEnum):
    PER_TENSOR_SYMMETRIC = 0
    PER_TENSOR_ASYMMETRIC = 1
    PER_CHANNEL_SYMMETRIC = 2
    PER_CHANNEL_ASYMMETRIC = 3

class QuantDType(IntEnum):
    INT8 = 0
    UINT8 = 1
    INT4 = 2
    UINT4 = 3

class QuantizationParams:
    """Quantization parameters (scale, zero_point, dtype, scheme)."""
    @property
    def scale(self) -> Tensor: ...
    @property
    def zero_point(self) -> Tensor: ...
    @property
    def dtype(self) -> QuantDType: ...
    @property
    def scheme(self) -> QuantizationScheme: ...
    @property
    def axis(self) -> int: ...

class QuantizedTensor:
    """Quantized tensor with associated quantization parameters."""
    def dequantize(self) -> Tensor: ...
    def data(self) -> Tensor: ...
    @property
    def params(self) -> QuantizationParams: ...

# Quantization functions
def compute_quantization_params(input: Tensor,
                                 scheme: QuantizationScheme = QuantizationScheme.PER_TENSOR_SYMMETRIC,
                                 dtype: QuantDType = QuantDType.INT8,
                                 axis: int = -1) -> QuantizationParams: ...
def quantize_tensor(input: Tensor, params: QuantizationParams) -> QuantizedTensor: ...
def quantize_per_tensor_symmetric(input: Tensor, dtype: QuantDType = QuantDType.INT8) -> QuantizedTensor: ...
def quantize_per_tensor_asymmetric(input: Tensor, dtype: QuantDType = QuantDType.INT8) -> QuantizedTensor: ...
def quantize_per_channel_symmetric(input: Tensor, axis: int = 0,
                                    dtype: QuantDType = QuantDType.INT8) -> QuantizedTensor: ...
def quantize_per_channel_asymmetric(input: Tensor, axis: int = 0,
                                     dtype: QuantDType = QuantDType.INT8) -> QuantizedTensor: ...
def dequantize_tensor(input: QuantizedTensor) -> Tensor: ...

# Observers
class MinMaxObserver:
    def __init__(self, dtype: QuantDType = QuantDType.INT8,
                 scheme: QuantizationScheme = QuantizationScheme.PER_TENSOR_SYMMETRIC) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def calculate_qparams(self) -> QuantizationParams: ...
    def reset(self) -> None: ...

class MovingAverageMinMaxObserver:
    def __init__(self, averaging_constant: float = 0.01,
                 dtype: QuantDType = QuantDType.INT8,
                 scheme: QuantizationScheme = QuantizationScheme.PER_TENSOR_SYMMETRIC) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def calculate_qparams(self) -> QuantizationParams: ...
    def reset(self) -> None: ...

class HistogramObserver:
    def __init__(self, bins: int = 2048,
                 dtype: QuantDType = QuantDType.INT8,
                 scheme: QuantizationScheme = QuantizationScheme.PER_TENSOR_SYMMETRIC) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def calculate_qparams(self) -> QuantizationParams: ...
    def reset(self) -> None: ...

# Fake quantization
class FakeQuantize(Module):
    def __init__(self, observer: Any = None,
                 dtype: QuantDType = QuantDType.INT8,
                 scheme: QuantizationScheme = QuantizationScheme.PER_TENSOR_SYMMETRIC) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...

# Quantized layers
class QuantizedLinear(Module):
    def __init__(self, in_features: int, out_features: int,
                 bias: bool = True) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class QuantizedConv2d(Module):
    def __init__(self, in_channels: int, out_channels: int,
                 kernel_size: int, stride: int = 1, padding: int = 0,
                 bias: bool = True) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class QuantizedBatchNorm2d(Module):
    def __init__(self, num_features: int, eps: float = 1e-5,
                 momentum: float = 0.1) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

# QConfig
class QConfig:
    def __init__(self, activation: Any = None, weight: Any = None) -> None: ...
    @property
    def activation(self) -> Any: ...
    @property
    def weight(self) -> Any: ...
