"""Type stubs for tenzor.sparse module."""

from __future__ import annotations
from typing import Optional, List, Tuple
from enum import IntEnum

from tenzor import Tensor, Device, dtype

class SparseLayout(IntEnum):
    COO = 0
    CSR = 1
    CSC = 2
    BSR = 3

class SparseTensor:
    """Sparse tensor supporting COO, CSR, CSC, and BSR formats."""

    # Properties
    @property
    def layout(self) -> SparseLayout: ...
    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def dtype(self) -> dtype: ...
    @property
    def device(self) -> Device: ...
    @property
    def nnz(self) -> int: ...
    @property
    def sparse_dim(self) -> int: ...
    @property
    def dense_dim(self) -> int: ...

    def is_coalesced(self) -> bool: ...

    # COO accessors
    def indices(self) -> Tensor: ...
    def values(self) -> Tensor: ...

    # CSR accessors
    def crow_indices(self) -> Tensor: ...
    def col_indices(self) -> Tensor: ...

    # CSC accessors
    def ccol_indices(self) -> Tensor: ...
    def row_indices(self) -> Tensor: ...

    # BSR accessors
    def bsr_row_ptr(self) -> Tensor: ...
    def bsr_col_ind(self) -> Tensor: ...
    def block_size(self) -> Tuple[int, int]: ...

    # Conversions
    def to_dense(self) -> Tensor: ...
    def to_coo(self) -> SparseTensor: ...
    def to_csr(self) -> SparseTensor: ...
    def to_csc(self) -> SparseTensor: ...
    def to_bsr(self, block_size: Tuple[int, int]) -> SparseTensor: ...
    def coalesce(self) -> SparseTensor: ...
    def transpose(self) -> SparseTensor: ...

    # Device transfer
    def to(self, device: Device) -> SparseTensor: ...

# Factory functions
def sparse_coo(indices: Tensor, values: Tensor,
               shape: List[int], dtype: Optional[dtype] = None,
               device: Optional[Device] = None) -> SparseTensor: ...
def sparse_csr(crow_indices: Tensor, col_indices: Tensor, values: Tensor,
               shape: List[int], dtype: Optional[dtype] = None,
               device: Optional[Device] = None) -> SparseTensor: ...
def sparse_csc(ccol_indices: Tensor, row_indices: Tensor, values: Tensor,
               shape: List[int], dtype: Optional[dtype] = None,
               device: Optional[Device] = None) -> SparseTensor: ...
def sparse_bsr(bsr_row_ptr: Tensor, bsr_col_ind: Tensor, values: Tensor,
               shape: List[int], block_size: Tuple[int, int],
               dtype: Optional[dtype] = None,
               device: Optional[Device] = None) -> SparseTensor: ...

# Dense-to-sparse conversion
def to_sparse(dense: Tensor) -> SparseTensor: ...
def to_sparse_csr(dense: Tensor) -> SparseTensor: ...
def to_sparse_csc(dense: Tensor) -> SparseTensor: ...

# Sparse operations
def spmm(sparse: SparseTensor, dense: Tensor) -> Tensor: ...
def spmv(sparse: SparseTensor, vector: Tensor) -> Tensor: ...
def add(sparse: SparseTensor, dense: Tensor) -> Tensor: ...
def sparse_add(a: SparseTensor, b: SparseTensor) -> SparseTensor: ...
def mul(sparse: SparseTensor, scalar: float) -> SparseTensor: ...

# Audit E.10: sparse-sparse GEMM and triangular solve previously absent
# from sparse.pyi but reachable through the C++ bindings.
def spgemm(a: SparseTensor, b: SparseTensor) -> SparseTensor: ...

def triangular_solve(a: SparseTensor, b: Tensor, *,
                     upper: bool = True,
                     unit_triangular: bool = False) -> Tensor: ...
