if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/integration/test_model_persistence[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/integration/test_model_persistence[1]_tests.cmake")
else()
  add_test(test_model_persistence_NOT_BUILT test_model_persistence_NOT_BUILT)
endif()
