if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_backend_ops_parameterized[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_backend_ops_parameterized[1]_tests.cmake")
else()
  add_test(test_backend_ops_parameterized_NOT_BUILT test_backend_ops_parameterized_NOT_BUILT)
endif()
