if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_checkpoint[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_checkpoint[1]_tests.cmake")
else()
  add_test(test_checkpoint_NOT_BUILT test_checkpoint_NOT_BUILT)
endif()
