if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_optimizers_extended[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_optimizers_extended[1]_tests.cmake")
else()
  add_test(test_optimizers_extended_NOT_BUILT test_optimizers_extended_NOT_BUILT)
endif()
