if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_model_hub[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_model_hub[1]_tests.cmake")
else()
  add_test(test_model_hub_NOT_BUILT test_model_hub_NOT_BUILT)
endif()
