if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_gru[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_gru[1]_tests.cmake")
else()
  add_test(test_gru_NOT_BUILT test_gru_NOT_BUILT)
endif()
