if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_fp16_kernels[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_fp16_kernels[1]_tests.cmake")
else()
  add_test(test_fp16_kernels_NOT_BUILT test_fp16_kernels_NOT_BUILT)
endif()
