if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_convnext[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_convnext[1]_tests.cmake")
else()
  add_test(test_convnext_NOT_BUILT test_convnext_NOT_BUILT)
endif()
