if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_dropout[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_dropout[1]_tests.cmake")
else()
  add_test(test_dropout_NOT_BUILT test_dropout_NOT_BUILT)
endif()
