if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_slice_backend_parity[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_slice_backend_parity[1]_tests.cmake")
else()
  add_test(test_slice_backend_parity_NOT_BUILT test_slice_backend_parity_NOT_BUILT)
endif()
