if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_albert_t5[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_albert_t5[1]_tests.cmake")
else()
  add_test(test_albert_t5_NOT_BUILT test_albert_t5_NOT_BUILT)
endif()
