if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_conv1d[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_conv1d[1]_tests.cmake")
else()
  add_test(test_conv1d_NOT_BUILT test_conv1d_NOT_BUILT)
endif()
