if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_attention[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_attention[1]_tests.cmake")
else()
  add_test(test_attention_NOT_BUILT test_attention_NOT_BUILT)
endif()
