if(EXISTS "/home/lee/Projects/Tenzor/build_checkpoint/tests/test_jit[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_checkpoint/tests/test_jit[1]_tests.cmake")
else()
  add_test(test_jit_NOT_BUILT test_jit_NOT_BUILT)
endif()
