# Auto-generated by tenzor_discover_tests (DD.8 race-free wrapper).
# Holds a process-scoped lock so parallel ctest invocations
# don't both regenerate the *_tests.cmake at the same time.
file(LOCK [==[/home/lee/Projects/Tenzor/tests/nn/test_batchnorm3d[1]_discover.lock]==] GUARD PROCESS TIMEOUT 300
          RESULT_VARIABLE _tenzor_lock_rv)
if(NOT _tenzor_lock_rv EQUAL 0)
    message(WARNING
        "tenzor_discover_tests: failed to acquire lock on"
        " [==[/home/lee/Projects/Tenzor/tests/nn/test_batchnorm3d[1]_discover.lock]==] (rv=${_tenzor_lock_rv}); proceeding unlocked")
endif()
include([==[/home/lee/Projects/Tenzor/tests/nn/test_batchnorm3d[1]_include.cmake]==])
file(LOCK [==[/home/lee/Projects/Tenzor/tests/nn/test_batchnorm3d[1]_discover.lock]==] RELEASE)
