if(EXISTS "/home/lee/Projects/Tenzor/build_oneapi/tests/integration/test_data_parallel_integration[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_oneapi/tests/integration/test_data_parallel_integration[1]_tests.cmake")
else()
  add_test(test_data_parallel_integration_NOT_BUILT test_data_parallel_integration_NOT_BUILT)
endif()
