#!/usr/bin/env python3
"""
Generate C++ header with embedded Vulkan shader data.
Converts .spv files to C++ byte arrays at compile time.
"""

import sys
import os
from pathlib import Path


def generate_shader_header(shader_dir, output_file):
    """Generate C++ header with all shaders embedded as byte arrays."""

    shader_files = sorted(Path(shader_dir).glob("*.spv"))

    if not shader_files:
        print(f"Warning: No .spv files found in {shader_dir}")
        return

    with open(output_file, 'w') as f:
        f.write("// Auto-generated file - DO NOT EDIT\n")
        f.write("// Generated by scripts/embed_shaders.py\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstddef>\n")
        f.write("#include <string>\n")
        f.write("#include <unordered_map>\n\n")
        f.write("namespace tenzor {\n")
        f.write("namespace vulkan {\n")
        f.write("namespace embedded_shaders {\n\n")

        # Forward declare all arrays
        for shader_file in shader_files:
            shader_name = shader_file.stem
            f.write(f"extern const uint32_t {shader_name}_data[];\n")
            f.write(f"extern const size_t {shader_name}_size;\n\n")

        # Generate shader registry
        f.write("// Shader registry: maps shader name to (data, size)\n")
        f.write("struct ShaderData {\n")
        f.write("    const uint32_t* data;\n")
        f.write("    size_t size;\n")
        f.write("};\n\n")

        f.write("inline const std::unordered_map<std::string, ShaderData>& getShaderRegistry() {\n")
        f.write("    static const std::unordered_map<std::string, ShaderData> registry = {\n")

        for i, shader_file in enumerate(shader_files):
            shader_name = shader_file.stem
            comma = "," if i < len(shader_files) - 1 else ""
            f.write(f'        {{"{shader_name}", {{{shader_name}_data, {shader_name}_size}}}}{comma}\n')

        f.write("    };\n")
        f.write("    return registry;\n")
        f.write("}\n\n")

        f.write("} // namespace embedded_shaders\n")
        f.write("} // namespace vulkan\n")
        f.write("} // namespace tenzor\n")

    print(f"Generated header: {output_file}")

    # Generate implementation file
    impl_file = output_file.replace('.hpp', '.cpp')
    with open(impl_file, 'w') as f:
        f.write("// Auto-generated file - DO NOT EDIT\n")
        f.write("// Generated by scripts/embed_shaders.py\n\n")
        f.write(f'#include "{Path(output_file).name}"\n\n')
        f.write("namespace tenzor {\n")
        f.write("namespace vulkan {\n")
        f.write("namespace embedded_shaders {\n\n")

        for shader_file in shader_files:
            shader_name = shader_file.stem

            # Read binary data
            with open(shader_file, 'rb') as shader:
                data = shader.read()

            # Ensure data is 4-byte aligned (SPIR-V requirement)
            if len(data) % 4 != 0:
                padding = 4 - (len(data) % 4)
                data += b'\x00' * padding

            # Convert to uint32_t array
            uint32_data = []
            for i in range(0, len(data), 4):
                value = int.from_bytes(data[i:i+4], byteorder='little')
                uint32_data.append(value)

            # Write array
            f.write(f"const uint32_t {shader_name}_data[] = {{\n")

            # Write data in rows of 8 values for readability
            for i in range(0, len(uint32_data), 8):
                row = uint32_data[i:i+8]
                f.write("    ")
                f.write(", ".join(f"0x{v:08x}" for v in row))
                if i + 8 < len(uint32_data):
                    f.write(",\n")
                else:
                    f.write("\n")

            f.write("};\n\n")
            f.write(f"const size_t {shader_name}_size = {len(uint32_data)};\n\n")

        f.write("} // namespace embedded_shaders\n")
        f.write("} // namespace vulkan\n")
        f.write("} // namespace tenzor\n")

    print(f"Generated implementation: {impl_file}")
    print(f"Embedded {len(shader_files)} shaders")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: embed_shaders.py <shader_dir> <output_header>")
        sys.exit(1)

    shader_dir = sys.argv[1]
    output_file = sys.argv[2]

    generate_shader_header(shader_dir, output_file)
