#version 450

// Cast Float32 to Int32
layout(local_size_x_id = 0) in;

layout(set = 0, binding = 0) readonly buffer InputBuffer {
    float data[];
} input_buf;

layout(set = 0, binding = 1) writeonly buffer OutputBuffer {
    int data[];
} output_buf;

layout(push_constant) uniform PushConstants {
    uint num_elements;
} pc;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= pc.num_elements) return;
    output_buf.data[idx] = int(input_buf.data[idx]);
}
