#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_float64 : require

// Complex128 negate.
layout(local_size_x_id = 0) in;

layout(set = 0, binding = 0) buffer InputBuf  { double data_in[];  };
layout(set = 0, binding = 1) buffer OutputBuf { double data_out[]; };

layout(push_constant) uniform PushConstants {
    uint num_elements;  // number of COMPLEX elements
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= num_elements) return;
    data_out[idx * 2u]      = -data_in[idx * 2u];
    data_out[idx * 2u + 1u] = -data_in[idx * 2u + 1u];
}
