#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

// Fill tensor with ones for Int64 dtype
layout(local_size_x_id = 0) in;

layout(binding = 0) buffer Output { int64_t output_data[]; };

layout(push_constant) uniform PushConstants {
    uint n;  // Total number of elements
} params;

void main() {
    uint idx = gl_GlobalInvocationID.x;

    if (idx >= params.n) {
        return;
    }

    output_data[idx] = int64_t(1);
}
