if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_minimal_training[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_minimal_training[1]_tests.cmake")
else()
  add_test(test_minimal_training_NOT_BUILT test_minimal_training_NOT_BUILT)
endif()
