if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_rocm_kernels[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_rocm_kernels[1]_tests.cmake")
else()
  add_test(test_rocm_kernels_NOT_BUILT test_rocm_kernels_NOT_BUILT)
endif()
