if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_mask_rcnn[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_mask_rcnn[1]_tests.cmake")
else()
  add_test(test_mask_rcnn_NOT_BUILT test_mask_rcnn_NOT_BUILT)
endif()
