if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_gradcheck_extended[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_gradcheck_extended[1]_tests.cmake")
else()
  add_test(test_gradcheck_extended_NOT_BUILT test_gradcheck_extended_NOT_BUILT)
endif()
