if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_rnn[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_rnn[1]_tests.cmake")
else()
  add_test(test_rnn_NOT_BUILT test_rnn_NOT_BUILT)
endif()
