if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_distillation[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_distillation[1]_tests.cmake")
else()
  add_test(test_distillation_NOT_BUILT test_distillation_NOT_BUILT)
endif()
