if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_transformer_multidtype[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_transformer_multidtype[1]_tests.cmake")
else()
  add_test(test_transformer_multidtype_NOT_BUILT test_transformer_multidtype_NOT_BUILT)
endif()
