if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_creation_ops[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_creation_ops[1]_tests.cmake")
else()
  add_test(test_creation_ops_NOT_BUILT test_creation_ops_NOT_BUILT)
endif()
