if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_mixed_precision[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_mixed_precision[1]_tests.cmake")
else()
  add_test(test_mixed_precision_NOT_BUILT test_mixed_precision_NOT_BUILT)
endif()
