if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_simd[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_simd[1]_tests.cmake")
else()
  add_test(test_simd_NOT_BUILT test_simd_NOT_BUILT)
endif()
