if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_oneapi_backend[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_oneapi_backend[1]_tests.cmake")
else()
  add_test(test_oneapi_backend_NOT_BUILT test_oneapi_backend_NOT_BUILT)
endif()
