if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_serialization[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_serialization[1]_tests.cmake")
else()
  add_test(test_serialization_NOT_BUILT test_serialization_NOT_BUILT)
endif()
