if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_data_loading[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_data_loading[1]_tests.cmake")
else()
  add_test(test_data_loading_NOT_BUILT test_data_loading_NOT_BUILT)
endif()
