if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_dtype_edge_cases[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_dtype_edge_cases[1]_tests.cmake")
else()
  add_test(test_dtype_edge_cases_NOT_BUILT test_dtype_edge_cases_NOT_BUILT)
endif()
