if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_edge_cases_multidtype[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_edge_cases_multidtype[1]_tests.cmake")
else()
  add_test(test_edge_cases_multidtype_NOT_BUILT test_edge_cases_multidtype_NOT_BUILT)
endif()
