if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_zero_stage1[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_zero_stage1[1]_tests.cmake")
else()
  add_test(test_zero_stage1_NOT_BUILT test_zero_stage1_NOT_BUILT)
endif()
