if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_nn_additional_multidtype[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_nn_additional_multidtype[1]_tests.cmake")
else()
  add_test(test_nn_additional_multidtype_NOT_BUILT test_nn_additional_multidtype_NOT_BUILT)
endif()
