if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_gpt[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_gpt[1]_tests.cmake")
else()
  add_test(test_gpt_NOT_BUILT test_gpt_NOT_BUILT)
endif()
