if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_onnx_export[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_onnx_export[1]_tests.cmake")
else()
  add_test(test_onnx_export_NOT_BUILT test_onnx_export_NOT_BUILT)
endif()
