if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_optimizers_extended_multidtype[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_optimizers_extended_multidtype[1]_tests.cmake")
else()
  add_test(test_optimizers_extended_multidtype_NOT_BUILT test_optimizers_extended_multidtype_NOT_BUILT)
endif()
