if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_comparison_ops_multidtype[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_comparison_ops_multidtype[1]_tests.cmake")
else()
  add_test(test_comparison_ops_multidtype_NOT_BUILT test_comparison_ops_multidtype_NOT_BUILT)
endif()
