if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_autograd_additional[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_autograd_additional[1]_tests.cmake")
else()
  add_test(test_autograd_additional_NOT_BUILT test_autograd_additional_NOT_BUILT)
endif()
