if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/test_offload[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/test_offload[1]_tests.cmake")
else()
  add_test(test_offload_NOT_BUILT test_offload_NOT_BUILT)
endif()
