if(EXISTS "/home/lee/Projects/Tenzor/build_asan/tests/integration/test_multi_gpu[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_asan/tests/integration/test_multi_gpu[1]_tests.cmake")
else()
  add_test(test_multi_gpu_NOT_BUILT test_multi_gpu_NOT_BUILT)
endif()
