if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/test_efficientnet[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/test_efficientnet[1]_tests.cmake")
else()
  add_test(test_efficientnet_NOT_BUILT test_efficientnet_NOT_BUILT)
endif()
