add_test([=[BmmAutogradTest.ForwardPass]=]  /home/lee/Projects/Tenzor/bin/test_bmm_autograd [==[--gtest_filter=BmmAutogradTest.ForwardPass]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BmmAutogradTest.ForwardPass]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BmmAutogradTest.BackwardGradientA]=]  /home/lee/Projects/Tenzor/bin/test_bmm_autograd [==[--gtest_filter=BmmAutogradTest.BackwardGradientA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BmmAutogradTest.BackwardGradientA]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BmmAutogradTest.BackwardGradientB]=]  /home/lee/Projects/Tenzor/bin/test_bmm_autograd [==[--gtest_filter=BmmAutogradTest.BackwardGradientB]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BmmAutogradTest.BackwardGradientB]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BmmAutogradTest.LargerBatchSize]=]  /home/lee/Projects/Tenzor/bin/test_bmm_autograd [==[--gtest_filter=BmmAutogradTest.LargerBatchSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BmmAutogradTest.LargerBatchSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BmmAutogradTest.NoGradWhenDisabled]=]  /home/lee/Projects/Tenzor/bin/test_bmm_autograd [==[--gtest_filter=BmmAutogradTest.NoGradWhenDisabled]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BmmAutogradTest.NoGradWhenDisabled]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BmmAutogradTest.OneInputRequiresGrad]=]  /home/lee/Projects/Tenzor/bin/test_bmm_autograd [==[--gtest_filter=BmmAutogradTest.OneInputRequiresGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BmmAutogradTest.OneInputRequiresGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_bmm_autograd_TESTS BmmAutogradTest.ForwardPass BmmAutogradTest.BackwardGradientA BmmAutogradTest.BackwardGradientB BmmAutogradTest.LargerBatchSize BmmAutogradTest.NoGradWhenDisabled BmmAutogradTest.OneInputRequiresGrad)
