add_test([=[SIMDOpsTest.CPUFeatureDetection]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.CPUFeatureDetection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.CPUFeatureDetection]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.AddCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.AddCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.AddCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.SubCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.SubCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.SubCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.MulCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.MulCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.MulCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.DivCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.DivCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.DivCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.SqrtCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.SqrtCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.SqrtCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.FMACorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.FMACorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.FMACorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.ReLUCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.ReLUCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.ReLUCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.SigmoidCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.SigmoidCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.SigmoidCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.TanhCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.TanhCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.TanhCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.GeLUCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.GeLUCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.GeLUCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.AddPerformance]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.DISABLED_AddPerformance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.AddPerformance]=]  PROPERTIES DISABLED TRUE WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.MulPerformance]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.MulPerformance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.MulPerformance]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.ReLUPerformance]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.ReLUPerformance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.ReLUPerformance]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.UnalignedAccess]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.UnalignedAccess]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.UnalignedAccess]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.ZeroSize]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.ZeroSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.ZeroSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SIMDOpsTest.SingleElement]=]  /home/lee/Projects/Tenzor/bin/test_simd_ops [==[--gtest_filter=SIMDOpsTest.SingleElement]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SIMDOpsTest.SingleElement]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_simd_ops_TESTS SIMDOpsTest.CPUFeatureDetection SIMDOpsTest.AddCorrectness SIMDOpsTest.SubCorrectness SIMDOpsTest.MulCorrectness SIMDOpsTest.DivCorrectness SIMDOpsTest.SqrtCorrectness SIMDOpsTest.FMACorrectness SIMDOpsTest.ReLUCorrectness SIMDOpsTest.SigmoidCorrectness SIMDOpsTest.TanhCorrectness SIMDOpsTest.GeLUCorrectness SIMDOpsTest.AddPerformance SIMDOpsTest.MulPerformance SIMDOpsTest.ReLUPerformance SIMDOpsTest.UnalignedAccess SIMDOpsTest.ZeroSize SIMDOpsTest.SingleElement)
