add_test([=[VulkanOpsTest.MaxPool2dForward]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.MaxPool2dForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.MaxPool2dForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.AvgPool2dForward]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.AvgPool2dForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.AvgPool2dForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.AdaptiveMaxPool2d]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.AdaptiveMaxPool2d]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.AdaptiveMaxPool2d]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.AdaptiveAvgPool2d]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.AdaptiveAvgPool2d]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.AdaptiveAvgPool2d]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.Softmax]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.Softmax]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.Softmax]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.LogSoftmax]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.LogSoftmax]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.LogSoftmax]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.Argmax]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.Argmax]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.Argmax]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.Argmin]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.Argmin]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.Argmin]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.Variance]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.Variance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.Variance]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.Std]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.Std]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.Std]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.Prod]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.Prod]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.Prod]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.Embedding]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.Embedding]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.Embedding]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.Gather]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.Gather]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.Gather]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.IndexSelect]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.IndexSelect]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.IndexSelect]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.BenchmarkLargeConv2d]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.DISABLED_BenchmarkLargeConv2d]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.BenchmarkLargeConv2d]=]  PROPERTIES DISABLED TRUE WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VulkanOpsTest.BenchmarkLargeMatmul]=]  /home/lee/Projects/Tenzor/bin/test_vulkan_complete_ops [==[--gtest_filter=VulkanOpsTest.DISABLED_BenchmarkLargeMatmul]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VulkanOpsTest.BenchmarkLargeMatmul]=]  PROPERTIES DISABLED TRUE WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_vulkan_complete_ops_TESTS VulkanOpsTest.MaxPool2dForward VulkanOpsTest.AvgPool2dForward VulkanOpsTest.AdaptiveMaxPool2d VulkanOpsTest.AdaptiveAvgPool2d VulkanOpsTest.Softmax VulkanOpsTest.LogSoftmax VulkanOpsTest.Argmax VulkanOpsTest.Argmin VulkanOpsTest.Variance VulkanOpsTest.Std VulkanOpsTest.Prod VulkanOpsTest.Embedding VulkanOpsTest.Gather VulkanOpsTest.IndexSelect VulkanOpsTest.BenchmarkLargeConv2d VulkanOpsTest.BenchmarkLargeMatmul)
