add_test([=[Conv2dTest.ForwardShapeBasic]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.ForwardShapeBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.ForwardShapeBasic]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.ForwardShapeSingleBatch]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.ForwardShapeSingleBatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.ForwardShapeSingleBatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.ForwardShapeMultiBatch]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.ForwardShapeMultiBatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.ForwardShapeMultiBatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.KernelSize1x1]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.KernelSize1x1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.KernelSize1x1]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.KernelSize3x3]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.KernelSize3x3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.KernelSize3x3]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.KernelSize5x5]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.KernelSize5x5]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.KernelSize5x5]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.KernelSize7x7]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.KernelSize7x7]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.KernelSize7x7]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Stride1]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Stride1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Stride1]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Stride2]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Stride2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Stride2]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Stride3]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Stride3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Stride3]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Stride4]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Stride4]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Stride4]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Padding0]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Padding0]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Padding0]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Padding1]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Padding1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Padding1]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Padding2]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Padding2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Padding2]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.PaddingSamePadding]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.PaddingSamePadding]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.PaddingSamePadding]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Dilation1]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Dilation1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Dilation1]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Dilation2]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Dilation2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Dilation2]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Dilation3]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Dilation3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Dilation3]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.DilationWithPadding]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.DilationWithPadding]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.DilationWithPadding]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Groups1Standard]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Groups1Standard]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Groups1Standard]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.GroupsDepthwise]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.GroupsDepthwise]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.GroupsDepthwise]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Groups2]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Groups2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Groups2]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.Groups4]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.Groups4]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.Groups4]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.WithBias]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.WithBias]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.WithBias]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.NoBias]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.NoBias]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.NoBias]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.BiasEffect]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.BiasEffect]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.BiasEffect]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.WeightShape]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.WeightShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.WeightShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.WeightShapeWithGroups]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.WeightShapeWithGroups]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.WeightShapeWithGroups]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.EdgeCase1x1Image]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.EdgeCase1x1Image]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.EdgeCase1x1Image]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.EdgeCaseLargeImage]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.EdgeCaseLargeImage]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.EdgeCaseLargeImage]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.EdgeCaseVeryLargeBatch]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.EdgeCaseVeryLargeBatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.EdgeCaseVeryLargeBatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.EdgeCaseSingleChannel]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.EdgeCaseSingleChannel]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.EdgeCaseSingleChannel]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.EdgeCaseManyChannels]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.EdgeCaseManyChannels]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.EdgeCaseManyChannels]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.CombinedStrideAndPadding]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.CombinedStrideAndPadding]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.CombinedStrideAndPadding]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.CombinedAllParameters]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.CombinedAllParameters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.CombinedAllParameters]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.ConsistentOutput]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.ConsistentOutput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.ConsistentOutput]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.DifferentInputsSameSize]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.DifferentInputsSameSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.DifferentInputsSameSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.RequiresGrad]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.RequiresGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.RequiresGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.NoGradWhenInputNoGrad]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.NoGradWhenInputNoGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.NoGradWhenInputNoGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.BackwardPassExecutes]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.BackwardPassExecutes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.BackwardPassExecutes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.GradientCheckSmall]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.GradientCheckSmall]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.GradientCheckSmall]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.GradientNonZero]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.GradientNonZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.GradientNonZero]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.ParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.ParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.ParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.ParameterSizes]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.ParameterSizes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.ParameterSizes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.BottleneckConfiguration]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.BottleneckConfiguration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.BottleneckConfiguration]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.ResidualConnection]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.ResidualConnection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.ResidualConnection]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.MemoryEfficiencySmall]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.MemoryEfficiencySmall]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.MemoryEfficiencySmall]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.MemoryEfficiencyLarge]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.MemoryEfficiencyLarge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.MemoryEfficiencyLarge]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.InvalidInputDimensions]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.InvalidInputDimensions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.InvalidInputDimensions]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.InvalidChannelCount]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.InvalidChannelCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.InvalidChannelCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.InvalidGroupConfiguration]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.InvalidGroupConfiguration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.InvalidGroupConfiguration]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.VGGStyleBlock]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.VGGStyleBlock]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.VGGStyleBlock]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.InceptionStyleBranch]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.InceptionStyleBranch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.InceptionStyleBranch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.MobileNetDepthwiseSeparable]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.MobileNetDepthwiseSeparable]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.MobileNetDepthwiseSeparable]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv2dTest.ResNetBottleneck]=]  /home/lee/Projects/Tenzor/bin/test_conv2d [==[--gtest_filter=Conv2dTest.ResNetBottleneck]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv2dTest.ResNetBottleneck]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_conv2d_TESTS Conv2dTest.ForwardShapeBasic Conv2dTest.ForwardShapeSingleBatch Conv2dTest.ForwardShapeMultiBatch Conv2dTest.KernelSize1x1 Conv2dTest.KernelSize3x3 Conv2dTest.KernelSize5x5 Conv2dTest.KernelSize7x7 Conv2dTest.Stride1 Conv2dTest.Stride2 Conv2dTest.Stride3 Conv2dTest.Stride4 Conv2dTest.Padding0 Conv2dTest.Padding1 Conv2dTest.Padding2 Conv2dTest.PaddingSamePadding Conv2dTest.Dilation1 Conv2dTest.Dilation2 Conv2dTest.Dilation3 Conv2dTest.DilationWithPadding Conv2dTest.Groups1Standard Conv2dTest.GroupsDepthwise Conv2dTest.Groups2 Conv2dTest.Groups4 Conv2dTest.WithBias Conv2dTest.NoBias Conv2dTest.BiasEffect Conv2dTest.WeightShape Conv2dTest.WeightShapeWithGroups Conv2dTest.EdgeCase1x1Image Conv2dTest.EdgeCaseLargeImage Conv2dTest.EdgeCaseVeryLargeBatch Conv2dTest.EdgeCaseSingleChannel Conv2dTest.EdgeCaseManyChannels Conv2dTest.CombinedStrideAndPadding Conv2dTest.CombinedAllParameters Conv2dTest.ConsistentOutput Conv2dTest.DifferentInputsSameSize Conv2dTest.RequiresGrad Conv2dTest.NoGradWhenInputNoGrad Conv2dTest.BackwardPassExecutes Conv2dTest.GradientCheckSmall Conv2dTest.GradientNonZero Conv2dTest.ParameterCount Conv2dTest.ParameterSizes Conv2dTest.BottleneckConfiguration Conv2dTest.ResidualConnection Conv2dTest.MemoryEfficiencySmall Conv2dTest.MemoryEfficiencyLarge Conv2dTest.InvalidInputDimensions Conv2dTest.InvalidChannelCount Conv2dTest.InvalidGroupConfiguration Conv2dTest.VGGStyleBlock Conv2dTest.InceptionStyleBranch Conv2dTest.MobileNetDepthwiseSeparable Conv2dTest.ResNetBottleneck)
