add_test([=[Conv1dTest.BasicForward]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.BasicForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.BasicForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.WithPadding]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.WithPadding]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.WithPadding]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.WithStride]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.WithStride]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.WithStride]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.WithDilation]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.WithDilation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.WithDilation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.WithGroups]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.WithGroups]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.WithGroups]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.BackwardPass]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.BackwardPass]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.BackwardPass]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.WithBias]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.WithBias]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.WithBias]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.ParameterShapes]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.ParameterShapes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.ParameterShapes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.WithoutBias]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.WithoutBias]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.WithoutBias]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.InputValidation]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.InputValidation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.InputValidation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.BatchProcessing]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.BatchProcessing]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.BatchProcessing]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.ParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.ParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.ParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.WeightGradient]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.WeightGradient]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.WeightGradient]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Conv1dTest.SequenceData]=]  /home/lee/Projects/Tenzor/bin/test_conv1d [==[--gtest_filter=Conv1dTest.SequenceData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Conv1dTest.SequenceData]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_conv1d_TESTS Conv1dTest.BasicForward Conv1dTest.WithPadding Conv1dTest.WithStride Conv1dTest.WithDilation Conv1dTest.WithGroups Conv1dTest.BackwardPass Conv1dTest.WithBias Conv1dTest.ParameterShapes Conv1dTest.WithoutBias Conv1dTest.InputValidation Conv1dTest.BatchProcessing Conv1dTest.ParameterCount Conv1dTest.WeightGradient Conv1dTest.SequenceData)
