if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/test_batchnorm2d[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/test_batchnorm2d[1]_tests.cmake")
else()
  add_test(test_batchnorm2d_NOT_BUILT test_batchnorm2d_NOT_BUILT)
endif()
