if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/test_comparison_operators[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/test_comparison_operators[1]_tests.cmake")
else()
  add_test(test_comparison_operators_NOT_BUILT test_comparison_operators_NOT_BUILT)
endif()
