add_test([=[GradScalerTest.DefaultConstructor]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.DefaultConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.DefaultConstructor]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.CustomConstructor]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.CustomConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.CustomConstructor]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.ConstructorValidation]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.ConstructorValidation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.ConstructorValidation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.LossScaling]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.LossScaling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.LossScaling]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.GradientUnscaling]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.GradientUnscaling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.GradientUnscaling]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.NoInfNanDetection]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.NoInfNanDetection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.NoInfNanDetection]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.InfDetection]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.InfDetection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.InfDetection]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.NanDetection]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.NanDetection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.NanDetection]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.ScaleBackoff]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.ScaleBackoff]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.ScaleBackoff]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.ScaleGrowth]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.ScaleGrowth]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.ScaleGrowth]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.SGDIntegration]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.SGDIntegration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.SGDIntegration]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.AdamIntegration]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.AdamIntegration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.AdamIntegration]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.Reset]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.Reset]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.Reset]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.StateDictSaveLoad]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.StateDictSaveLoad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.StateDictSaveLoad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.MultipleParameters]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.MultipleParameters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.MultipleParameters]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.TrainingLoopSimulation]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.TrainingLoopSimulation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.TrainingLoopSimulation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.ScaleLimits]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.ScaleLimits]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.ScaleLimits]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradScalerTest.DoubleUnscaleProtection]=]  /home/lee/Projects/Tenzor/bin/test_grad_scaler [==[--gtest_filter=GradScalerTest.DoubleUnscaleProtection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradScalerTest.DoubleUnscaleProtection]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_grad_scaler_TESTS GradScalerTest.DefaultConstructor GradScalerTest.CustomConstructor GradScalerTest.ConstructorValidation GradScalerTest.LossScaling GradScalerTest.GradientUnscaling GradScalerTest.NoInfNanDetection GradScalerTest.InfDetection GradScalerTest.NanDetection GradScalerTest.ScaleBackoff GradScalerTest.ScaleGrowth GradScalerTest.SGDIntegration GradScalerTest.AdamIntegration GradScalerTest.Reset GradScalerTest.StateDictSaveLoad GradScalerTest.MultipleParameters GradScalerTest.TrainingLoopSimulation GradScalerTest.ScaleLimits GradScalerTest.DoubleUnscaleProtection)
