add_test([=[GradCheckTest.QuadraticFunction]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.QuadraticFunction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.QuadraticFunction]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.LinearFunction]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.LinearFunction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.LinearFunction]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.SumReduction]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.SumReduction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.SumReduction]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.ElementWiseOps]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.ElementWiseOps]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.ElementWiseOps]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.MultiDimensional]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.MultiDimensional]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.MultiDimensional]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.DetailedResult]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.DetailedResult]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.DetailedResult]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.Float64Precision]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.Float64Precision]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.Float64Precision]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.RequiresGradCheck]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.RequiresGradCheck]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.RequiresGradCheck]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.NumericalGradientComputation]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.NumericalGradientComputation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.NumericalGradientComputation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.CompareGradients]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.CompareGradients]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.CompareGradients]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.EpsilonSensitivity]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.EpsilonSensitivity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.EpsilonSensitivity]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.ScalarOutput]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.ScalarOutput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.ScalarOutput]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GradCheckTest.PerformanceBenchmark]=]  /home/lee/Projects/Tenzor/bin/test_gradcheck [==[--gtest_filter=GradCheckTest.PerformanceBenchmark]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GradCheckTest.PerformanceBenchmark]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_gradcheck_TESTS GradCheckTest.QuadraticFunction GradCheckTest.LinearFunction GradCheckTest.SumReduction GradCheckTest.ElementWiseOps GradCheckTest.MultiDimensional GradCheckTest.DetailedResult GradCheckTest.Float64Precision GradCheckTest.RequiresGradCheck GradCheckTest.NumericalGradientComputation GradCheckTest.CompareGradients GradCheckTest.EpsilonSensitivity GradCheckTest.ScalarOutput GradCheckTest.PerformanceBenchmark)
