add_test([=[ONNXImportTest.ImporterConstruction]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ImporterConstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ImporterConstruction]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.InvalidFilePath]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.InvalidFilePath]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.InvalidFilePath]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.EmptyFile]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.EmptyFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.EmptyFile]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.CorruptedProtobuf]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.CorruptedProtobuf]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.CorruptedProtobuf]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.VerboseMode]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.VerboseMode]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.VerboseMode]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.DeviceSelection]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.DeviceSelection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.DeviceSelection]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.DataTypeConversion]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.DataTypeConversion]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.DataTypeConversion]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.DataTypeToTenzor]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.DataTypeToTenzor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.DataTypeToTenzor]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ONNXTensorDataCreation]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ONNXTensorDataCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ONNXTensorDataCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ONNXAttributeGetters]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ONNXAttributeGetters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ONNXAttributeGetters]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ONNXNodeStructure]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ONNXNodeStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ONNXNodeStructure]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ONNXValueInfo]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ONNXValueInfo]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ONNXValueInfo]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ONNXGraphStructure]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ONNXGraphStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ONNXGraphStructure]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ONNXModelData]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ONNXModelData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ONNXModelData]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ImportContextValueRegistration]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ImportContextValueRegistration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ImportContextValueRegistration]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ImportContextModuleRegistration]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ImportContextModuleRegistration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ImportContextModuleRegistration]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ImportContextDevice]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ImportContextDevice]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ImportContextDevice]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.WeightLoadingConcept]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.WeightLoadingConcept]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.WeightLoadingConcept]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.BatchNormBufferAccess]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.BatchNormBufferAccess]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.BatchNormBufferAccess]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.Conv1dStructure]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.Conv1dStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.Conv1dStructure]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.Conv2dStructure]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.Conv2dStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.Conv2dStructure]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.BatchNorm2dStructure]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.BatchNorm2dStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.BatchNorm2dStructure]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.ImportFromBytesAPI]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.ImportFromBytesAPI]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.ImportFromBytesAPI]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.GetModelDataAPI]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.GetModelDataAPI]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.GetModelDataAPI]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ONNXImportTest.HighLevelImportAPI]=]  /home/lee/Projects/Tenzor/bin/test_onnx_import [==[--gtest_filter=ONNXImportTest.HighLevelImportAPI]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ONNXImportTest.HighLevelImportAPI]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_onnx_import_TESTS ONNXImportTest.ImporterConstruction ONNXImportTest.InvalidFilePath ONNXImportTest.EmptyFile ONNXImportTest.CorruptedProtobuf ONNXImportTest.VerboseMode ONNXImportTest.DeviceSelection ONNXImportTest.DataTypeConversion ONNXImportTest.DataTypeToTenzor ONNXImportTest.ONNXTensorDataCreation ONNXImportTest.ONNXAttributeGetters ONNXImportTest.ONNXNodeStructure ONNXImportTest.ONNXValueInfo ONNXImportTest.ONNXGraphStructure ONNXImportTest.ONNXModelData ONNXImportTest.ImportContextValueRegistration ONNXImportTest.ImportContextModuleRegistration ONNXImportTest.ImportContextDevice ONNXImportTest.WeightLoadingConcept ONNXImportTest.BatchNormBufferAccess ONNXImportTest.Conv1dStructure ONNXImportTest.Conv2dStructure ONNXImportTest.BatchNorm2dStructure ONNXImportTest.ImportFromBytesAPI ONNXImportTest.GetModelDataAPI ONNXImportTest.HighLevelImportAPI)
