add_test([=[CIoULossTest.PerfectOverlap]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.PerfectOverlap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.PerfectOverlap]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.NoOverlap]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.NoOverlap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.NoOverlap]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.PartialOverlap]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.PartialOverlap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.PartialOverlap]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.AspectRatioPenalty]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.AspectRatioPenalty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.AspectRatioPenalty]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.CenterDistancePenalty]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.CenterDistancePenalty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.CenterDistancePenalty]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.Monotonicity]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.Monotonicity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.Monotonicity]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.BatchProcessing]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.BatchProcessing]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.BatchProcessing]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.LossComputation]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.LossComputation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.LossComputation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.NumericalStability]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.NumericalStability]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.NumericalStability]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.Symmetry]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.Symmetry]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.Symmetry]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.ManualCalculation]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.ManualCalculation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.ManualCalculation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.BoxFormatConsistency]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.BoxFormatConsistency]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.BoxFormatConsistency]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.ZeroSizedBoxes]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.ZeroSizedBoxes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.ZeroSizedBoxes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.LargeBatchStressTest]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.LargeBatchStressTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.LargeBatchStressTest]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CIoULossTest.CIoUVsIoUImprovement]=]  /home/lee/Projects/Tenzor/bin/test_ciou_loss [==[--gtest_filter=CIoULossTest.CIoUVsIoUImprovement]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CIoULossTest.CIoUVsIoUImprovement]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_ciou_loss_TESTS CIoULossTest.PerfectOverlap CIoULossTest.NoOverlap CIoULossTest.PartialOverlap CIoULossTest.AspectRatioPenalty CIoULossTest.CenterDistancePenalty CIoULossTest.Monotonicity CIoULossTest.BatchProcessing CIoULossTest.LossComputation CIoULossTest.NumericalStability CIoULossTest.Symmetry CIoULossTest.ManualCalculation CIoULossTest.BoxFormatConsistency CIoULossTest.ZeroSizedBoxes CIoULossTest.LargeBatchStressTest CIoULossTest.CIoUVsIoUImprovement)
