add_test([=[BertTest.BertEmbeddingsForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertEmbeddingsForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertEmbeddingsForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertEmbeddingsWithTokenTypes]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertEmbeddingsWithTokenTypes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertEmbeddingsWithTokenTypes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertEmbeddingsGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertEmbeddingsGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertEmbeddingsGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertEncoderForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertEncoderForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertEncoderForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertEncoderWithMask]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertEncoderWithMask]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertEncoderWithMask]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertEncoderGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertEncoderGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertEncoderGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertPoolerForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertPoolerForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertPoolerForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertPoolerTanhActivation]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertPoolerTanhActivation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertPoolerTanhActivation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelWithAllInputs]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelWithAllInputs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelWithAllInputs]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelTrainEvalMode]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelTrainEvalMode]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelTrainEvalMode]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.SequenceClassificationForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.SequenceClassificationForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.SequenceClassificationForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.SequenceClassificationMultiClass]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.SequenceClassificationMultiClass]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.SequenceClassificationMultiClass]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.SequenceClassificationGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.SequenceClassificationGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.SequenceClassificationGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.TokenClassificationForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.TokenClassificationForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.TokenClassificationForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.TokenClassificationWithMask]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.TokenClassificationWithMask]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.TokenClassificationWithMask]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.TokenClassificationGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.TokenClassificationGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.TokenClassificationGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.QuestionAnsweringForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.QuestionAnsweringForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.QuestionAnsweringForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.QuestionAnsweringWithTokenTypes]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.QuestionAnsweringWithTokenTypes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.QuestionAnsweringWithTokenTypes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.QuestionAnsweringGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.QuestionAnsweringGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.QuestionAnsweringGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertConfigBase]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertConfigBase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertConfigBase]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertConfigLarge]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertConfigLarge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertConfigLarge]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.SequenceClassificationExtraParameters]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.SequenceClassificationExtraParameters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.SequenceClassificationExtraParameters]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelCPU]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelCPU]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelCPU]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelStateDictSaveLoad]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelStateDictSaveLoad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelStateDictSaveLoad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.ModelHubParameterNameMapping]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.ModelHubParameterNameMapping]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.ModelHubParameterNameMapping]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.ModelHubDownloadNotImplemented]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.ModelHubDownloadNotImplemented]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.ModelHubDownloadNotImplemented]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.ModelHubLoadCheckpointNotImplemented]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.ModelHubLoadCheckpointNotImplemented]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.ModelHubLoadCheckpointNotImplemented]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelShortSequence]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelShortSequence]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelShortSequence]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelLongSequence]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelLongSequence]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelLongSequence]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BertTest.BertModelBatchSizeOne]=]  /home/lee/Projects/Tenzor/bin/test_bert [==[--gtest_filter=BertTest.BertModelBatchSizeOne]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BertTest.BertModelBatchSizeOne]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_bert_TESTS BertTest.BertEmbeddingsForwardShape BertTest.BertEmbeddingsWithTokenTypes BertTest.BertEmbeddingsGradientFlow BertTest.BertEncoderForwardShape BertTest.BertEncoderWithMask BertTest.BertEncoderGradientFlow BertTest.BertPoolerForwardShape BertTest.BertPoolerTanhActivation BertTest.BertModelForwardShape BertTest.BertModelWithAllInputs BertTest.BertModelGradientFlow BertTest.BertModelTrainEvalMode BertTest.SequenceClassificationForwardShape BertTest.SequenceClassificationMultiClass BertTest.SequenceClassificationGradientFlow BertTest.TokenClassificationForwardShape BertTest.TokenClassificationWithMask BertTest.TokenClassificationGradientFlow BertTest.QuestionAnsweringForwardShape BertTest.QuestionAnsweringWithTokenTypes BertTest.QuestionAnsweringGradientFlow BertTest.BertConfigBase BertTest.BertConfigLarge BertTest.BertModelParameterCount BertTest.SequenceClassificationExtraParameters BertTest.BertModelCPU BertTest.BertModelStateDictSaveLoad BertTest.ModelHubParameterNameMapping BertTest.ModelHubDownloadNotImplemented BertTest.ModelHubLoadCheckpointNotImplemented BertTest.BertModelShortSequence BertTest.BertModelLongSequence BertTest.BertModelBatchSizeOne)
