add_test([=[FP16KernelsTest.ZerosFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.ZerosFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.ZerosFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.OnesFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.OnesFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.OnesFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.RandFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.RandFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.RandFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.RandnFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.RandnFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.RandnFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.FullFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.FullFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.FullFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.Float32ToFloat16Conversion]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.Float32ToFloat16Conversion]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.Float32ToFloat16Conversion]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.Int32ToFloat16Conversion]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.Int32ToFloat16Conversion]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.Int32ToFloat16Conversion]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.AdditionFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.AdditionFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.AdditionFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.SubtractionFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.SubtractionFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.SubtractionFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.MultiplicationFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.MultiplicationFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.MultiplicationFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.DivisionFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.DivisionFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.DivisionFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.BroadcastAdditionFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.BroadcastAdditionFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.BroadcastAdditionFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.BroadcastMultiplicationFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.BroadcastMultiplicationFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.BroadcastMultiplicationFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.MatmulTensorCoresAligned]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.MatmulTensorCoresAligned]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.MatmulTensorCoresAligned]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.MatmulTensorCoresNonAligned]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.MatmulTensorCoresNonAligned]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.MatmulTensorCoresNonAligned]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.MatmulTensorCoresRectangular]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.MatmulTensorCoresRectangular]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.MatmulTensorCoresRectangular]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.MatmulTensorCoresLarge]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.MatmulTensorCoresLarge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.MatmulTensorCoresLarge]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.BatchedMatmulFP16]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.BatchedMatmulFP16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.BatchedMatmulFP16]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.MixedPrecisionWorkflow]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.MixedPrecisionWorkflow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.MixedPrecisionWorkflow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.MemoryFootprint]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.MemoryFootprint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.MemoryFootprint]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FP16KernelsTest.ShapePreservation]=]  /home/lee/Projects/Tenzor/bin/test_fp16_kernels [==[--gtest_filter=FP16KernelsTest.ShapePreservation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FP16KernelsTest.ShapePreservation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_fp16_kernels_TESTS FP16KernelsTest.ZerosFP16 FP16KernelsTest.OnesFP16 FP16KernelsTest.RandFP16 FP16KernelsTest.RandnFP16 FP16KernelsTest.FullFP16 FP16KernelsTest.Float32ToFloat16Conversion FP16KernelsTest.Int32ToFloat16Conversion FP16KernelsTest.AdditionFP16 FP16KernelsTest.SubtractionFP16 FP16KernelsTest.MultiplicationFP16 FP16KernelsTest.DivisionFP16 FP16KernelsTest.BroadcastAdditionFP16 FP16KernelsTest.BroadcastMultiplicationFP16 FP16KernelsTest.MatmulTensorCoresAligned FP16KernelsTest.MatmulTensorCoresNonAligned FP16KernelsTest.MatmulTensorCoresRectangular FP16KernelsTest.MatmulTensorCoresLarge FP16KernelsTest.BatchedMatmulFP16 FP16KernelsTest.MixedPrecisionWorkflow FP16KernelsTest.MemoryFootprint FP16KernelsTest.ShapePreservation)
