add_test([=[UNetTest.UNetForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_unet [==[--gtest_filter=UNetTest.UNetForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UNetTest.UNetForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 1200)
add_test([=[UNetTest.UNetGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_unet [==[--gtest_filter=UNetTest.UNetGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UNetTest.UNetGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 1200)
add_test([=[UNetTest.UNetParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_unet [==[--gtest_filter=UNetTest.UNetParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UNetTest.UNetParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 1200)
add_test([=[UNetTest.UNetDifferentInputSizes]=]  /home/lee/Projects/Tenzor/bin/test_unet [==[--gtest_filter=UNetTest.UNetDifferentInputSizes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UNetTest.UNetDifferentInputSizes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 1200)
add_test([=[UNetTest.UNetBinarySegmentation]=]  /home/lee/Projects/Tenzor/bin/test_unet [==[--gtest_filter=UNetTest.UNetBinarySegmentation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UNetTest.UNetBinarySegmentation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 1200)
add_test([=[UNetTest.UNetGrayscaleInput]=]  /home/lee/Projects/Tenzor/bin/test_unet [==[--gtest_filter=UNetTest.UNetGrayscaleInput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UNetTest.UNetGrayscaleInput]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 1200)
set(  test_unet_TESTS UNetTest.UNetForwardShape UNetTest.UNetGradientFlow UNetTest.UNetParameterCount UNetTest.UNetDifferentInputSizes UNetTest.UNetBinarySegmentation UNetTest.UNetGrayscaleInput)
