add_test([=[ElectraTest.ConfigSmall]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.ConfigSmall]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.ConfigSmall]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.ConfigBase]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.ConfigBase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.ConfigBase]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.ConfigLarge]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.ConfigLarge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.ConfigLarge]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.ConfigToBertConfig]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.ConfigToBertConfig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.ConfigToBertConfig]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.GeneratorCreation]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.GeneratorCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.GeneratorCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.GeneratorForward]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.GeneratorForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.GeneratorForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.DiscriminatorCreation]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.DiscriminatorCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.DiscriminatorCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.DiscriminatorForward]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.DiscriminatorForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.DiscriminatorForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.PreTrainingCreation]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.PreTrainingCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.PreTrainingCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.PreTrainingForward]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.PreTrainingForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.PreTrainingForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.PreTrainingLossComputation]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.PreTrainingLossComputation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.PreTrainingLossComputation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.SequenceClassificationCreation]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.SequenceClassificationCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.SequenceClassificationCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.SequenceClassificationForward]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.SequenceClassificationForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.SequenceClassificationForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.TokenClassificationCreation]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.TokenClassificationCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.TokenClassificationCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.TokenClassificationForward]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.TokenClassificationForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.TokenClassificationForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.QuestionAnsweringCreation]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.QuestionAnsweringCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.QuestionAnsweringCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.QuestionAnsweringForward]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.QuestionAnsweringForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.QuestionAnsweringForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.GradientFlowSequenceClassification]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.GradientFlowSequenceClassification]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.GradientFlowSequenceClassification]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.GradientFlowPreTraining]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.GradientFlowPreTraining]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.GradientFlowPreTraining]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.GetGeneratorDiscriminator]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.GetGeneratorDiscriminator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.GetGeneratorDiscriminator]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.DiscriminatorBertModel]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.DiscriminatorBertModel]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.DiscriminatorBertModel]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.AllTokensUsedForTraining]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.AllTokensUsedForTraining]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.AllTokensUsedForTraining]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ElectraTest.BenchmarkInference]=]  /home/lee/Projects/Tenzor/bin/test_electra [==[--gtest_filter=ElectraTest.DISABLED_BenchmarkInference]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ElectraTest.BenchmarkInference]=]  PROPERTIES DISABLED TRUE WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_electra_TESTS ElectraTest.ConfigSmall ElectraTest.ConfigBase ElectraTest.ConfigLarge ElectraTest.ConfigToBertConfig ElectraTest.GeneratorCreation ElectraTest.GeneratorForward ElectraTest.DiscriminatorCreation ElectraTest.DiscriminatorForward ElectraTest.PreTrainingCreation ElectraTest.PreTrainingForward ElectraTest.PreTrainingLossComputation ElectraTest.SequenceClassificationCreation ElectraTest.SequenceClassificationForward ElectraTest.TokenClassificationCreation ElectraTest.TokenClassificationForward ElectraTest.QuestionAnsweringCreation ElectraTest.QuestionAnsweringForward ElectraTest.GradientFlowSequenceClassification ElectraTest.GradientFlowPreTraining ElectraTest.GetGeneratorDiscriminator ElectraTest.DiscriminatorBertModel ElectraTest.AllTokensUsedForTraining ElectraTest.BenchmarkInference)
