if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/test_tensor_lifetime[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/test_tensor_lifetime[1]_tests.cmake")
else()
  add_test(test_tensor_lifetime_NOT_BUILT test_tensor_lifetime_NOT_BUILT)
endif()
