add_test([=[GPTTest.EmbeddingsForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.EmbeddingsForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.EmbeddingsForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.EmbeddingsWithPositionIds]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.EmbeddingsWithPositionIds]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.EmbeddingsWithPositionIds]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.EmbeddingsGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.EmbeddingsGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.EmbeddingsGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.DecoderLayerForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.DecoderLayerForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.DecoderLayerForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.DecoderLayerWithCausalMask]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.DecoderLayerWithCausalMask]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.DecoderLayerWithCausalMask]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.DecoderLayerGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.DecoderLayerGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.DecoderLayerGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT2ModelForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT2ModelForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT2ModelForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT2ModelParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT2ModelParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT2ModelParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT2ModelGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT2ModelGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT2ModelGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT2LMHeadForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT2LMHeadForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT2LMHeadForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT2LMHeadLogitsRange]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT2LMHeadLogitsRange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT2LMHeadLogitsRange]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT2LMHeadGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT2LMHeadGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT2LMHeadGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT3ModelConstruction]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT3ModelConstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT3ModelConstruction]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT3LMHeadModelForward]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT3LMHeadModelForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT3LMHeadModelForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GeneratorGreedySearch]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GeneratorGreedySearch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GeneratorGreedySearch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GeneratorTopKSampling]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GeneratorTopKSampling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GeneratorTopKSampling]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GeneratorTopPSampling]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GeneratorTopPSampling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GeneratorTopPSampling]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GeneratorBeamSearch]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GeneratorBeamSearch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GeneratorBeamSearch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GeneratorGenericGenerate]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GeneratorGenericGenerate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GeneratorGenericGenerate]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT2ConfigPresets]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT2ConfigPresets]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT2ConfigPresets]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.GPT3ConfigPresets]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.GPT3ConfigPresets]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.GPT3ConfigPresets]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.EndToEndTextGeneration]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.EndToEndTextGeneration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.EndToEndTextGeneration]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GPTTest.TrainingModeVsEvalMode]=]  /home/lee/Projects/Tenzor/bin/test_gpt [==[--gtest_filter=GPTTest.TrainingModeVsEvalMode]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GPTTest.TrainingModeVsEvalMode]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_gpt_TESTS GPTTest.EmbeddingsForwardShape GPTTest.EmbeddingsWithPositionIds GPTTest.EmbeddingsGradientFlow GPTTest.DecoderLayerForwardShape GPTTest.DecoderLayerWithCausalMask GPTTest.DecoderLayerGradientFlow GPTTest.GPT2ModelForwardShape GPTTest.GPT2ModelParameterCount GPTTest.GPT2ModelGradientFlow GPTTest.GPT2LMHeadForwardShape GPTTest.GPT2LMHeadLogitsRange GPTTest.GPT2LMHeadGradientFlow GPTTest.GPT3ModelConstruction GPTTest.GPT3LMHeadModelForward GPTTest.GeneratorGreedySearch GPTTest.GeneratorTopKSampling GPTTest.GeneratorTopPSampling GPTTest.GeneratorBeamSearch GPTTest.GeneratorGenericGenerate GPTTest.GPT2ConfigPresets GPTTest.GPT3ConfigPresets GPTTest.EndToEndTextGeneration GPTTest.TrainingModeVsEvalMode)
