add_test([=[ViTTest.PatchEmbeddingForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.PatchEmbeddingForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.PatchEmbeddingForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.PatchEmbeddingGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.PatchEmbeddingGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.PatchEmbeddingGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.PatchEmbeddingNumPatches]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.PatchEmbeddingNumPatches]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.PatchEmbeddingNumPatches]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTEmbeddingsForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTEmbeddingsForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTEmbeddingsForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTEmbeddingsGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTEmbeddingsGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTEmbeddingsGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBaseConfig]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBaseConfig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBaseConfig]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBasePatch16ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBasePatch16ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBasePatch16ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBasePatch16GradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBasePatch16GradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBasePatch16GradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBasePatch16ParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBasePatch16ParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBasePatch16ParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBasePatch32Config]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBasePatch32Config]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBasePatch32Config]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBasePatch32ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBasePatch32ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBasePatch32ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBasePatch32GradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBasePatch32GradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBasePatch32GradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTLargeConfig]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTLargeConfig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTLargeConfig]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTLargePatch16ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTLargePatch16ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTLargePatch16ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTLargePatch16GradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTLargePatch16GradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTLargePatch16GradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTLargePatch16ParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTLargePatch16ParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTLargePatch16ParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTLargePatch32ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTLargePatch32ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTLargePatch32ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTHugeConfig]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTHugeConfig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTHugeConfig]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTHugePatch14ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTHugePatch14ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTHugePatch14ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTHugePatch14GradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTHugePatch14GradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTHugePatch14GradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTHugePatch14ParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTHugePatch14ParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTHugePatch14ParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTHugePatch16ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTHugePatch16ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTHugePatch16ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBaseBatchSizeOne]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBaseBatchSizeOne]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBaseBatchSizeOne]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBaseCustomClasses]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBaseCustomClasses]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBaseCustomClasses]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTBaseDifferentImageSize]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTBaseDifferentImageSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTBaseDifferentImageSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.PatchEmbeddingDifferentPatchSizes]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.PatchEmbeddingDifferentPatchSizes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.PatchEmbeddingDifferentPatchSizes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
add_test([=[ViTTest.ViTConfigNumPatchesCalculation]=]  /home/lee/Projects/Tenzor/bin/test_vit [==[--gtest_filter=ViTTest.ViTConfigNumPatchesCalculation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ViTTest.ViTConfigNumPatchesCalculation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 600)
set(  test_vit_TESTS ViTTest.PatchEmbeddingForwardShape ViTTest.PatchEmbeddingGradientFlow ViTTest.PatchEmbeddingNumPatches ViTTest.ViTEmbeddingsForwardShape ViTTest.ViTEmbeddingsGradientFlow ViTTest.ViTBaseConfig ViTTest.ViTBasePatch16ForwardShape ViTTest.ViTBasePatch16GradientFlow ViTTest.ViTBasePatch16ParameterCount ViTTest.ViTBasePatch32Config ViTTest.ViTBasePatch32ForwardShape ViTTest.ViTBasePatch32GradientFlow ViTTest.ViTLargeConfig ViTTest.ViTLargePatch16ForwardShape ViTTest.ViTLargePatch16GradientFlow ViTTest.ViTLargePatch16ParameterCount ViTTest.ViTLargePatch32ForwardShape ViTTest.ViTHugeConfig ViTTest.ViTHugePatch14ForwardShape ViTTest.ViTHugePatch14GradientFlow ViTTest.ViTHugePatch14ParameterCount ViTTest.ViTHugePatch16ForwardShape ViTTest.ViTBaseBatchSizeOne ViTTest.ViTBaseCustomClasses ViTTest.ViTBaseDifferentImageSize ViTTest.PatchEmbeddingDifferentPatchSizes ViTTest.ViTConfigNumPatchesCalculation)
