add_test([=[Float16Test.BasicConversion]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=Float16Test.BasicConversion]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Float16Test.BasicConversion]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Float16Test.SmallValues]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=Float16Test.SmallValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Float16Test.SmallValues]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Float16Test.LargeValues]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=Float16Test.LargeValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Float16Test.LargeValues]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Float16Test.SpecialValues]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=Float16Test.SpecialValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Float16Test.SpecialValues]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Float16Test.Precision]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=Float16Test.Precision]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Float16Test.Precision]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Float16Test.Comparison]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=Float16Test.Comparison]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Float16Test.Comparison]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BFloat16Test.BasicConversion]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=BFloat16Test.BasicConversion]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BFloat16Test.BasicConversion]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BFloat16Test.DynamicRange]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=BFloat16Test.DynamicRange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BFloat16Test.DynamicRange]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BFloat16Test.SpecialValues]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=BFloat16Test.SpecialValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BFloat16Test.SpecialValues]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BFloat16Test.Precision]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=BFloat16Test.Precision]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BFloat16Test.Precision]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BFloat16Test.Comparison]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=BFloat16Test.Comparison]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BFloat16Test.Comparison]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TensorFP16Test.CreationAndAccess]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=TensorFP16Test.CreationAndAccess]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TensorFP16Test.CreationAndAccess]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TensorFP16Test.DTypeSize]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=TensorFP16Test.DTypeSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TensorFP16Test.DTypeSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TensorFP16Test.DTypeName]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=TensorFP16Test.DTypeName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TensorFP16Test.DTypeName]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ConversionTest.Float16ToFloat32]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=ConversionTest.Float16ToFloat32]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ConversionTest.Float16ToFloat32]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ConversionTest.BFloat16ToFloat32]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=ConversionTest.BFloat16ToFloat32]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ConversionTest.BFloat16ToFloat32]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ConversionTest.RoundTrip]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=ConversionTest.RoundTrip]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ConversionTest.RoundTrip]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EdgeCaseTest.Float16Subnormals]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=EdgeCaseTest.Float16Subnormals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EdgeCaseTest.Float16Subnormals]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EdgeCaseTest.ZeroPreservation]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=EdgeCaseTest.ZeroPreservation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EdgeCaseTest.ZeroPreservation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PerformanceTest.Float16VsBFloat16Precision]=]  /home/lee/Projects/Tenzor/bin/test_fp16 [==[--gtest_filter=PerformanceTest.Float16VsBFloat16Precision]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PerformanceTest.Float16VsBFloat16Precision]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_fp16_TESTS Float16Test.BasicConversion Float16Test.SmallValues Float16Test.LargeValues Float16Test.SpecialValues Float16Test.Precision Float16Test.Comparison BFloat16Test.BasicConversion BFloat16Test.DynamicRange BFloat16Test.SpecialValues BFloat16Test.Precision BFloat16Test.Comparison TensorFP16Test.CreationAndAccess TensorFP16Test.DTypeSize TensorFP16Test.DTypeName ConversionTest.Float16ToFloat32 ConversionTest.BFloat16ToFloat32 ConversionTest.RoundTrip EdgeCaseTest.Float16Subnormals EdgeCaseTest.ZeroPreservation PerformanceTest.Float16VsBFloat16Precision)
