add_test([=[DataLoaderTest.DatasetCreation]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.DatasetCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.DatasetCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.TensorDatasetAccess]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.TensorDatasetAccess]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.TensorDatasetAccess]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.DatasetOutOfBounds]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.DatasetOutOfBounds]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.DatasetOutOfBounds]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.SingleThreadedLoading]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.SingleThreadedLoading]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.SingleThreadedLoading]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.DifferentBatchSizes]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.DifferentBatchSizes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.DifferentBatchSizes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.DropLastBatch]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.DropLastBatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.DropLastBatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.Shuffling]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.Shuffling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.Shuffling]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.MultiThreadedLoading]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.MultiThreadedLoading]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.MultiThreadedLoading]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.MultiThreadedPerformance]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.MultiThreadedPerformance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.MultiThreadedPerformance]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.IteratorOperations]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.IteratorOperations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.IteratorOperations]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.ResetLoader]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.ResetLoader]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.ResetLoader]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.ConcatDataset]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.ConcatDataset]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.ConcatDataset]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.ErrorHandling]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.ErrorHandling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.ErrorHandling]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.DataCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.DataCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.DataCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.TransformComposition]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.TransformComposition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.TransformComposition]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataLoaderTest.MNISTLikeData]=]  /home/lee/Projects/Tenzor/bin/test_dataloader [==[--gtest_filter=DataLoaderTest.MNISTLikeData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataLoaderTest.MNISTLikeData]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_dataloader_TESTS DataLoaderTest.DatasetCreation DataLoaderTest.TensorDatasetAccess DataLoaderTest.DatasetOutOfBounds DataLoaderTest.SingleThreadedLoading DataLoaderTest.DifferentBatchSizes DataLoaderTest.DropLastBatch DataLoaderTest.Shuffling DataLoaderTest.MultiThreadedLoading DataLoaderTest.MultiThreadedPerformance DataLoaderTest.IteratorOperations DataLoaderTest.ResetLoader DataLoaderTest.ConcatDataset DataLoaderTest.ErrorHandling DataLoaderTest.DataCorrectness DataLoaderTest.TransformComposition DataLoaderTest.MNISTLikeData)
