add_test([=[AutocastTest.BasicEnableDisable]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.BasicEnableDisable]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.BasicEnableDisable]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.NestedContexts]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.NestedContexts]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.NestedContexts]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.DisableWithinEnabled]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.DisableWithinEnabled]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.DisableWithinEnabled]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.ComputeHeavyOperations]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.ComputeHeavyOperations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.ComputeHeavyOperations]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.StabilityCriticalOperations]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.StabilityCriticalOperations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.StabilityCriticalOperations]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.DeviceTypeFiltering]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.DeviceTypeFiltering]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.DeviceTypeFiltering]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.BFloat16Dtype]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.BFloat16Dtype]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.BFloat16Dtype]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.InvalidDtype]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.InvalidDtype]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.InvalidDtype]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.AutocastGuard]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.AutocastGuard]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.AutocastGuard]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.AutocastDisabled]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.AutocastDisabled]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.AutocastDisabled]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.AutocastDtypeFloat32]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.AutocastDtypeFloat32]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.AutocastDtypeFloat32]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.LowPrecisionInput]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.LowPrecisionInput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.LowPrecisionInput]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.IntegerPreservation]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.IntegerPreservation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.IntegerPreservation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.HelperFunction]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.HelperFunction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.HelperFunction]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.MultipleCycles]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.MultipleCycles]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.MultipleCycles]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AutocastTest.DeviceTypePersistence]=]  /home/lee/Projects/Tenzor/bin/test_autocast [==[--gtest_filter=AutocastTest.DeviceTypePersistence]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AutocastTest.DeviceTypePersistence]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_autocast_TESTS AutocastTest.BasicEnableDisable AutocastTest.NestedContexts AutocastTest.DisableWithinEnabled AutocastTest.ComputeHeavyOperations AutocastTest.StabilityCriticalOperations AutocastTest.DeviceTypeFiltering AutocastTest.BFloat16Dtype AutocastTest.InvalidDtype AutocastTest.AutocastGuard AutocastTest.AutocastDisabled AutocastTest.AutocastDtypeFloat32 AutocastTest.LowPrecisionInput AutocastTest.IntegerPreservation AutocastTest.HelperFunction AutocastTest.MultipleCycles AutocastTest.DeviceTypePersistence)
