if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/test_onnx_import[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/test_onnx_import[1]_tests.cmake")
else()
  add_test(test_onnx_import_NOT_BUILT test_onnx_import_NOT_BUILT)
endif()
