add_test([=[ResNetTest.BasicBlockForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BasicBlockForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BasicBlockForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.BasicBlockForwardShapeWithStride]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BasicBlockForwardShapeWithStride]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BasicBlockForwardShapeWithStride]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.BasicBlockGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BasicBlockGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BasicBlockGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.BottleneckForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BottleneckForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BottleneckForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.BottleneckForwardShapeWithStride]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BottleneckForwardShapeWithStride]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BottleneckForwardShapeWithStride]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.BottleneckGroupedConvolution]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BottleneckGroupedConvolution]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BottleneckGroupedConvolution]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.BottleneckGradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BottleneckGradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BottleneckGradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet18Architecture]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet18Architecture]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet18Architecture]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet18ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet18ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet18ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet18CustomClasses]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet18CustomClasses]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet18CustomClasses]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet18DifferentInputSize]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet18DifferentInputSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet18DifferentInputSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet18GradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet18GradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet18GradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet34ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet34ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet34ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet34ParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet34ParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet34ParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet50ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet50ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet50ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet50ParameterCount]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet50ParameterCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet50ParameterCount]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet50GradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet50GradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet50GradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet101ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet101ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet101ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNet152ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNet152ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNet152ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNeXt50ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNeXt50ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNeXt50ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ResNeXt101ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ResNeXt101ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ResNeXt101ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.WideResNet50ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.WideResNet50ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.WideResNet50ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.WideResNet101ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.WideResNet101ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.WideResNet101ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.TrainingModeSwitch]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.TrainingModeSwitch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.TrainingModeSwitch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.BatchNormBehavior]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BatchNormBehavior]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BatchNormBehavior]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.StateDictSaveLoad]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.StateDictSaveLoad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.StateDictSaveLoad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.BasicBlockRejectsGroups]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BasicBlockRejectsGroups]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BasicBlockRejectsGroups]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.BasicBlockRejectsWideWidth]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.BasicBlockRejectsWideWidth]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.BasicBlockRejectsWideWidth]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.SmallBatchSize]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.SmallBatchSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.SmallBatchSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.LargeBatchSize]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.LargeBatchSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.LargeBatchSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ParameterSharing]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ParameterSharing]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ParameterSharing]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResNetTest.ZeroGrad]=]  /home/lee/Projects/Tenzor/bin/test_resnet [==[--gtest_filter=ResNetTest.ZeroGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResNetTest.ZeroGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_resnet_TESTS ResNetTest.BasicBlockForwardShape ResNetTest.BasicBlockForwardShapeWithStride ResNetTest.BasicBlockGradientFlow ResNetTest.BottleneckForwardShape ResNetTest.BottleneckForwardShapeWithStride ResNetTest.BottleneckGroupedConvolution ResNetTest.BottleneckGradientFlow ResNetTest.ResNet18Architecture ResNetTest.ResNet18ForwardShape ResNetTest.ResNet18CustomClasses ResNetTest.ResNet18DifferentInputSize ResNetTest.ResNet18GradientFlow ResNetTest.ResNet34ForwardShape ResNetTest.ResNet34ParameterCount ResNetTest.ResNet50ForwardShape ResNetTest.ResNet50ParameterCount ResNetTest.ResNet50GradientFlow ResNetTest.ResNet101ForwardShape ResNetTest.ResNet152ForwardShape ResNetTest.ResNeXt50ForwardShape ResNetTest.ResNeXt101ForwardShape ResNetTest.WideResNet50ForwardShape ResNetTest.WideResNet101ForwardShape ResNetTest.TrainingModeSwitch ResNetTest.BatchNormBehavior ResNetTest.StateDictSaveLoad ResNetTest.BasicBlockRejectsGroups ResNetTest.BasicBlockRejectsWideWidth ResNetTest.SmallBatchSize ResNetTest.LargeBatchSize ResNetTest.ParameterSharing ResNetTest.ZeroGrad)
