add_test([=[YOLOTest.YOLOv3ForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_yolo [==[--gtest_filter=YOLOTest.YOLOv3ForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[YOLOTest.YOLOv3ForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[YOLOTest.YOLOv3GradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_yolo [==[--gtest_filter=YOLOTest.YOLOv3GradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[YOLOTest.YOLOv3GradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[YOLOTest.YOLOv3TinyForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_yolo [==[--gtest_filter=YOLOTest.YOLOv3TinyForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[YOLOTest.YOLOv3TinyForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[YOLOTest.YOLOv5SmallForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_yolo [==[--gtest_filter=YOLOTest.YOLOv5SmallForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[YOLOTest.YOLOv5SmallForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[YOLOTest.YOLOv5MediumForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_yolo [==[--gtest_filter=YOLOTest.YOLOv5MediumForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[YOLOTest.YOLOv5MediumForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[YOLOTest.YOLOv5LargeForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_yolo [==[--gtest_filter=YOLOTest.YOLOv5LargeForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[YOLOTest.YOLOv5LargeForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[YOLOTest.YOLOv5XLargeForwardShape]=]  /home/lee/Projects/Tenzor/bin/test_yolo [==[--gtest_filter=YOLOTest.YOLOv5XLargeForwardShape]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[YOLOTest.YOLOv5XLargeForwardShape]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[YOLOTest.YOLOv5GradientFlow]=]  /home/lee/Projects/Tenzor/bin/test_yolo [==[--gtest_filter=YOLOTest.YOLOv5GradientFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[YOLOTest.YOLOv5GradientFlow]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[YOLOTest.YOLODifferentImageSizes]=]  /home/lee/Projects/Tenzor/bin/test_yolo [==[--gtest_filter=YOLOTest.YOLODifferentImageSizes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[YOLOTest.YOLODifferentImageSizes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_yolo_TESTS YOLOTest.YOLOv3ForwardShape YOLOTest.YOLOv3GradientFlow YOLOTest.YOLOv3TinyForwardShape YOLOTest.YOLOv5SmallForwardShape YOLOTest.YOLOv5MediumForwardShape YOLOTest.YOLOv5LargeForwardShape YOLOTest.YOLOv5XLargeForwardShape YOLOTest.YOLOv5GradientFlow YOLOTest.YOLODifferentImageSizes)
