add_test([=[MaxPool2dTest.ForwardShapeBasic]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.ForwardShapeBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.ForwardShapeBasic]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.ForwardShapeSingleBatch]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.ForwardShapeSingleBatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.ForwardShapeSingleBatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.ForwardShapeMultiBatch]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.ForwardShapeMultiBatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.ForwardShapeMultiBatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.KernelSize2]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.KernelSize2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.KernelSize2]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.KernelSize3]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.KernelSize3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.KernelSize3]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.KernelSize4]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.KernelSize4]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.KernelSize4]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.StrideDefault]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.StrideDefault]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.StrideDefault]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.Stride1]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.Stride1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.Stride1]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.Stride2]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.Stride2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.Stride2]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.Padding0]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.Padding0]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.Padding0]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.Padding1]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.Padding1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.Padding1]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.MaxValueSelection]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.MaxValueSelection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.MaxValueSelection]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.RequiresGrad]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.RequiresGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.RequiresGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.NoGradWhenInputNoGrad]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.NoGradWhenInputNoGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.NoGradWhenInputNoGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.BackwardPassExecutes]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.BackwardPassExecutes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.BackwardPassExecutes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.GradientNonZero]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.GradientNonZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.GradientNonZero]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MaxPool2dTest.GradientCheckSmall]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=MaxPool2dTest.GradientCheckSmall]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MaxPool2dTest.GradientCheckSmall]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.ForwardShapeBasic]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.ForwardShapeBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.ForwardShapeBasic]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.ForwardShapeSingleBatch]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.ForwardShapeSingleBatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.ForwardShapeSingleBatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.ForwardShapeMultiBatch]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.ForwardShapeMultiBatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.ForwardShapeMultiBatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.KernelSize2]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.KernelSize2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.KernelSize2]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.KernelSize3]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.KernelSize3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.KernelSize3]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.StrideDefault]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.StrideDefault]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.StrideDefault]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.Stride1]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.Stride1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.Stride1]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.Stride2]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.Stride2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.Stride2]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.AverageValueComputation]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.AverageValueComputation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.AverageValueComputation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.RequiresGrad]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.RequiresGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.RequiresGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.NoGradWhenInputNoGrad]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.NoGradWhenInputNoGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.NoGradWhenInputNoGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.BackwardPassExecutes]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.BackwardPassExecutes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.BackwardPassExecutes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.GradientNonZero]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.GradientNonZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.GradientNonZero]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AvgPool2dTest.GradientCheckSmall]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AvgPool2dTest.GradientCheckSmall]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AvgPool2dTest.GradientCheckSmall]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.ForwardShapeBasic]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.ForwardShapeBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.ForwardShapeBasic]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.ForwardShapeSquare]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.ForwardShapeSquare]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.ForwardShapeSquare]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.ForwardShapeRectangular]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.ForwardShapeRectangular]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.ForwardShapeRectangular]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.GlobalAveragePooling]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.GlobalAveragePooling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.GlobalAveragePooling]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.OutputLargerThanInput]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.OutputLargerThanInput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.OutputLargerThanInput]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.RequiresGrad]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.RequiresGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.RequiresGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.NoGradWhenInputNoGrad]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.NoGradWhenInputNoGrad]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.NoGradWhenInputNoGrad]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.BackwardPassExecutes]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.BackwardPassExecutes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.BackwardPassExecutes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.GradientNonZero]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.GradientNonZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.GradientNonZero]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AdaptiveAvgPool2dTest.GradientCheckSmall]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=AdaptiveAvgPool2dTest.GradientCheckSmall]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AdaptiveAvgPool2dTest.GradientCheckSmall]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.MaxPoolEdgeCase1x1]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.MaxPoolEdgeCase1x1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.MaxPoolEdgeCase1x1]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.AvgPoolEdgeCase1x1]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.AvgPoolEdgeCase1x1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.AvgPoolEdgeCase1x1]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.AdaptivePoolSameSize]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.AdaptivePoolSameSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.AdaptivePoolSameSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.LargeBatch]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.LargeBatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.LargeBatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.ManyChannels]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.ManyChannels]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.ManyChannels]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.InvalidInputDimensions]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.InvalidInputDimensions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.InvalidInputDimensions]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.SequentialPooling]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.SequentialPooling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.SequentialPooling]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.MixedPoolingTypes]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.MixedPoolingTypes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.MixedPoolingTypes]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.PoolingWithConvolution]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.PoolingWithConvolution]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.PoolingWithConvolution]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoolingTest.ResNetStyleBottleneck]=]  /home/lee/Projects/Tenzor/bin/test_pooling [==[--gtest_filter=PoolingTest.ResNetStyleBottleneck]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoolingTest.ResNetStyleBottleneck]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_pooling_TESTS MaxPool2dTest.ForwardShapeBasic MaxPool2dTest.ForwardShapeSingleBatch MaxPool2dTest.ForwardShapeMultiBatch MaxPool2dTest.KernelSize2 MaxPool2dTest.KernelSize3 MaxPool2dTest.KernelSize4 MaxPool2dTest.StrideDefault MaxPool2dTest.Stride1 MaxPool2dTest.Stride2 MaxPool2dTest.Padding0 MaxPool2dTest.Padding1 MaxPool2dTest.MaxValueSelection MaxPool2dTest.RequiresGrad MaxPool2dTest.NoGradWhenInputNoGrad MaxPool2dTest.BackwardPassExecutes MaxPool2dTest.GradientNonZero MaxPool2dTest.GradientCheckSmall AvgPool2dTest.ForwardShapeBasic AvgPool2dTest.ForwardShapeSingleBatch AvgPool2dTest.ForwardShapeMultiBatch AvgPool2dTest.KernelSize2 AvgPool2dTest.KernelSize3 AvgPool2dTest.StrideDefault AvgPool2dTest.Stride1 AvgPool2dTest.Stride2 AvgPool2dTest.AverageValueComputation AvgPool2dTest.RequiresGrad AvgPool2dTest.NoGradWhenInputNoGrad AvgPool2dTest.BackwardPassExecutes AvgPool2dTest.GradientNonZero AvgPool2dTest.GradientCheckSmall AdaptiveAvgPool2dTest.ForwardShapeBasic AdaptiveAvgPool2dTest.ForwardShapeSquare AdaptiveAvgPool2dTest.ForwardShapeRectangular AdaptiveAvgPool2dTest.GlobalAveragePooling AdaptiveAvgPool2dTest.OutputLargerThanInput AdaptiveAvgPool2dTest.RequiresGrad AdaptiveAvgPool2dTest.NoGradWhenInputNoGrad AdaptiveAvgPool2dTest.BackwardPassExecutes AdaptiveAvgPool2dTest.GradientNonZero AdaptiveAvgPool2dTest.GradientCheckSmall PoolingTest.MaxPoolEdgeCase1x1 PoolingTest.AvgPoolEdgeCase1x1 PoolingTest.AdaptivePoolSameSize PoolingTest.LargeBatch PoolingTest.ManyChannels PoolingTest.InvalidInputDimensions PoolingTest.SequentialPooling PoolingTest.MixedPoolingTypes PoolingTest.PoolingWithConvolution PoolingTest.ResNetStyleBottleneck)
