add_test([=[ChunkTest.BasicChunkEvenDivision]=]  /home/lee/Projects/Tenzor/bin/test_chunk [==[--gtest_filter=ChunkTest.BasicChunkEvenDivision]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChunkTest.BasicChunkEvenDivision]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChunkTest.BasicChunkUnevenDivision]=]  /home/lee/Projects/Tenzor/bin/test_chunk [==[--gtest_filter=ChunkTest.BasicChunkUnevenDivision]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChunkTest.BasicChunkUnevenDivision]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChunkTest.ChunkFewerThanDimensionSize]=]  /home/lee/Projects/Tenzor/bin/test_chunk [==[--gtest_filter=ChunkTest.ChunkFewerThanDimensionSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChunkTest.ChunkFewerThanDimensionSize]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChunkTest.ChunkAlongDifferentDimension]=]  /home/lee/Projects/Tenzor/bin/test_chunk [==[--gtest_filter=ChunkTest.ChunkAlongDifferentDimension]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChunkTest.ChunkAlongDifferentDimension]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChunkTest.ChunkNegativeDimension]=]  /home/lee/Projects/Tenzor/bin/test_chunk [==[--gtest_filter=ChunkTest.ChunkNegativeDimension]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChunkTest.ChunkNegativeDimension]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChunkTest.ChunkSingleChunk]=]  /home/lee/Projects/Tenzor/bin/test_chunk [==[--gtest_filter=ChunkTest.ChunkSingleChunk]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChunkTest.ChunkSingleChunk]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChunkTest.ChunkInvalidChunks]=]  /home/lee/Projects/Tenzor/bin/test_chunk [==[--gtest_filter=ChunkTest.ChunkInvalidChunks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChunkTest.ChunkInvalidChunks]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChunkTest.ChunkInvalidDimension]=]  /home/lee/Projects/Tenzor/bin/test_chunk [==[--gtest_filter=ChunkTest.ChunkInvalidDimension]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChunkTest.ChunkInvalidDimension]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChunkTest.ChunkDataCorrectness]=]  /home/lee/Projects/Tenzor/bin/test_chunk [==[--gtest_filter=ChunkTest.ChunkDataCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChunkTest.ChunkDataCorrectness]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_chunk_TESTS ChunkTest.BasicChunkEvenDivision ChunkTest.BasicChunkUnevenDivision ChunkTest.ChunkFewerThanDimensionSize ChunkTest.ChunkAlongDifferentDimension ChunkTest.ChunkNegativeDimension ChunkTest.ChunkSingleChunk ChunkTest.ChunkInvalidChunks ChunkTest.ChunkInvalidDimension ChunkTest.ChunkDataCorrectness)
