if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/test_losses_advanced[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/test_losses_advanced[1]_tests.cmake")
else()
  add_test(test_losses_advanced_NOT_BUILT test_losses_advanced_NOT_BUILT)
endif()
