if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/test_fp16[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/test_fp16[1]_tests.cmake")
else()
  add_test(test_fp16_NOT_BUILT test_fp16_NOT_BUILT)
endif()
