if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/test_split_operation[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/test_split_operation[1]_tests.cmake")
else()
  add_test(test_split_operation_NOT_BUILT test_split_operation_NOT_BUILT)
endif()
