add_test([=[RobertaTest.ConfigBase]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.ConfigBase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.ConfigBase]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.ConfigLarge]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.ConfigLarge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.ConfigLarge]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.ConfigToBertConfig]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.ConfigToBertConfig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.ConfigToBertConfig]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.ModelCreation]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.ModelCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.ModelCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.ModelForwardBase]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.ModelForwardBase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.ModelForwardBase]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.ModelForwardWithAttentionMask]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.ModelForwardWithAttentionMask]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.ModelForwardWithAttentionMask]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.SequenceClassificationCreation]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.SequenceClassificationCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.SequenceClassificationCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.SequenceClassificationForward]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.SequenceClassificationForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.SequenceClassificationForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.TokenClassificationCreation]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.TokenClassificationCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.TokenClassificationCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.TokenClassificationForward]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.TokenClassificationForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.TokenClassificationForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.QuestionAnsweringCreation]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.QuestionAnsweringCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.QuestionAnsweringCreation]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.QuestionAnsweringForward]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.QuestionAnsweringForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.QuestionAnsweringForward]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.GradientFlowSequenceClassification]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.GradientFlowSequenceClassification]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.GradientFlowSequenceClassification]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.NoSegmentEmbeddings]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.NoSegmentEmbeddings]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.NoSegmentEmbeddings]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RobertaTest.BenchmarkInference]=]  /home/lee/Projects/Tenzor/bin/test_roberta [==[--gtest_filter=RobertaTest.DISABLED_BenchmarkInference]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RobertaTest.BenchmarkInference]=]  PROPERTIES DISABLED TRUE WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_roberta_TESTS RobertaTest.ConfigBase RobertaTest.ConfigLarge RobertaTest.ConfigToBertConfig RobertaTest.ModelCreation RobertaTest.ModelForwardBase RobertaTest.ModelForwardWithAttentionMask RobertaTest.SequenceClassificationCreation RobertaTest.SequenceClassificationForward RobertaTest.TokenClassificationCreation RobertaTest.TokenClassificationForward RobertaTest.QuestionAnsweringCreation RobertaTest.QuestionAnsweringForward RobertaTest.GradientFlowSequenceClassification RobertaTest.NoSegmentEmbeddings RobertaTest.BenchmarkInference)
