add_test([=[ModelHubTest.SetAndGetCacheDir]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.SetAndGetCacheDir]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.SetAndGetCacheDir]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.SetAndGetConfig]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.SetAndGetConfig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.SetAndGetConfig]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.ComputeChecksum]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.ComputeChecksum]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.ComputeChecksum]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.VerifyChecksum_Valid]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.VerifyChecksum_Valid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.VerifyChecksum_Valid]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.VerifyChecksum_Invalid]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.VerifyChecksum_Invalid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.VerifyChecksum_Invalid]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.VerifyChecksum_Empty]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.VerifyChecksum_Empty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.VerifyChecksum_Empty]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.RegisterModel]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.RegisterModel]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.RegisterModel]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.RegisterMultipleModels]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.RegisterMultipleModels]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.RegisterMultipleModels]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.GetModelInfo_NotRegistered]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.GetModelInfo_NotRegistered]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.GetModelInfo_NotRegistered]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.ListRegisteredModels]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.ListRegisteredModels]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.ListRegisteredModels]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.CacheSize_Empty]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.CacheSize_Empty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.CacheSize_Empty]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.CacheSize_WithFiles]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.CacheSize_WithFiles]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.CacheSize_WithFiles]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.ClearCache]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.ClearCache]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.ClearCache]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.ListCachedModels]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.ListCachedModels]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.ListCachedModels]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.IsCached]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.IsCached]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.IsCached]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.GetCachedPath]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.GetCachedPath]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.GetCachedPath]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.RemoveFromCache]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.RemoveFromCache]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.RemoveFromCache]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.CleanCache_SizeLimit]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.CleanCache_SizeLimit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.CleanCache_SizeLimit]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.DownloadWeights_FileURL]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.DownloadWeights_FileURL]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.DownloadWeights_FileURL]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.DownloadWeights_Caching]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.DownloadWeights_Caching]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.DownloadWeights_Caching]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.DownloadWeights_ChecksumMismatch]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.DownloadWeights_ChecksumMismatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.DownloadWeights_ChecksumMismatch]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.DownloadPretrained_NotRegistered]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.DownloadPretrained_NotRegistered]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.DownloadPretrained_NotRegistered]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.ProgressCallback]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.ProgressCallback]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.ProgressCallback]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.DownloadStats]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.DownloadStats]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.DownloadStats]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.LoadPretrainedWeights_FileNotFound]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.LoadPretrainedWeights_FileNotFound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.LoadPretrainedWeights_FileNotFound]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.LoadPretrainedWeights_Strict]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.LoadPretrainedWeights_Strict]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.LoadPretrainedWeights_Strict]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.LoadPretrainedWeights_NonStrict]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.LoadPretrainedWeights_NonStrict]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.LoadPretrainedWeights_NonStrict]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.DefaultRegistry_ResNet]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.DefaultRegistry_ResNet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.DefaultRegistry_ResNet]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.DefaultRegistry_VGG]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.DefaultRegistry_VGG]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.DefaultRegistry_VGG]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.DefaultRegistry_MobileNet]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.DefaultRegistry_MobileNet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.DefaultRegistry_MobileNet]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.DefaultRegistry_EfficientNet]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.DefaultRegistry_EfficientNet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.DefaultRegistry_EfficientNet]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.ConcurrentAccess]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.ConcurrentAccess]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.ConcurrentAccess]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.EmptyModelName]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.EmptyModelName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.EmptyModelName]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.InvalidURL]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.InvalidURL]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.InvalidURL]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.ComputeChecksum_NonexistentFile]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.ComputeChecksum_NonexistentFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.ComputeChecksum_NonexistentFile]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelHubTest.VerifyChecksum_NonexistentFile]=]  /home/lee/Projects/Tenzor/bin/test_model_hub [==[--gtest_filter=ModelHubTest.VerifyChecksum_NonexistentFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelHubTest.VerifyChecksum_NonexistentFile]=]  PROPERTIES WORKING_DIRECTORY /home/lee/Projects/Tenzor/build_fresh/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_model_hub_TESTS ModelHubTest.SetAndGetCacheDir ModelHubTest.SetAndGetConfig ModelHubTest.ComputeChecksum ModelHubTest.VerifyChecksum_Valid ModelHubTest.VerifyChecksum_Invalid ModelHubTest.VerifyChecksum_Empty ModelHubTest.RegisterModel ModelHubTest.RegisterMultipleModels ModelHubTest.GetModelInfo_NotRegistered ModelHubTest.ListRegisteredModels ModelHubTest.CacheSize_Empty ModelHubTest.CacheSize_WithFiles ModelHubTest.ClearCache ModelHubTest.ListCachedModels ModelHubTest.IsCached ModelHubTest.GetCachedPath ModelHubTest.RemoveFromCache ModelHubTest.CleanCache_SizeLimit ModelHubTest.DownloadWeights_FileURL ModelHubTest.DownloadWeights_Caching ModelHubTest.DownloadWeights_ChecksumMismatch ModelHubTest.DownloadPretrained_NotRegistered ModelHubTest.ProgressCallback ModelHubTest.DownloadStats ModelHubTest.LoadPretrainedWeights_FileNotFound ModelHubTest.LoadPretrainedWeights_Strict ModelHubTest.LoadPretrainedWeights_NonStrict ModelHubTest.DefaultRegistry_ResNet ModelHubTest.DefaultRegistry_VGG ModelHubTest.DefaultRegistry_MobileNet ModelHubTest.DefaultRegistry_EfficientNet ModelHubTest.ConcurrentAccess ModelHubTest.EmptyModelName ModelHubTest.InvalidURL ModelHubTest.ComputeChecksum_NonexistentFile ModelHubTest.VerifyChecksum_NonexistentFile)
