if(EXISTS "/home/lee/Projects/Tenzor/build_fresh/tests/test_quantization[1]_tests.cmake")
  include("/home/lee/Projects/Tenzor/build_fresh/tests/test_quantization[1]_tests.cmake")
else()
  add_test(test_quantization_NOT_BUILT test_quantization_NOT_BUILT)
endif()
